### ISSUE TITLE
omxplayer: causes system to crash on udp: stream and also on keyboard inputs with .ts file

### ISSUE THREAD

**Issue by jviyer** [popcornmix/omxplayer#102]
-v output:
```
Version: 9b52cee[master]
=========================
```
1) played several .ts files.  Plays fine. except when I hit forward (right arrow) or reverse(left arrow) a few times (one at a time)  it causes this behaviour: video freezes on screem. Cannot get out of it without power reset. (because it also cause loss of the ssh connection) & just about any input.
This happens at random times. A couple of times it did play fine after I hit left arrow once or twice. But more often than not it is failing.
2) I streamed hdhomerun tuner output to udp port and when omxplayer starts playing stream but after playing a few seconds causes the above behaviour as well.

**Comment by Ruffio** [comment]
@popcornmix this issue should be closed as there have been no response to your question for a year
