### ISSUE TITLE
Seek not working in latest version 0.3.3~git20131119~9b52cee, but working in previous version 0.3.2

### ISSUE THREAD

**Issue by rcugut** [popcornmix/omxplayer#104]
Hi, I have a RaspberryPI model B running Raspbian and I installed the latest omxplayer 0.3.3 binary  from http://omxplayer.sconde.net/builds/omxplayer_0.3.3~git20131119~9b52cee_armhf.deb

Seek using keys or -l cmd line flag doesn't work: OSD shows the seek seconds, but the audio plays for a fraction of second and the video freezes frame. If I press the arrow keys (forward or back) it just moves a few seconds to the designated timestamp, and same behaviour: the audio plays for a fraction of a second, and it freezes again. Howver, if I play the video from the start, and never seek, it works from begining-end.
I downgraded to version 0.3.2, downloaded from the same builds site, and seek is working without any issues (both by keypress during playback or the -l cmdline flag)

omxplayer -i  dump:
```
[avi @ 0x9d24e0] non-interleaved AVI
Input #0, avi, from 'CSI.Miami.S10E07.Sinner.Takes.All.avi':
  Metadata:
    encoder         : MEncoder r33883
  Duration: 00:43:20.60, start: 0.000000, bitrate: 1045 kb/s
    Stream #0:0: Video: h264 (Constrained Baseline) (h264 / 0x34363268), yuv420p, 624x352 [SAR 1:1 DAR 39:22], SAR 180224:180219 DAR 8192:4621, 23.98 fps, 23.98 tbr, 23.98 tbn, 47.95 tbc
    Stream #0:1: Audio: aac (mp[0][0] / 0x706D), 44100 Hz, stereo, fltp, 163 kb/s
```

**Comment by Ruffio** [comment]
@popcornmix I believe this can be closed.

**Comment by rcugut** [comment]
this works correctly in 0.3.5 [6ee9a0a]
