### ISSUE TITLE
Left mouse click as keyboard shortcut

### ISSUE THREAD

**Issue by alattgsi** [popcornmix/omxplayer#111]
I am building a project for a touchscreen, and I'd really like Omxplayer to respond to a mouse click (touching the screen)

I have tried using the --key-config parameter with variations of the following parameters in the key config file:
PAUSE:hex 0x01
PAUSE:hex 0x0001
PAUSE:s
PAUSE:p

The s and p keys work but the left mouse click doesn't. 
Do I have the wrong hex code for left mouse click?
If so please can you let me know what it should be.
If not what can I do to pick up a mouse event whilst playing Omxplayer.
Thanks
Al

**Comment by Ruffio** [comment]
Should this be closed as it is a feature request that is not gping to be implemented?
