### ISSUE TITLE
Seek to a specific point in time, and a random gray garbage screen when done.

### ISSUE THREAD

**Issue by danielmorena** [popcornmix/omxplayer#115]
Sometime ago i've successfully implemented a cluster of omxplayer playing in sync over network using UDP multicast in a head (providing time) / body (consuming time) configuration. And recently rewrote the solution to work this implementation, as it's more up to date (as noticed in the huceke repository) and with more features, like rotating the screen and so on, which interest me. 
I've got two major problems with my implementation using both code bases and need some advice to figuring it out. 
First one: when i seek using the the omxreader SeekTime, using huceke repository base code and depending on the codec used i get a gray screen for some frames, like garbage in GPU. I need to use a non temporal codec like motionjpeg or h264 with all frames as keyframes to work around, but is PITA and files become huge. This is apparently fixed in this repository code, but i will really appreciate a better solution if any.
The second one is the seek time, which was super fast in the other (huceke) version is slow (almost 2 sec depending on the "distance") in this version, which is destroying my solution. By the time the playhead is in the right position, the sync is off again, which leads to a long series of hiccups in the bodies. More hiccups than sync.
I've read all the .cpp and can't figure out where i can code a drop frame, or at least a more responsive seek.

To seek i'm using this block of code in the omxplayer.cpp main function, where "jump" is the new time in seconds:
```
if(jump >= 0.0)
		{
			// grab and parse the times
			double cur_time=m_av_clock->OMXMediaTime();
			double new_time=jump * 1000.0;
			
			// handle subtitles
			if(m_has_subtitle)
			{
				m_player_subtitles.Pause();
			}

			// stop the main clock
			m_av_clock->OMXStop();
			
			// send the stream reader to desired point
			m_omx_reader.SeekTime(new_time
								  , (new_time < cur_time) ? AVSEEK_FLAG_BACKWARD : 0
								  , &startpts);
			// flush the streams
			FlushStreams(startpts);
			
			// clear the flag
			jump=-1.0;
			
			// execute the pause
			if(m_Pause)
			{
				// change the velocity to zero
				SetSpeed(OMX_PLAYSPEED_PAUSE);
				
				// stop the clock
				m_av_clock->OMXPause();
				
				// pause the subtitles clock
				if(m_has_subtitle)
				{
					m_player_subtitles.Pause();
				}
			}
			else
			{
				// if not the pause case, restart the clock
				m_av_clock->OMXStart(startpts);
			}
			
			// if not the pause case, restar the subtitles
			if(m_has_subtitle && !m_Pause)
			{
				m_player_subtitles.Resume();
			}

			// continue the loop, avoiding errors in the packet reader
			continue;
		}
```
Any suggestions will be appreciated!
Thanks in advance.

**Comment by Ruffio** [comment]
@danielmorena have you got time to look more into it?

**Comment by popcornmix** [comment]
I suspect this issue won't occur anymore. See https://github.com/popcornmix/omxplayer/commit/7c752d37a2c761659ada5fdb1323334447df3712
