### ISSUE TITLE
writing bytes to omxplayer's OutputStream from java

### ISSUE THREAD

**Issue by jimpil** [popcornmix/omxplayer#116]
Hello everyone,

First of all I should clarify that this is probably not an issue with omxplayer...it seems that some people have managed to spawn and control an omxplayer Process from Java code but I can't find any working code anywhere! Now that oracle-java-7 is in the official repos, I've written a rudimentary playlist GUI for the pi. 

I can successfully spawn the omxplayer process but there is no way to control it from my code...The Process runs until the video/song finishes and then it starts over!!! Only option is to reboot...I've literally tried everything and I am following all the best practices (buffered streams and ProcessBuilder). Here is the code snippet that should write the bytes for quitting omxplayer (q char):

``` java

if (p != null){ //p is the Process object return by ProcessBuilder.start()
BufferedOutputStream stdin = new BufferedOutputStream(p.getOutputStream()); 
String x = "q";
stdin.write(x.getBytes());
stdin.flush();
}

```

However ,the above code pattern does not work for anything (volume, pausing, quitting etc). I 've even tried putting the code that starts the Process in a separate thread and still nothing.

I do realise that this is not the most appropriate place to ask for help but I am slightly desperate! I cannot think of anything else to try out...To my surprise, p.destroy() doesn't work either!!! Any help/pointers are greatly appreciated...

many thanks in advance,
Jim

**Comment by jehutting** [comment]
I vote for closing this one.

**Comment by jehutting** [comment]
@jimpil can you close this issue?

**Comment by jimpil** [comment]
Sure, closing it now...
