### ISSUE TITLE
OMX Player not linking any more.

### ISSUE THREAD

**Issue by JontomXire** [popcornmix/omxplayer#117]
OMX Player used to build and link perfectly. But when I tried again today it didn't. I have been mucking about with packages installed on my RPi and just updated my copy of the repository from here, but...

Firstly there were a load of symbols like vgCreateImage which come from OpenVG. I have libopenvg1-mesa:armhf installed on my Raspberry Pi and the libraries were available, but the makefile just wasn't trying to link to that library.

I added "-lOpenVG" to the LD_FLAGS in the makefile and now the list of unresolved symbols is reduced to...

/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `platform_get_global_image_info'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_error_assist'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_pointer_map_delete'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `rpc_send_ctrl_longest'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_get_type_size'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `client_process_state'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_global_image_map_insert'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `rpc_begin'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `rpc_flush'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_vector_extend'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `platform_release_global_image'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `platform_client_release'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `rpc_send_ctrl_end'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `rpc_send_bulk_gather'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `rpc_recv'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_pointer_map_insert'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_pointer_map_lookup'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `rpc_send_ctrl_write'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_platform_malloc'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_global_image_map_init'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_vector_init'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `rpc_send_ctrl_begin'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_vector_term'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_global_image_map_lookup'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `platform_client_lock'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `platform_acquire_global_image'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_global_image_map_term'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_clip_rect2'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `platform_tls_get'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_pointer_map_iterate'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_pointer_map_term'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `client_tls'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `rpc_send_bulk'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `rpc_high_priority_begin'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `rpc_high_priority_end'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_platform_free'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_vector_clear'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `khrn_pointer_map_init'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `rpc_end'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `khrn_global_image_map_delete'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libOpenVG.so: undefined reference to `egl_config_get_mask_format'
/home/jx/dev/raspberry_pi/rootfs/opt/vc/lib//libGLESv2.so: undefined reference to `platform_memcpy'

As far as I can tell, these all come from something called khronos, but what that is and how I can get it for me RPi I don't know.

---

Why doesn't the Makefile link in the required libraries in the link line?

I also want to know how come it linked before and doesn't now, but I don't suppose you can help me with that. :)

**Comment by Ruffio** [comment]
@popcornmix this issue can be closed now
