### ISSUE TITLE
Playback freezes / chops heavily after using keyboard commands (pause, seek, volume+-, ect)

### ISSUE THREAD

**Issue by lewisdiamond** [popcornmix/omxplayer#119]
This happens only when using the -b option.

If any other info is needed, please let me know. Also, if anyone can help me investigating this, I could potentially patch it and submit a pull request. I'm a developer but not very familiar with ffmpeg, omxplayer and video playback in general.

**Comment by Ruffio** [comment]
@levisdiamond is this still an issue?

**Comment by lewisdiamond** [comment]
I'm no longer using omxplayer, I setup xbmc/kodi.

**Comment by Ruffio** [comment]
@popcornmix this can be closed.
