### ISSUE TITLE
omxplayer occasionally terminates incorrectly at the end of a track

### ISSUE THREAD

**Issue by KenT2** [popcornmix/omxplayer#124]
omxplayer -v gives:
        Build date: Mon, 16 Dec 2013 22:06:42 +0100
        Version   : b34143c [master]

omxplayer occasionally terminates incorrectly at the end of a track. This occurs for the 4 videos tested and at random. Sometimes after tens of iterations sometimetimes after thousands.

Using the script below and also an instrumented version of Pi Presents (which uses noahs pexpect to interface with omxplayer) I have observed three different symptoms. All seem to occur with a timestamp that is near the end of a track:

a. TIMEOUT -  The stats output produced by the -s option stops during a track so there is no have a nice day, the last line is often truncated. Following this the omxplayer and omxplayer.bin processes terminate naturally.

example of last line of output: 

M:12348800 V:  1.53s      0k/  4800k A:  1.12   6.14s/  2.00s Cv:     0k Ca:     8k  
M:12524561 V:

b. ABORT - omxplayer.bin appears to abort before outputting have a nice day. The abort is reported by omxplayer. Following this the omxplayer and omxplayer.bin processes terminate naturally.

examples of error report:
/usr/bin/omxplayer: line 56:  3756 Aborted                 LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"

c. HANG - have a nice day is output, following this the omxplayer and omxplayer.bin processes do not terminate naturally. Seems to occur only on a short video (1sec.mp4)

The script used to demonstrate these is:
# !/bin/sh

while :
   do
        omxplayer -s -g -olocal 5sec.mp4 1>>log.log 2>>error.log
        if  [ -s error.log ] 
        then
           break
        fi
   done

 just place it in an empty directory, put videos to be played in the same directory, make it executable and run it with ./omx.sh. Wait until videos stop playing then look at the logs for the last iteration.

I am currently testing a version of Pi Presents which has workarounds for the three symptoms.

I have uploaded a zip file to www.museumoftechnology.org.uk/ken/omxplayer1.zip
It contains the script, 2 very short test videos -  1sec.mp4 and 5sec.mp4,and some example runs.
The other two videos I have used xthresh.mp4 and suits-short.mkv can be obtained from https://github.com/KenT2/pipresents-next-examples/tree/master/pp_home/media

Tell me where to get an omxplayer.bin and I'll soak test any fixes.

**Comment by Ruffio** [comment]
@KenT2 is this still an issue? If not, please close the issue. Thanks.

**Comment by jehutting** [comment]
Can you @KenT2 reply on Ruffio's request?

**Comment by KenT2** [comment]
Sorry missed the previous request, I have converted PI Presents to use dbus rather than pexpect so will close
