### ISSUE TITLE
omxplayer script not compatible with busybox (mktemp)

### ISSUE THREAD

**Issue by agherzan** [popcornmix/omxplayer#136]
Busybox has a restriction in temp file name. From documentation:	
Create a temporary file with name based on TEMPLATE and print its name. TEMPLATE must end with XXXXXX (e.g. [/dir/]nameXXXXXX).

Hope this time it works for you... :)
https://review.gherzan.ro:8443/#/c/43/

**Comment by Ruffio** [comment]
@agherzan is this still an issue?

**Comment by agherzan** [comment]
Don't even remember due to this very late feedback. You can close it for now and will come back with info if needed.
