### ISSUE TITLE
make dist issues after commit 201c77973155861e60492e45d35467b19b69c1c4

### ISSUE THREAD

**Issue by agherzan** [popcornmix/omxplayer#138]
I am pretty confused by a change in:
commit 201c77973155861e60492e45d35467b19b69c1c4
Author: Jontom Xire <JontomXire@yahoo.co.uk>
Date:   Mon Dec 30 15:23:12 2013 +0000

If I want to install omxplayer in a defined DIST directory, "cd $(DIST); tar -czf ../$(DIST).tgz *" fails with:
cd /home/agherzan/work/personal/yocto/2014-01-02-rpi/tmp/work/armv6-vfp-poky-linux-gnueabi/omxplayer/git-r3/image; tar -czf ..//home/agherzan/work/personal/yocto/2014-01-02-rpi/tmp/work/armv6-vfp-poky-linux-gnueabi/omxplayer/git-r3/image.tgz *
| tar (child): ..//home/agherzan/work/personal/yocto/2014-01-02-rpi/tmp/work/armv6-vfp-poky-linux-gnueabi/omxplayer/git-r3/image.tgz: Cannot open: No such file or directory

So if DIST is an absolute path, how is that supposed to work?

EDIT: Understood now what was the idea of that change. But still: as long as you are archiving only things in DIST, where is the issue?

**Comment by Ruffio** [comment]
@agherzan is this still an issue?

**Comment by agherzan** [comment]
Don't even remember due to this very late feedback. You can close it for now and will come back with info if needed.
