### ISSUE TITLE
cannot get dbus command or python dbus-python to control player

### ISSUE THREAD

**Issue by jackmullen** [popcornmix/omxplayer#155]
If I understand what should happen when I attempt to access the player via a dbus application, then the following  results indicate an issue that I cannot resolve.  

If I start the player ( on raspberry pi, debian dist ) and launch dbuscontrol.sh with any commands I get the following result:  

pi@raspberrypi:~$ bash dbuscontrol.sh status
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

if I attempt to access the dbus daemon using a dbus-python application I get this message :  dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.17" is not allowed to own the service "raspberry.pi.OMXPlayer" due to security policies in the configuration file

I can see no restrictions in the dbus config files, either system or session that would prevent ownership. The default configuration files allow any number owners. 

I want to be able to determine in python, ( programmatically ) if a movie is still playing. 

I have spent some time on this problem and any insight or advice provided will be appreciated . 

thank you

**Comment by Ruffio** [comment]
@jackmullen is this issue resolved?

**Comment by jackmullen** [comment]
Yes .. Thank you 

On Jun 24, 2015, at 7:59 AM, Rasmus Christiansen <notifications@github.com> wrote:

> @jackmullen is this issue resolved?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Jack Mullen
All Rights Reserved without Prejudice


Notice & Warning: This email contains proprietary business information, trade secrets, restricted and valued information intended for the addressees eyes only.
This message (including any attachments) is covered by the Electronic Communication Privacy Act, 18 U.S.C. sec 2510-2521. This e-mail message, including any attachments, is for the sole use of the intended recipient(s) 
All interceptors, surveillance agents foreign and domestic, enforcement agencies are hereby prohibited from accessing, possessing, using, selling, purchasing, storing, retrieving, and transmitting this valuable information as a product or service for gain. Any monetary profits, benefits or accounting of this information for gain may be prosecuted as a felony offense and cause of action. Persons, whistle blowers, informants may be granted an award for information leading to the successful prosecution of agents committing acts of infringement.

[ truths ]
Neo: "What truth?" Morpheus: "That you are a slave, Neo. That you, like everyone else, was born into bondage... kept inside a prison that you cannot smell, taste, or touch – a prison for your mind." Matrix

"The consciousness of being at war, and therefore in danger, makes the handing over of all power to a small caste seem the natural unavoidable condition of survival." ~ George Orwell

“To compel a man to furnish funds for the propagation of ideas he disbelieves and abhors is sinful and tyrannical.” - Thomas Jefferson

“A mere demarcation on parchment of the constitutional limits (of government) is not a sufficient guard against those encroachments which lead to a tyrannical concentration of all the powers of government in the same hands.”, James Madison

"Malo Periculosam Libertatem Quam Quietum Servitium"

“The best way to control the opposition is to lead it ourselves.” 
― Vladimir Ilyich Lenin
