### ISSUE TITLE
setvideopos on RTSP stream

### ISSUE THREAD

**Issue by microwavesafe** [popcornmix/omxplayer#157]
When changing the video position (the new dbus features) on an RTSP stream from an IP camera, it seems to screw up the stream and has to wait for some kind of resynchronisation which can take 10 seconds or so. It is actually quicker to kill the process and start a new one with the new size.

Is there anyway to force the stream to resync? I've noticed seek also does the same thing and also increases the latency even when using --live.

If I can get this aspect working it will be absolutely perfect!

I can make the stream publicly available for short periods if you give me notice. If that's any help at all.

**Comment by Ruffio** [comment]
@microwavesafe is this still an issue?

**Comment by microwavesafe** [comment]
As far as I'm aware this is still an issue. I gave up trying to seek h264 RTSP streams.

**Comment by popcornmix** [comment]
I believe this was resolved with https://github.com/popcornmix/omxplayer/commit/66ca3030477bfd60fc25cc695b5c5e159f4395b4
setvideopos no longer close/opens the stream.
