### ISSUE TITLE
give the possibility to disable audio

### ISSUE THREAD

**Issue by drakkan** [popcornmix/omxplayer#180]
I think would be useful a command line option to disable audio playback, there are use cases when you have a network stream/local file with audio and video but you want to show only video

**Comment by Ruffio** [comment]
@popcornmix as this feature request has been implemented, it can be closed.

**Comment by mijutu** [comment]
libavformat still suffers from bug [5080](https://trac.ffmpeg.org/ticket/5080) and disabling audio with omxplayer -n -1 doesn't help as a work-around. It doesn't seem to disable audio the same way "ffmpeg -i url -an" does. With audio disabled, omxplayer still does about hundred http requests per second with problematic mp4s.

Tried with omxplayer and ffmpeg from raspbian buster.
