### ISSUE TITLE
problems with dbus setvideopos

### ISSUE THREAD

**Issue by gkreidl** [popcornmix/omxplayer#183]
I'm using that command extensively in my new omxplayer GUI, each time the GUI window is being moved or resized. This works well with all kind of files (a very small hiccup in the video) and also on http ts streams (mpg2 and HD h264).
If I serve video files on http, I'm running into different problems, depending on the file format:
avi: sound plays on, but new video area remains black and video never returns.
mp4: video and sound get lost, video seems to be stuck at pos. 0:00:00 (shown when pausing), but omxplayer does not stop.
mkv: video returns but jumps ahead by 1 - 2 minutes

**Comment by popcornmix** [comment]
Is this still an issue with latest omxplayer?

**Comment by ktws** [comment]
It's no longer an issue as the latest OMXplayer uses OMXVideo::SetVideoRect (I finally managed to get it working).

**Comment by gkreidl** [comment]
No, it's perfect now and that's why I already closed this issue.

**Comment by popcornmix** [comment]
Issue is currently open. I'll close now.
