### ISSUE TITLE
omxplayer fails compilation in arch linux.

### ISSUE THREAD

**Issue by vkefallinos** [popcornmix/omxplayer#195]
I tried yaourt -S omxplayer-git and it fails on OMXSubtitleTagSami

    Makefile:45: recipe for target 'OMXSubtitleTagSami.o' failed
    make: *** [OMXSubtitleTagSami.o] Error 4
    ==> ERROR: A failure occurred in build().
       Aborting...
    ==> ERROR: Makepkg was unable to build omxplayer-git.

The latest version of omxplayer fails to compile in arch linux..
The only working version of omxplayer is the one in aur packages that doesnt support dbus control..

**Comment by Ruffio** [comment]
@popcornmix it looks like that this issue can be closed as there have been no response for a year now...
