### ISSUE TITLE
skip by Mb rather than seconds ?

### ISSUE THREAD

**Issue by divenal** [popcornmix/omxplayer#217]
When trying out omxplayer using an http stream served from a second rpi, it seemed very sluggish to resume playing after a skip. I see from the logs on the httpd server that it's opening the stream at various byte offsets, presumably to try to figure out the point with the correct timestamp.

Maybe it's a silly idea, but I'm wondering if there's any interest in supporting skip by a byte-count, rather than a time. The point being that when I'm trying to skip adverts, I don't care if it goes exactly 30 seconds or not, I just want to keep going forwards a bit at a time until program restarts, then rewind in smaller steps to find the end of the adverts.  Seems that if I skip by a byte count, it can start playing sooner and therefore I can decide for myself whether to keep skipping, skip in bigger amounts, etc.

(I'm currently using a remote control on smartphone via a web interface, with omxplayer running as a child of the server, with keypresses going over anonymous pipe, but I'll probably be changing to use dbus for control when I find time.)

Apologies if this is the wrong place for this sort of thing.

**Comment by popcornmix** [comment]
No plans to implement.
