### ISSUE TITLE
White flicker upon end of video playback

### ISSUE THREAD

**Issue by turingmachine** [popcornmix/omxplayer#250]
When omxplayer arrives at the end of a video file, the screen turns completely white for a couple of ms. This behavior is perceived much stronger if content is played on a projector in a dark room. It's almost like a strobe.

I narrowed it down to revision 8491367c10b9106f2259bb4e325a2eea1f75a183, in which the described behaviour is not present.
It first appears in the build of revision 74f4be222be05d3ea50be9f5a70846f7c0e9df6e.
It didn't  try the two revisions between 74f4be222be05d3ea50be9f5a70846f7c0e9df6e and 8491367c10b9106f2259bb4e325a2eea1f75a183 because there are no builds on omxplayer.sconde.net.

Possibly related to revision 443b4dc07d2a4b44741063dbca3dc6be40e8a106?

**Comment by Ruffio** [comment]
@exidyboy is this still an issue?

**Comment by exidyboy** [comment]
@turingmachine created the issue. I merely confirmed it. I believe he is better positioned to say whether it has been fixed.

**Comment by HakanL** [comment]
What was the outcome of this, is there a way to fix this without re-coding the videos? I have some videos that I have purchased (h.264, atmosfx.com) and I get the white flash at the end on all of them, build d99bd86.
