### ISSUE TITLE
Gab between two videos

### ISSUE THREAD

**Issue by matheusvetor** [popcornmix/omxplayer#257]
Hi guys, i have trying to execute many videos in a loop. I have a ruby script which call a spawn process but i have a gap between 2 videos. I thought which the gap was because the omxplayer prints some informations at start/stop the video. I tried remove these messages but no success . The gap is ~2 seconds.

```
      ...
      params = it.items.map{|i| Shellwords.escape(i.file_path) }
      params.each do |p|
        command = "omxplayer -o hdmi #{p} > /dev/null"
        video_player_pid = spawn(command)
        status = Process.waitpid2(video_player_pid)
      end
```

Exist a way to mitigate the gap between videos?

**Comment by Ruffio** [comment]
@popcornmix there is no issue herefter. This can be closed.
