### ISSUE TITLE
omxplayer wrapper script issues

### ISSUE THREAD

**Issue by ktsaou** [popcornmix/omxplayer#259]
1. ${USER} variable is undefined for scripts started from rc.local.
 
 I suggest to replace:

 ```sh
OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.${USER}"
OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.${USER}.pid"
```

 with:
 ```sh
OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.${USER:-root}"
OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.${USER:-root}.pid"
```

 This way, if the `${USER}` variable is empty, the script will assume it is actually `root`.

2. ~~The files `/tmp/omxplayerdbus*` should be saved in `/run`, not `/tmp`. `/tmp` writes to disk which is not necessary for the dbus session variables.~~

 My mistake. `/run` is not writable by normal users.

3. The return code of omxplayer.bin is not returned to the caller. This means the caller has no way of knowing if omxplayer.bin was actually being able to play the file, if it has been killed or whatever else can be detected from the return value.

**Comment by Ruffio** [comment]
@ktsaou I can't figure out if this issue can be closed or it needs something?

**Comment by ktsaou** [comment]
Hi,

the issue has 3 points. Point 2 is wrong (my bad). Points 1 and 3 as unsolved:

1. If omxplayer is started from rc.local then omxplayer spawns a dbus for user '' (empty string). This has the problem that if you also have a cron job to communicate to omxplayer via cron, the cron script cannot find the rc.local omxplayer. I have given you the fix.

2. The return code of omxplayer is lost by the wrapper script, so that programs calling omxplayer (not omxplayer.bin) cannot know what happened. The offending line on your wrapper script is this:

 ```sh
LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"; true
```

 It should save the return code of OMXPLAYER_BIN to a variable. Then, you will have to exit the script with the return code saved to this variable.

Thanks

**Comment by popcornmix** [comment]
@ktsaou Is this good for you? http://paste.ubuntu.com/11768498/

**Comment by ktsaou** [comment]
it is perfect!
thanks!

**Comment by popcornmix** [comment]
Okay, pushed.

**Comment by ktsaou** [comment]
Thank you very much.
I am closing this...
