### ISSUE TITLE
pause(p)/stop(q) key not working , if omxplayer started at  boot using /etc/init.d script 

### ISSUE THREAD

**Issue by navaneetharaopy** [popcornmix/omxplayer#278]
Currently i am using omxplayer in my pi to show videos while booting, For that i have included a file in /etc/init.d/ and it works fine. But after booting to desktop mode when play videos(manualy)  using omxplayer pause/play/stop key bindings are not working(none of the keyboards key can pause/stop the video).

**Comment by StevenHickson** [comment]
This is known behavior and is appropriate. When you start it from the terminal, you are still in that shell and it is listening for keybindings. Here it is running and not listening for those. You can control the play/pause functionality with dbus messages.

**Comment by navaneetharaopy** [comment]
This issue can be resolved by running omxplayer as super user.
 For example instead of omxplayer -o hdmi  filename.mp4
You can run the omxplayer as super user sudo omxplayer -o hdmi  filename.mp4 
This will make omxplayer terminal to listen to stdin

**Comment by Ruffio** [comment]
@fcarlier the 'issue' seems to be closed so this can be closed officially.
