### ISSUE TITLE
Display media meta data

### ISSUE THREAD

**Issue by PanderMusubi** [popcornmix/omxplayer#287]
Please, display ID3 information from MP3 and streams and other meta data from media files while playing them. An option could be added to show this constantly while playing or pause. Example implementation can be found here https://github.com/rejhgadellaa/icerrr/blob/master/webapp/php/tests/test-readid3.php

Additionally the use could override the format of %ARTIST - %ALBUMTITLE - %TRACKNUMBER %TRACKTITLE. Please use a the same well thought through format of https://raw.githubusercontent.com/stsquad/easytag/master/doc/EasyTAG_Documentation.html

**Comment by Ruffio** [comment]
@popcornmix if this feature request is not going to be implemented, then please close this.
