### ISSUE TITLE
does offscreen video use memory?

### ISSUE THREAD

**Issue by Billybangleballs** [popcornmix/omxplayer#288]
So I have this movie, real letterbox aspect ratio. Left to its own devices, it plays at 1920x800.
Now thinks me, if I hang the edges over the edge of the screen a bit, I can get to the point where it is 1080 high and looks better on the TV.
So I did a bit of calculating and decided how much needed to hang over the edge to fill the height of the screen properly and came up with :-

omxplayer --win "-336 0 2256 1080" movie.mkv

Which did exactly what I was wanting. Except that 5 minutes later the pi crashed. I restarted it, and 5 minutes into the movie it just locked up solid again.
I'm running with gpu_mem=256, the movie plays just fine if I just let it do its own thing, none of the logs on the logging machine showed anything untoward, (other than "Transfer to device 6 endpoint 0x1 frame 498 failed - FIQ reported NYET. Data may have been lost."), of which I get very many.
Does anyone have any ideas as to what is happening? I suspect I'm running out of memory but can't confirm it. I'm up-to-date with the OS (Raspbian) and my kernel is Linux raspberrypi 3.12.32+ #721 PREEMPT Fri Nov 7 16:50:31 GMT 2014 armv6l GNU/Linux

**Comment by popcornmix** [comment]
Closing. Reopen if you have a repeatable test case.
