### ISSUE TITLE
Cant make external subtitles to work with mkv files

### ISSUE THREAD

**Issue by Olvikolvi** [popcornmix/omxplayer#289]
player not loading external subtitle (yes sama name and str format) when playin mkv video format. When adding --subtitles . it gives subtitle count: 1, but does not display it anyways.

**Comment by pickfire** [comment]
I played it without external subtitle on .mkv but it doesn't play the subtitle and only shows subtitle count: 1. I am using version:

```
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Thu, 02 Apr 2015 00:49:35 +0000
        Version   : 74aac37 [master]
        Repository: https://github.com/popcornmix/omxplayer.git
```

**Comment by jehutting** [comment]
I assume that you have the subtitle switched on (with the 's'-key):
```Subtitle count: 25, state:  on, index: 1, delay: 0```

OMXPlayer supports __only__ subtitles (ffmpeg codec id) AV_CODEC_ID_SUBRIP and AV_CODEC_ID_SSA.
```mediainfo``` shows these codecs as S_TEXT/UTF8 and _probably_ S_TEXT/SSA.

**Comment by pickfire** [comment]
I tried `omxplayer video.mkv` and switched on subtitle with *'m-key'*:
```
Video codec omx-h264 width 1920 height 1080 profile 100 fps 23.809525
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 1, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1920x1080@23.81 interlace:0 deinterlace:0 anaglyph:0 par:1.00 layer:0 alpha:255
Subtitle count: 1, state:  on, index: 1, delay: 0
have a nice day ;)
```
`mediainfo` shows:
```
Text
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Default                                  : Yes
Forced                                   : Yes
```

**Comment by jehutting** [comment]
S_TEXT/ASS will be identified as ffmpeg codec id AV_CODEC_ID_ASS.

**Comment by pickfire** [comment]
So, what do you mean? So it should be working? It works on kodi.

**Comment by jehutting** [comment]
S_TEST/ASS is __NOT__ working with OMXPlayer as the codec AV_CODEC_ID_ASS is NOT supported.

It is not clear _to me_ if today's Kodi (XBMC) uses libass or HarfBuzz to support ASS subtitles.
Have a look at #238.

**Comment by pickfire** [comment]
Does omxplayer support 3D subtitle just like kodi?

**Comment by popcornmix** [comment]
Latest omxplayer will replicate subtitles when TV is in 3D mode, so they appear correctly.
No support for subtitle depth though.

**Comment by pickfire** [comment]
What library does omxplayer use to display subtitle and what is the difference between kodi's subtitle library?

**Comment by popcornmix** [comment]
Kodi supports many many subtitle formats, both textual and graphical.
It uses libass (and quite possibly other external libraries).

omxplayer's support is much simpler, supporting textual subs only. No external libraries, but makes use of OpenVG that is supported on GPU for rendering text.

**Comment by pickfire** [comment]
So that is why some subs can't be rendered. Thanks.

**Comment by Ruffio** [comment]
@popcornmix if this feature request is not going to be implemented, then please close this.

**Comment by jehutting** [comment]
@pickfire If I'm right, you created this issue because you had problems with external subtitles. But at the end it appears more having a problem with ASS subtitling. 
The (latest) commit 17b81a8 supports it now. Could you verify this (ASS support) too and/or close this issue?

**Comment by pickfire** [comment]
@jehutting Yup, I just figured out it is there some time ago when I try to watch one piece in omxplayer.

Thanks a lot, this issue can be closed now.
