### ISSUE TITLE
omxplayer --key-config <file> not working

### ISSUE THREAD

**Issue by omes22** [popcornmix/omxplayer#290]
Hello, 
I found out that I can make a custom omxplayer key binding file via the omxplayer command 

omxplayer --key-config /path/to/file

but it just gives me help list of omxplayer. The syntax is correct, example: 

sudo omxplayer --key-config /home/pi/doc/conf/remote.txt

version:
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Sat, 22 Mar 2014 20:58:15 +0000
        Version   : 39e6342 [master]
        Repository: https://github.com/popcornmix/omxplayer.git

**Comment by popcornmix** [comment]
@omes22 does @jehutting's reply solve your issue?

**Comment by Ruffio** [comment]
@omes22 can this be closed?

**Comment by romuald-maillet** [comment]
Hello Ruffio
Yes for me
