### ISSUE TITLE
Playback fails after first time.

### ISSUE THREAD

**Issue by JontomXire** [popcornmix/omxplayer#300]
I have just downloaded some guitar lesson videos for my daughter in full HD. The video downloader is downloading from YouTube and apparently needs to download the video and audio separately which it then muxes together to make an MP4 file.

When she plays the first video it is fine, but when she then tries to play a second video there is just a black screen and no audio. Reboot solves the problem (of course) but is very inconvenient. Other mp4 files (of much lower quality) downloaded from other sources play fine. I'm wondering if there is some resource leak although I've played longer files of lower quality that are actually bigger with no problems.

I've tried cutting a sample file, but I can't get it much under 50 seconds and 13MB file size.

**Comment by popcornmix** [comment]
13MB is fine (even 100-200MB is okay for a sample).
Just a quick check - what gpu_mem do you have defined? Does increasing it help?

**Comment by JontomXire** [comment]
The box was failing to boot when I got back after Christmas holidays so I re-imaged it. Settings are all default as far as memory split. What split do you recommend, given that the box is only used for playing videos?


--------------------------------------------
On Sun, 18/1/15, popcornmix <notifications@github.com> wrote:

 Subject: Re: [omxplayer] Playback fails after first time. (#300)
 To: "popcornmix/omxplayer" <omxplayer@noreply.github.com>
 Cc: "JontomXire" <JontomXire@yahoo.co.uk>
 Date: Sunday, 18 January, 2015, 12:26
 
 13MB is fine (even 100-200MB is
 okay for a sample).
 
 Just a quick check - what gpu_mem do you have defined? Does
 increasing it help?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by popcornmix** [comment]
I'd recommend gpu_mem=128.
64 should be okay for most videos, but may struggle with 1080p with many reference frames or subtitles.

**Comment by JontomXire** [comment]
That fixed it, thanks.

I wonder how it was able to play any of the videos at all.


--------------------------------------------
On Tue, 20/1/15, popcornmix <notifications@github.com> wrote:

 Subject: Re: [omxplayer] Playback fails after first time. (#300)
 To: "popcornmix/omxplayer" <omxplayer@noreply.github.com>
 Cc: "JontomXire" <JontomXire@yahoo.co.uk>
 Date: Tuesday, 20 January, 2015, 17:45
 
 I'd recommend gpu_mem=128.
 
 64 should be okay for most videos, but may struggle with
 1080p with many reference frames or subtitles.
 
 —
 Reply to this email directly or view
 it on GitHub.
