### ISSUE TITLE
Decoder timeout

### ISSUE THREAD

**Issue by karimdavoodi** [popcornmix/omxplayer#301]
(excuse me for weak english writing...)
I use omxplayer in this case:
         dvbt-->dvblast----------(udp stream)---->(omxplayer --live udp://@:1234)
in weak dvb signal, omxplayer have two problem:
1- freez screen and failed in file OMXVideo.cpp ( Decode() function )
    It can't get buffer in line: 
    OMX_BUFFERHEADERTYPE *omx_buffer = m_omx_decoder.GetInputBuffer(500);
    after this error I must reboot the system.
2- freez screen and wait in OMXPlayerVideo::Decode(OMXPacket *pkt) in loop:
  while((int) m_decoder->GetFreeSpace() < pkt->size)
  I try to solve this problem with "break loop" or "flush" or "reset" the decoder, but can't! 
  after this error I must terminate the omxplayer.
(gpu_mem=256 and system is updated to last firmware and omxplayer code)

**Comment by popcornmix** [comment]
Can you capture a file that shows the problem?

**Comment by karimdavoodi** [comment]
Hello popcornmix.
The link of log file: https://drive.google.com/file/d/0B2G1S2_AEJLAZmltbHYtNUNqTGM/view?usp=sharing
(omxplayer freeze and hanged. I kill omxplayer with Ctrl+C)

**Comment by popcornmix** [comment]
Nothing much in log.
Ideally I'd like a video file that hangs.
i.e. can you dump the udp stream to a file and then check if file hangs the same way as the live stream. Then I could investigate.

**Comment by karimdavoodi** [comment]
I ignore decoder hanging with this code:
--- omxplayer-orig/OMXPlayerVideo.cpp	2015-01-27 16:53:08.000000000 +0330
+++ omxplayer/OMXPlayerVideo.cpp	2015-01-26 11:55:08.920621946 +0330
@@ -195,9 +195,16 @@
 
   if(pts != DVD_NOPTS_VALUE)
     m_iCurrentPts = pts;
-
+  //KDKD
+  int i=0;
   while((int) m_decoder->GetFreeSpace() < pkt->size)
   {
+    if((i++)>300){
+	printf("Video decoder timeout\n");
+	CloseDecoder();
+	OpenDecoder();
+	return true;
+    }
     OMXClock::OMXSleep(10);
     if(m_flush_requested) return true;
   }

**Comment by karimdavoodi** [comment]
I ignore decoder hanging with this code:
```C
--- omxplayer-orig/OMXPlayerVideo.cpp 2015-01-27 16:53:08.000000000 +0330
+++ omxplayer/OMXPlayerVideo.cpp 2015-01-26 11:55:08.920621946 +0330
@@ -195,9 +195,16 @@

if(pts != DVD_NOPTS_VALUE)
m_iCurrentPts = pts;

    //KDKD
    int i=0; while((int) m_decoder->GetFreeSpace() < pkt->size) {
    if((i++)>300){
    printf("Video decoder timeout\n");
    CloseDecoder();
    OpenDecoder();
    return true;
    } OMXClock::OMXSleep(10); if(m_flush_requested) return true; }
```

**Comment by romuald-maillet** [comment]
I have the same install or almost
You schema is not quite correct
I think it looks rather

dvbt-->dvblast----------(udp stream)---->FFMpeg ----> (omxplayer --live udp://@:1234)

Looking stored the stream output / input ffmpeg / omxplayer in a FIFO for read by omxplayer 
Otherwise I have no problem of decoding but rather of slow startup / change file.

;-)
