### ISSUE TITLE
Characters such as tilde, single and double quotes not displayed in subtitles

### ISSUE THREAD

**Issue by vinv** [popcornmix/omxplayer#303]
I observed an issue with certain characters such as tilde, single and double quotes not displaying in subtitles. I tried multiple fonts and different versions of omxplayer. The issue is seen irrespective.

I added log lines in SubtitleRenderer.cpp to figure out what is going wrong. I discovered that when we compute glyph_origin in load_glyph_internal, in the line -

`glyph_origin[1] = static_cast<VGfloat>(padding + bitmap.rows - bit_glyph->top - 1)`

bitmap.rows is unsigned and for these particular characters `padding + bitmap.rows` is smaller than `bit_glyph->top`. Given the one unsigned in this math, the negative result becomes a very high unsigned value, causing a bad origin coordinate for these glyphs.

I was able to fix the issue by changing the line to -

`glyph_origin[1] = static_cast<VGfloat>(padding + static_cast<int>(bitmap.rows) - bit_glyph->top - 1)`

Not sure if others see the issue, but it reproduces reliably for me and the code and fix seem logical.

/vv
`

**Comment by popcornmix** [comment]
What you have said makes sense. See https://github.com/popcornmix/omxplayer/commit/18f051d64d9c837edbf718bc4935204583cfa030
