### ISSUE TITLE
Next/Previous Video

### ISSUE THREAD

**Issue by OMID-313** [popcornmix/omxplayer#308]
Hi all,

I'm using dbuscontrol.sh integrated with LIRC to control the raspberry Pi B+ via an IR remote controller.
I have several video files in a specific folder, and I want to play them in loop. I use some code like this link (http://stackoverflow.com/questions/16470795/bash-script-to-loop-through-all-videos-in-a-folder-on-raspbian-wheezy), so the omxplayer plays them in loop perfectly.

Although the loop works flawlessly, I want to have the control to jump to the next/previous/specific video when I want. There are some options like Next/Previous Audio, Chapter, Subtitle, etc. but it's surprising that there is no command/shortcut for next/previous video. Or maybe I can't find it.

My issues:
1. Is this way of playing omxplayer in loop optimum? I mean, are there any other better alternatives?
2. How can I tell to omxplayer to jump to the next/previous video?
3. I want to make use of the remote controller's numeric buttons (ch0 ~ ch9). So how can I tell omxplayer to play e.g. video_5 when I press Button_5 on my remote controller? Is there anyway that omxplayer can assign IDs to the videos in a specific folder?

Thank you very much for your time and support :)

**Comment by subogero** [comment]
Try omxd. It's a daemon that plays your playlist via omxplayer. It has various commands to add/remove files to/from the playlist, and jump around in it, like next file, next dir, or direct access:

    omxd A <folder>  # Append all files in folder to playlist (recursively for subfolders)
    omxd p  # play/pause
    omxd n  # Play next file
    omxd g 12  # Go to 13th file in playlist (it counts from zero)
    man omxd  # See comprehensive list of all commands

It has a web UI as well called remotepi. Which allows to use any smartphone or PC on your LAN to be a remote control.
http://subogero.github.io/remotepi/

It is essential to install omxplayer also from my package repo mentioned on the link above. If you install remotepi from there, it will automatically install omxd and omxplayer too. Just make sure to remove the standard Raspbian omxplayer beforehand.

**Comment by OMID-313** [comment]
Thanks @subogero for your reply.
Actually, omxd seems really nice, and probably it will solve my problem.

But I have 2 questions regarding this omxd:

1. I'm a beginner, and I just don't know how to install it on my raspberry which has NOOBS/Raspbian installed on it. Can I install it with sudo apt-get install omxd ?
2. Currently I don't need other stuff like remotepi, rpi.fm, etc. So is it enough to just install omxd? In this case, do I still have to uninstall my omxplayer first?
3. In order to control omxplayer from LIRC, I have to use its dbuscontrol.sh. For example, now I use commands like "/dbuscontrol.sh pause" to pause the video from command (not using keyboard). Is this omxd capable of running such commands to replace its keyboard shortcuts?

Thank you very much for your great help.

**Comment by subogero** [comment]
The right steps would be:
* `apt-get remove omxplayer`
* Adding `deb http://linux.subogero.com/deb/ /` to your Raspbian package repos
* `apt-get install omxd`

The last step will intstall the newer omxplayer as well.

As for LIRC, I guess you'll have to replace `dbuscontrol.sh pause` with `omxd p`.

**Comment by OMID-313** [comment]
Thanks @subogero for your quick reply.

One more question:
Would you please describe what the second step is? And how should I do that? What exactly should I enter in the command terminal?

Sorry for my stupid questions!

**Comment by subogero** [comment]
As root, create the file `/etc/apt/sources.list.d/subogero.list` with the following contents:

`deb http://linux.subogero.com/deb/ /`

**Comment by OMID-313** [comment]
Thanks again @subogero for your great help.

I will try them all ASAP, and will report the results here.

Thanks for your time and patience.

**Comment by subogero** [comment]
Sorry, don't forget `apt-get update` before installing omxd.

**Comment by OMID-313** [comment]
Thanks for your note.

Is it possible not to run this update?

Because I have modified some files like cmdline.txt , rc.local , rcS , etc. and I'm afraid the changes will be reset after update.

**Comment by subogero** [comment]
I think this is the wrong forum to discuss `apt-get`. Please contact me per email: szg@subogero.com

**Comment by OMID-313** [comment]
Thanks @subogero for your helpful replies.

I have posted my issues regarding the omxd on its Github page here (https://github.com/subogero/omxd/issues/26), so we'd better continue our duscussions there.

It seems that omxd is a very nice package, and it would be very nice if @popcornmix adds omxd to omxplayer.
