### ISSUE TITLE
setvideopos doesn't work any more

### ISSUE THREAD

**Issue by gkreidl** [popcornmix/omxplayer#313]
In latest release from http://omxplayer.sconde.net/ the dbus command setvideopos doesn't work any more. The video gets lost.
I'm using that a lot in omxplayerGUI, when a window is moved or resized or the display format is changed.
It works with the default Raspbian version.

**Comment by ktws** [comment]
@gkreidl I submitted a bugfix for this 17 days ago, #307, but unfortunately it's not yet been accepted.

Frustratingly, omxplayer has been upgraded in the repositories today without this bug fix. This means that any software using 'setvideopos' and/or 'unhidevideo' d-bus commands will no longer work with the default Raspbian version.

@popcornmix Any chance of getting pull request #307 accepted and the repository version upgraded accordingly?

**Comment by subogero** [comment]
Hi. I don't know about the fix, but the latest omxplayer builds from skgsegio's build bot are available in my Deb repo. So once once the fix is accepted, you can use that. More info at the bottom of the page at http://subogero.github.io/remotepi

**Comment by gkreidl** [comment]
I strongly support ktws's suggestion to add the bug fix and get it into the repository as fast as possible.

**Comment by popcornmix** [comment]
#307 is now merged.

**Comment by gkreidl** [comment]
Thanks! :-)
How long might it take to get the new version into the repository?

**Comment by 42loop** [comment]
hm, this still does not work. with #307 'setvideopos' doesnt stop the video anymore, but is of no effect (besides a hiccup in the video).
'unhidevideo' does not work
[still trying to figure out how its supposed to work, maybe we just need a simple setvideorect...]

**Comment by gkreidl** [comment]
I can assure you that both commands do work with the latest release.  I'm using them all the time.

**Comment by ktws** [comment]
#307 works but you need to download and install omxplayer_0.3.6~git20150217~5337be8_armhf.deb from http://omxplayer.sconde.net/

```
sudo dpkg -i omxplayer_0.3.6~git20150217~5337be8_armhf.deb
```

I didn't really document the d-bus commands other than in my initial commit, https://github.com/popcornmix/omxplayer/pull/149, and examples within dbuscontrol.sh. Hopefully the following descriptions will help you understand what they do.

- hidevideo hides the video while retaining sound
- unhidevideo video restores the video to its original position
- setvideopos lets you change the video on-screen position/size

**Comment by 42loop** [comment]
ok, the build from sconde.net does it, however the current git source which i'm compiling myself does not work. strange enough, 'hidevideo' and all other dbus commands work fine

**Comment by popcornmix** [comment]
Can you try building from 14237dd3eb3790feb56223ad1a66018715c78b54
which should match the sconde build. Assuming that works, you can identify the specific build that broke it (there's only been 6 commits since then).

**Comment by 42loop** [comment]
the sconde build is of version 5337be8 - that one works
until version c5ab808 it also works
from version 14237dd it does not work anymore, so it is #322 that breaks it. if i undo the changes from #322 in omxplayer.cpp, e.g. replacing the reset call by the old calls to close, open, it works. something in the reset function must be odd...

**Comment by popcornmix** [comment]
ping @tdicola

**Comment by tdicola** [comment]
Oh weird, let me take a look and repro tonight.  Is it only when changing position through dbus or also from the keyboard that it fails (I suspect it would fail with keyboard too, but just want to check)?

**Comment by ktws** [comment]
I'll have a proper look later tonight but it looks like the "m_player_video" flag is the problem. For example:

KeyConfig::ACTION_HIDE_VIDEO ([1416-1424](https://github.com/popcornmix/omxplayer/blob/14237dd3eb3790feb56223ad1a66018715c78b54/omxplayer.cpp#L1416-1424)) sets "m_has_video" to false and closes "m_player_video" in order to hide the video layer.

I chose to code it this way as there's no "stutter" interruption in sound when removing the video layer. It makes for a better user experience in the media player wrapper i'm writing.

#322 introduces line [1497](https://github.com/popcornmix/omxplayer/blob/14237dd3eb3790feb56223ad1a66018715c78b54/omxplayer.cpp#L1497) which doesn't re-open "m_player_video" in order to optimize video restart.

**Comment by ktws** [comment]
@tdicola using the old code when "m_new_win_pos" is true corrects the problem:

```
      if (!m_new_win_pos)
      {
        if (m_has_video && !m_player_video.Reset())
          goto do_exit;
      }
      else
      {
        if (m_has_video && !m_player_video.Open(m_hints_video, m_av_clock, DestRect, m_Deinterlace ? VS_DEINTERLACEMODE_FORCE:m_NoDeinterlace ? VS_DEINTERLACEMODE_OFF:VS_DEINTERLACEMODE_AUTO,
                                           m_anaglyph, m_hdmi_clock_sync, m_thread_player, m_display_aspect, m_display, m_layer, video_queue_size, video_fifo_size))
          goto do_exit;
      }

```

**Comment by tdicola** [comment]
Ah, yeah that looks like a good way to fix it so the player is opened again after hiding and unhiding the video.  Just about have my fork setup and compiling again so I'll give it a quick test and send a pull with the change soon.

**Comment by tdicola** [comment]
Yeah that fix seems to work well, thanks!  I can use the hide, unhide, and setvideopos commands from dbus and they seem to work as expected now.  Sent a pull with the fix here: https://github.com/popcornmix/omxplayer/pull/326
