### ISSUE TITLE
16 videos at a time

### ISSUE THREAD

**Issue by ZdeSim** [popcornmix/omxplayer#315]
I need to buy the program which plays up to 16 windows with video at a time.
Features:
- For Raspberry pi 2 (quad-core)
- The specified 1-16 windows and sources, separate process
- Video resolution 480x270 min
- Autoloop (auto loop video files, auto re-connection ip stream)
- Live, ip cameras
- Source ip stream or file
- No sound
- With the unavailability show ip stream entered the picture, the same for all
- Without additional functions (pause, seek, subtitle etc.)

eg: plaeyr16 --live - loop "x1 y1 x2 y2" rtsp:\\cam_ip_adr  "x1 y1 x2 y2" /home/pi/media.avi etc.

Can anyone give me this program, what is the price and delivery date?

Thank Zdenek Simunek

**Comment by towolf** [comment]
You are funny, man. This is not a shop.

**Comment by Ruffio** [comment]
@popcornmix, this issue should be closed.
