### ISSUE TITLE
--win option not working.

### ISSUE THREAD

**Issue by teucrus** [popcornmix/omxplayer#318]
Hello,
I have raspberry pi B+ and I am using raspbian. I have updated with rpi-update and apt-get dist-upgrade. I have omxplayer_0.3.6~git20150217~5337be8_armhf.deb from http://omxplayer.sconde.net/
I use "omxplayer --win '200 200 200 200' video.mp4" but the video always runs fullscreen.
At some point it worked but after rebooting the device it stopped working again.
Any ideas what may be the issue?
Thanks.

**Comment by jehutting** [comment]
The syntax for the ```--win``` option is ```--win 'x1 y1 x2 y2'``` or ```--win x1,y1,x2,y2```, where
(x1,y1) is the upper left corner and (x2,y2) the bottom right corner of the window. Only when ```(x2 > x1) AND (y2 > y1)``` OMXPlayer shows a windowed screen. In all other cases OMXPlayer uses full screen.

**Comment by teucrus** [comment]
You were right. Thank you very much. I was stuck and didn't think of that.
