### ISSUE TITLE
alpha transparency

### ISSUE THREAD

**Issue by 42loop** [popcornmix/omxplayer#319]
hi, 
I have successfully modified the code to accept an alpha transparency value when starting up. 
however, when trying to modify alpha while the player is already running along the lines:

  OMX_ERRORTYPE omx_err;
  OMX_CONFIG_DISPLAYREGIONTYPE configDisplay;
  OMX_INIT_STRUCTURE(configDisplay);
  configDisplay.set = OMX_DISPLAY_SET_ALPHA;
  configDisplay.alpha = myalpha;
  omx_err = m_omx_render.SetConfig(OMX_IndexConfigDisplayRegion, &configDisplay);

I'll get an error in the log saying

  Open error OMX_IndexConfigDisplayRegion omx_err(0x80001001)

which is an 'unknown' error. the same thing works fine using dispmanx, so I can't believe its not working in OMX. any hints ?

grtx

**Comment by popcornmix** [comment]
Are you setting the port?
```
  configDisplay.nPortIndex = m_omx_render.GetInputPort();
```

**Comment by 42loop** [comment]
yes, it makes no difference

**Comment by popcornmix** [comment]
Can you post (e.g. to pastebin) the diff from current omxplayer code?

**Comment by 42loop** [comment]
its here: 
http://pastebin.com/FTdXu341

**Comment by 42loop** [comment]
changes in 'blank_background' were from a previous wrong attempt

**Comment by popcornmix** [comment]
I applied your patch. Ran 
```omxplayer -g --alpha 32 h264_1080p_hp_4.1_10mbps_dts_unstyled_subs_monsters.mkv```
and video was dimmed, with console visible.

How exactly were you trying to change it dynamically?

**Comment by 42loop** [comment]
there is a test call to setalpha() right after the open:
that generates the error and is of no effect.

dreaming of a video mixer, made some GUI in OpenVG, implemented alpha in the raspicam code, currently running 4 layers ;-)
grtx

  if(m_has_video && !m_player_video.Open(m_hints_video, m_av_clock, DestRect, m_Deinterlace ? VS_DEINTERLACEMODE_FORCE:m_NoDeinterlace ? VS_DEINTERLACEMODE_OFF:VS_DEINTERLACEMODE_AUTO,
                                         m_anaglyph, m_hdmi_clock_sync, m_thread_player, m_display_aspect, m_alpha, m_display, m_layer, video_queue_size, video_fifo_size))
    goto do_exit;


m_player_video.SetAlpha(128);

**Comment by popcornmix** [comment]
I suspect it is because m_omx_render is not created by COMXVideo::Open, but by COMXVideo::PortSettingsChanged which occurs after first video frame is decoded.

If m_omx_render has not been created, then just store the alpha away, and set it in PortSettingsChanged. If it has been created you can directly set it.

**Comment by 42loop** [comment]
ok, that was it, the m_omx_render was not created.
for mixing action, portsettingschanged is too 'expensive', i now use my setalpha code later and that works fine. now i can adjust the transparency also by a dbus call.
thanks for your pointers

**Comment by popcornmix** [comment]
Okay to close?

**Comment by Depado** [comment]
Hi,
Is there any way I could see that diff or has that been merged ? I'm also interested in transparency handling and your pastebin is not up anymore.

**Comment by 42loop** [comment]
hi there,

this has been merged from pull request 331,
see here:

https://github.com/popcornmix/omxplayer/commit/fe619610dc0dbcca9616c1a4da4d0f625186ac3a

**Comment by Depado** [comment]
Yeah I saw that just after I commented. Thanks a lot :)

**Comment by Depado** [comment]
Quick question though, omxplayer works in a fire-and-forget way ? So there is no way I can get the current transparency level from Dbus or something similar ?

**Comment by 42loop** [comment]
i haven't used it myself, but the status request at the top of
dbuscontrol.sh looks like you can request all values

**Comment by ChrisLaurie** [comment]
For my community theatre's next project I would love to have keyboard control for this fade out. Say each time I press a key, the alpha is adjusted (say by 5% of the range) so that I can fade the video at a specific rate and then press the stop key once the video is faded out.

Is there any chance of this being controlled directly from the keyboard and not via dbus?
