### ISSUE TITLE
Codecinfo: acpu and vcpu are forever at 0% as of OpenELEC 5.0.4

### ISSUE THREAD

**Issue by bconway** [popcornmix/omxplayer#320]
I recently upgraded from 4.2.1 to 5.0.4 and noticed that acpu and vcpu % numbers never budge from 0. In the past, acpu was a helpful hint as to whether serious audio decoding was being done or whether it was pass-through.

Obviously this isn't critical information, I just liked seeing it. Thanks.

**Comment by bconway** [comment]
To clarify, this is on Raspberry Pi (1) Model B 512.

**Comment by popcornmix** [comment]
This isn't the right place to report this. This repo is for the command line omxplayer tool which isn't used by kodi or openelec. Try posting in the openelec forum.
