### ISSUE TITLE
showing shoutcast information

### ISSUE THREAD

**Issue by Aiexis** [popcornmix/omxplayer#324]
Hi all,
When I listen to a shoutcast stream, I would like to know what music is played.
If I use: $ omxplayer --info http://...
I can get the StreamTitle but nothing is played (as expected).

Without --info options, the stream is played, but the binding key "z" (show info) doesn't seem to work.

I can't find any dbus option to get information about what is played.
I wrote a small php script to get the title directly from the shoutcast server, but it would be cleaner if it comes from omxplayer directly (as there is about 40 seconds delay between server and client).

Any idea ?
Thank you in advance.

**Comment by subogero** [comment]
This is what the `-I` option is for.

**Comment by Aiexis** [comment]
Hi subogero,
I tried this option too, but the streamtitle is not updated in real time (just shown at the first start).

**Comment by popcornmix** [comment]
In general ffmpeg handles all of the stream access. If ffmpeg doesn't report the "live" stream title then this is not going to be supported.

**Comment by Aiexis** [comment]
Ok thank you popcornmix, I will continue to use my php script.
