### ISSUE TITLE
Set volume with dbus

### ISSUE THREAD

**Issue by Aiexis** [popcornmix/omxplayer#327]
Hello
I have successfully used dbus to increase and decrease the sound volume, using dbuscontrol.sh.
Is there a way to SET the volume to any value (like --vol option) with dbus, while playing ?
I see that it is documented ("When called with an argument it will set the volume and return the current volume."), but it's not available in the dbus control script.

Thank you in advance.

**Comment by popcornmix** [comment]
I've added a new dbuscontrolL https://github.com/popcornmix/omxplayer/commit/4e5280953640d5aa56bc0dbfde72e052ddafac80

Try:
```
./dbuscontrol.sh volume 0.5
```

**Comment by Aiexis** [comment]
Works fine, thanks ! ;)
