### ISSUE TITLE
--win option does't work any more

### ISSUE THREAD

**Issue by gkreidl** [popcornmix/omxplayer#334]
I just downloaded latest version (omxplayer_0.3.6~git20150318~201828d_armhf.deb) from http://omxplayer.sconde.net. While the dbus commands setvideopos, hide and unhide video work really great now (and even with live TV streams!), the initial --win option doesn't seem to have any effect at all (always full screen). I tried both 'x1 y1 x2 y2' and x1,y1,x2,y2 - no difference.

**Comment by popcornmix** [comment]
Should be fixed with: https://github.com/popcornmix/omxplayer/commit/f2098e69faf2994d3dcfee8025ee57690ddbe48a

**Comment by gkreidl** [comment]
Yes, fixed.
Sergio was so nice to bring it online very fast.
