### ISSUE TITLE
where can I modify --threshold limit in the code ?

### ISSUE THREAD

**Issue by todostreaming** [popcornmix/omxplayer#336]
I would like to increase the limit of --threshold that actually is about 6.1 seconds (live or not). However I could not find the part in the code that determines this value, or is related to it. I would like increase it double its actual size (about 12 seconds). I've seent that neither fifos nor queues are related to this setting.

Thanks in advance and regards.
/ts

**Comment by popcornmix** [comment]
You can modify threshold on the command line.
However it makes no sense to set threshold to a larger value that the size of the fifos+queues.
You will need to increase fifos and queues to be able to contain more than 6 seconds of data.

**Comment by todostreaming** [comment]
I've tested with fifos and queues at 40 MBs, however it is not possible to go over threshold = 6.1 sec
No matter if --live is used or not, 6.1 seconds is the limit. 
With a content of 2 Mbps, there should be enough room for more than 6.1 seconds of audio+video.

/ts
