### ISSUE TITLE
Play audio on external audio device

### ISSUE THREAD

**Issue by todostreaming** [popcornmix/omxplayer#339]
Is there any way to play the audio on an external device (alsa, pulse) ?

Thanks
/ts

**Comment by popcornmix** [comment]
No. omxplayer is a GPU side video player, and drives audio (hdmi/analogue) from the GPU.
The GPU has no knowledge of alsa/pulse devices.

There are other (accelerated) players than can handle ALSA, like Kodi or VLC.
