### ISSUE TITLE
prepare-native-raspbian.sh missing sanity checks

### ISSUE THREAD

**Issue by msmuenchen** [popcornmix/omxplayer#351]
prepare-native-raspbian.sh uses sudo and pkg-config without checking for their existence.

It could parse /boot/config.txt and check for the value of gpu_mem instead of running raspi-config.

Also, the Makefile does a blank cp -r; I personally believe that the content of install and uninstall should be the same.

I'll submit a patch as soon as I have time for it.

**Comment by popcornmix** [comment]
A patch would be welcome.
``vcgencmd get_mem gpu`` would be better than parsing config.txt.

**Comment by msmuenchen** [comment]
Furthermore, it should check against dpkg if the raspberrypi-firmware package and friends are installed and only install/invoke rpi-update if not; while this prevents using the brand-freshest firmware, it also does not mess around with the user's packaging system.

**Comment by msmuenchen** [comment]
Seems to be closed since #355 got merged
