### ISSUE TITLE
Live strem start glitches and lose audio with stream above 4Mb/s

### ISSUE THREAD

**Issue by radojko** [popcornmix/omxplayer#354]
Live strem start glitches and lose audio with stream above 4Mb/s

Video is in the format h264 1280x720 60fps, problem occurred with both rtsp and rtmp live streams.
This problem is very expressed in fast scenes like sports and occurred  about 1 minute after starting.
Output parameter V:  is lower and lower after time and when reach value 0 video start glitching.

Output and omxplayer.log are on addresses: http://pasted.co/e9565a15 and http://pasted.co/17e044b5

Command for start is omxplayer -s -g --live rtmp://192.168.180.231:5502/live

Rpi is version 2 with latest Raspbian 2015-05-05
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux
Omxplayer 337004e [master]

**Comment by radojko** [comment]
It seems this is problem with encoder audio/video sync. This issue can be closed.

**Comment by NoAnyLove** [comment]
Has the same problem with OSMC 2015.6-1 on RPi and RPi2. It happended when I play video from Youku (a video website similar to Youtube). Solved this by disable omxplayer harware acceleration. 

Found some discussion here http://forum.kodi.tv/showthread.php?tid=220781. It seems that omxplayer doesn't handle corrupt timestamp correctly. Wish to fix this problem.

**Comment by popcornmix** [comment]
This repo is for command line omxplayer, which is significantly different from omxplayer in Kodi.
Best to report issue in osmc forum.
