### ISSUE TITLE
How to install omxplayer on minimal distros?

### ISSUE THREAD

**Issue by OMID-313** [popcornmix/omxplayer#358]
Hi,

Currently I'm using `omxplayer` on `Raspbian` to automatically play a folder of videos in loop after boot. It works great. The only problem is that it takes almost 90 seconds to boot and start to play video files.
I switched to `Xbian` ; it was better. But still it would take almost 50 seconds to boot and play video files.

So I decided to find very minimal distros with fast boot process.
I searched a lot, and found Minibian (http://sourceforge.net/projects/minibian/) and Moebius (http://moebiuslinux.sourceforge.net/), which both are probably the minimized versions of `Raspbian`.
These distros claim to have very fast boot processes (20 and 10 seconds), which make them ideal for minimal embedded applications. This is great.

However, it seems that people have had problems installing `omxplayer` on these distros.
Would you please help what we shall change, or what dependencies we shall install first, so as to be able to install `omxplayer` on very minimal distros, like `Minibian` or `Moebius` !?

Thank you for your time and support.

**Comment by popcornmix** [comment]
I'm afraid that's really a question for the author's of the distribution you are using. There are dozens of distributions out there and I don't have time to work out how they all work.
I would start by downloading the deb file from here: http://omxplayer.sconde.net/
and trying to ``sudo dpkg -i`` the deb file.
But really this isn't the right place for distribution specific questions.

**Comment by OMID-313** [comment]
You're right @popcornmix ; this is not the right place.
Actually, I asked these questions on those distribution's forums; but didn't get any answer.

Also, I don't mean that you analyze all the available distros out there.
What I'm asking is this:

What dependencies does the `omxplayer` need to be installed before its own installation on a linux-based minimal OS !?

**Comment by popcornmix** [comment]
The deb file should include the dependencies and if the distribution you are using supports apt and contains the required packages in the depo it may just work, or it may report what packages need to be installed.

Also look at:
https://github.com/popcornmix/omxplayer/blob/master/prepare-native-raspbian.sh#L14

which checks for required packages.

**Comment by OMID-313** [comment]
Thanks @popcornmix for your quick reply.

I will definitely test with the deb file, and report the results here.
