### ISSUE TITLE
xpra

### ISSUE THREAD

**Issue by pums974** [popcornmix/omxplayer#362]
xpra is a vnc-like app with high compression and low latency.
But on the raspberry pi, without hardware support, it's useless.

Would it be possible to have a simple api permitting to a python app (xpra) to send a data to omxplayer in order to use hardware decoding ?

**Comment by popcornmix** [comment]
Sorry omxplayer is a standalone video player. I doubt it is suitable for what you want.
xpra should be using OpenMAX or MMAL which are libraries suitable for HW video decode.

**Comment by pums974** [comment]
Ok, thank you.
