### ISSUE TITLE
unrecognized option

### ISSUE THREAD

**Issue by peter1308** [popcornmix/omxplayer#363]
I'm missing some options which are listed as an valid option on https://github.com/popcornmix/omxplayer. The option --alpha for example is listed on the webside but not listed by the help option and not recognized by the player. My version is: 337004e [master]. apt-get told me it's the latest.

**Comment by peter1308** [comment]
sorry. i forgot to execute the install command. So i always worked with the original omxplayer.

**Comment by popcornmix** [comment]
Have you tried a more recent build:
http://omxplayer.sconde.net/

**Comment by peter1308** [comment]
Thanx for the reply. The problem was that i went to coma during the 
compilation process. At the end i forgot to install the new version. So 
i ever worked with the old one. Installing the new version after the 
make command did the trick. Now everything works like expected. Thank 
you for waking me up.


Am 31.07.2015 15:14, schrieb popcornmix:
