### ISSUE TITLE
Can different subtitle streams be selected via D-BUS

### ISSUE THREAD

**Issue by exidyboy** [popcornmix/omxplayer#364]
The readme indicates that a specific subtitle stream can be selected via the D-BUS player interface using SelectSubtitle https://github.com/popcornmix/omxplayer/blob/master/README.md#selectsubtitle

Here is a link to a short .mkv test file in to which two subtitle tracks, one in Maori and one in English, have been multiplexed: http://www.michaelborthwick.com.au/kakapo_subs.mkv.zip

You can use the 'n' and 'm' keys to switch between subtitle languages 'on-the-fly'

I have created a modified version of the original dbuscontrol.sh here https://gist.github.com/exidyboy/6a6f178d4e8e32ba872c which looks OK to me but doesn't switch streams if I issue:

./dbuscontrol_m.sh selectsubtitles 2

against the test file linked to above.

I have also experimented with a purely Python approach using omxcontrol from @Douglas6
https://github.com/Douglas6/omxcontrol but couldn't get that to work either as discussed here:
https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=100809&p=796545#p796545

Since I have been unsuccessful in both cases I'm hoping that someone can confirm that there isn't a problem under the bonnet with the D-BUS interface itself.

The relevant code to switch subtitles via D-BUS starts here:
https://github.com/popcornmix/omxplayer/blob/master/OMXControl.cpp#L515
I note that there is an extra line
subtitles->SetActiveStream(reader->GetSubtitleIndex());
at https://github.com/popcornmix/omxplayer/blob/master/OMXControl.cpp#L532
compared to the otherwise structurally identical code immediately following that switches audio streams.

Here is the code to that handles subtitle stream switching from the keyboard for comparison
https://github.com/popcornmix/omxplayer/blob/master/omxplayer.cpp#L1264

**Comment by jehutting** [comment]
In OMXControl.cpp SelectSubtitles code the call to get the subtitle index is
`dbus_message_get_args(m, &error, DBUS_TYPE_INT32, &index, DBUS_TYPE_INVALID);
`
There is no objpath argument involved, only the INT32 index. Just remove the objpath from the dbuscontrol.sh command.

`selectsubtitles)
  dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.SelectSubtitle int32:$2 >/dev/null
	;;
`

Notice  that you use SelectSubtitle_s_ -in the dbuscontrol.sh as selector- whereas OMXPlayer dbus interface doesn't!

ALSO be aware that the interface is zero-based (0,1,2, ...) indexed, whereas the user interface is one-based (1,2,3,..). (When you select a next/previous subtitle with the keyboard key you see "Subtitle stream : 1", so one-based.)

So use `dbuscontrol.sh selectsubtitles 0` to select the subtitle which _OMXReader indexed_ as 0 (in your case the Maori subtitle).

**Comment by exidyboy** [comment]
Thanks mate tested and works. The zero based index also explains why @Douglas6 omxcontrol wasn't working.

Not sure what this sentence means though. Specifically the underscore 's' underscore:
"Notice that you use SelectSubtitle_s_ -in the dbuscontrol.sh as selector- whereas OMXPlayer dbus interface doesn't!"

Cheers !

**Comment by jehutting** [comment]
In the dbuscontrol.sh you use `selectsubtitles` with an ending s (plural form), whereas the dbus interface uses `SelectSubtitle` without an ending s (singular form). The `_s_` was to try to typeface it bold; but in markdown supported text bold is with two underscore. So `selectsubtitle`__s__. Sorry for the confusion.

**Comment by exidyboy** [comment]
OK. Thanks for the __clear explanation__. I agree it's not ideal but I thought it would be more confusing for someone hacking together a script that called dbuscontrol.sh if I broke with the user-facing convention reflected in 'toggle subtitles', 'show subtitles' and 'hide subtitles'. The next challenge is to load multiple .srt files from the command line as discussed here https://github.com/popcornmix/omxplayer/issues/45 That will be a substantial piece of work that might require sponsorship or crowd-funding.
