### ISSUE TITLE
Occasional crash when run with -g

### ISSUE THREAD

**Issue by vegizombie** [popcornmix/omxplayer#369]
On the raspberry pi B+ when playing mp3 files with -g or --genlog omxplayer will occasionally crash without returning an error code ($? outputs 0) with error text:

/usr/bin/omxplayer: line 67: <number in the low 3k> Aborted
LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"

This seems to happen randomly, although more likely with some files than others.

**Comment by popcornmix** [comment]
Does it occur before playback starts, in middle of playback or at end?
Can you post the omxplayer.log file in case there are any clues?
Can you run omxplayer through gdb to see if we get a backtrace?

**Comment by vegizombie** [comment]
It occurs before playback.

Sure, I saw nothing in there, hence not posting it but I suppose I should have. I have created 5 logs, 1-4 crashed and 5 didn't. I am not sure how to upload (drag and drop here only seems to accept images), so I am linking my google drive.
Additionally I have uploaded a track that it happens reasonably frequently on (the frequency seems to vary by track).
https://drive.google.com/folderview?id=0B1YI_2NRXSyMb0ljNXQtdktSN28&usp=sharing

Sure, how do I do so? gdb omxplayer does not work and gdb /usr/bin/omxplayer.bin returns an error about shared libraries.

**Comment by vegizombie** [comment]
I was trying to work out how I might be able to debug it when I stumbled across using 
"bash -x omxplayer"
to debug the shell script at least but that seemed to require starting it in the /usr/bin directory; I noticed that I could not cause it to crash, so I removed bash -x and still could not cause it to crash. It appears that the bug is not there when I run omxplayer in /usr/bin/ but even if I refer to it in full (ie calling /usr/bin/omxplayer) it will still crash from a different directory. I am not sure if that helps at all but I thought it interesting.

**Comment by popcornmix** [comment]
There is a fix pushed that is reported as solving the issue in #411

**Comment by jehutting** [comment]
@vegizombie Any confirmation on your issue being fixed?

**Comment by Ruffio** [comment]
@popcornmix This looks to resolved and should be closed...
