### ISSUE TITLE
Weird issue with 1080p Big Buck Bunny demo file

### ISSUE THREAD

**Issue by mihalop** [popcornmix/omxplayer#373]
On stock Raspbian Wheezy 2015-05-05, with just firmware and packages updated, on RPi2, on 1080p DVI monitor.

omxplayer: Package Version: 0.3.6~git20150912~d99bd86

firmware: Sep 29 2015 13:06:19
version 3bbf5122d0c4ff421c92d72871dbc8fa104a976d (clean) (release)

Trying to playback the following (without any options):
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4

1st playback succeeds. On all following runs, a solid color output is displayed. Tried to re-package the media using avconv (no re-encoding though), leaving only the h.264 and mp3 stream, but there was no difference.

Tried different RPi2, same behavior. Tried a fork of omxplayer (dubbed "pwomxplayer", from piwall project, based on a much older version of omxplayer) and it did not have this problem.

**Comment by popcornmix** [comment]
Cab you try with either ``omxplayer --no-osd <file>`` or add gpu_mem=128 to config.txt.

**Comment by mihalop** [comment]
Problem solved, I had:

    gpu_mem=128
    gpu_mem_256=64

in config.txt and had not realize until today that by using `gpu_mem_256`, the `gpu_mem` is ignored by 512MB and 1GB RPis.

Thnx for your time.
