### ISSUE TITLE
big delay when trying to change resolution on the go

### ISSUE THREAD

**Issue by heniotierra** [popcornmix/omxplayer#375]
I've been experimenting with dbuscontrol.sh. When you try to change the resolution of a video while it's playing, it takes some seconds to actually apply the new resolution, sometimes more than 15 seconds.

**Comment by popcornmix** [comment]
Can you explain exactly what dbus command you are sending?

**Comment by heniotierra** [comment]
Nevermind, It seems t work fine with latest version of omxplayer. Thanks. :)
