### ISSUE TITLE
Feature request: output audio current audio level to stdout

### ISSUE THREAD

**Issue by mKay1610** [popcornmix/omxplayer#377]
Hey everyone! This one should be quite easy.. I would change the code myself, but the omxplayer is just too complex for me to ... well understand it.
I want to control some LED stripes according to the music playing. So I would like omxplayer to give me the current audio level somehow without having to use alsa for that. I think it should easily possible just before the data is being flushed to the sound card, right? just write the peak out into stdout.

thank you in advance, in case there is any interest in doing this.
(it could turn the raspi into a nice "low cost party shed player")

**Comment by popcornmix** [comment]
Sorry, I think this is unlikely to be implemented. It is far from trivial and useful to *very* few people.
I imagine using a player that uses alsa will be a better choice as the samples are available to the ARM.
