### ISSUE TITLE
Concat TS input (discontinue PTS)

### ISSUE THREAD

**Issue by todostreaming** [popcornmix/omxplayer#378]
I'm trying the play smoothly 2 concatenated TS files so PTS reinits when the 1st TS files ends and the 2nd one starts, and the playback freezes the video but the audio keeps playing ok. How can I bypass the PTS issue to achive a seemless and smooth playback when changing to the second TS file ?
I've built the latest commit.
Thanks in advance and regards
/ts

**Comment by mihalop** [comment]
Why not concat though avconv or ffmpeg and feed that to omxplayer through a named pipe?

**Comment by todostreaming** [comment]
avconv/ffmpeg does not change audio nor video PTS when just remuxes. I would need to reecode in order to re-PTS the result output TS. I guess it should be better to make omxplayer handle with PTS discontinuities (specially when going back).

**Comment by mihalop** [comment]
I am already doing that. I encode original streams in individual TS, then arbitrarily feed them from avconv/ffmpeg to omxplayer as a continuous TS through a named pipe. Works fine (not sure on omxplayer version though).

Perhaps I am missing something.

**Comment by todostreaming** [comment]
How are you doing so ? I have 2 separate and different TS files encoded, and want to concat them, and play it with omxplayer.
cat file1.ts file2.ts > result.ts
omxplayer result.ts

Thanks in advance

**Comment by mihalop** [comment]
Do this:

    mkfifo /tmp/omx_fifo.ts
    ffmpeg -y -i result.ts -f mpegts -acodec copy -vcodec copy /tmp/omx_fifo.ts &
    omxplayer /tmp/omx_fifo.ts

Or better, do something like this with ffmpeg/avconv, to avoid copying:

    cat file1.ts file2.ts file3.ts file4.ts | ffmpeg -y -f mpegts -i pipe:0 -f mpegts -acodec copy -vcodec copy /tmp/omx_fifo.ts &

You could also use the concat protocol, or other ways to concat the files, see https://trac.ffmpeg.org/wiki/Concatenate

**Comment by todostreaming** [comment]
OK, nice, I'll test so.
Thanks
