### ISSUE TITLE
Running 2 instances is broken

### ISSUE THREAD

**Issue by cristallium** [popcornmix/omxplayer#379]
Test version is  : d99bd86 [master](get today)

First I run one instance fullscreen
/> omxplayer -o hdmi /box/test.mp4
Video codec omx-h264 width 1280 height 720 profile 100 fps 23.976025
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1280x720@23.98 interlace:0 deinterlace:0 anaglyph:0 par:1.00 layer:0 alpha:255

then on another terminal I run a new instance over
/> omxplayer -o hdmi --win 0,0,160,90 --layer 1 /box/test.mp4
COMXVideo::Decode timeout
COMXVideo::Decode timeout
COMXVideo::Decode timeout
...

was working fine on omxplayer
 Build date: Tue, 10 Feb 2015 01:49:30 +0000
 Version   : 337004e [master]

regards

**Comment by jehutting** [comment]
I assume that the firmware fix solves this issue too? Isn't it @cristallium ?

**Comment by cristallium** [comment]
Hi Jozef , 

I will check this. I tell you when I come back (next week) 

Regards 

Le 26.01.2016 00:32, Jozef Hutting a écrit : 

> I assume that the firmware fix solves this issue too? Isn't it @cristallium [1] ? 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Frédéric Gilli 

mob.0668542622 

http://www.cristallium.com

 [3] 

 

Links:
------
[1] https://github.com/cristallium
[2]
https://github.com/popcornmix/omxplayer/issues/379#issuecomment-174729684
[3] http://www.cristallium.com

**Comment by stevesoto** [comment]
bump

**Comment by popcornmix** [comment]
What does "bump" mean?
Are you having this issue, or are you suggesting it be closed.

My belief is the problem was solved with #386. We were waiting for confirmation from @cristallium before closing.

**Comment by stevesoto** [comment]
Maybe I'm just an old guy and thought we all knew what it means. I am also having this issue. I was also interested in the reply. Had not seen a reply so I "bumped" it to see if the person we were waiting on might have had the time to figure out the solution. Bump is an old way of saying "hello, I am also interested in this topic"

https://ubuntuforums.org/showthread.php?t=786621

**Comment by popcornmix** [comment]
Have you increased gpu_mem?
For 2 instances of omxplayer I'd suggest trying with gpu_mem=256 (you may get away with less, but the default of 64M will definitely be too low).

**Comment by stevesoto** [comment]
I am trying it with 256 and will report back

**Comment by stevesoto** [comment]
Well, that made a great improvement. Thank you!

**Comment by popcornmix** [comment]
I'll close this - issue believed to have been fixed 10 months ago.
