### ISSUE TITLE
Mouse support in omxplayer

### ISSUE THREAD

**Issue by nsenica** [popcornmix/omxplayer#383]
Hi

I'm just wondering how easy would it be to have mouse support in omxplayer.

My main concern is how to detect that there was a mouse event that can be passed on to omxplayer, in the same way that a key is pressed.

My first idea would be to detect a mouse click and pause/unpause the video, then I could work on adding more functionality.

Do you have any pointers or ideas on how this could be done ? I know we can use dbus to send the events, but I'm a bit before that, first I need to capture the mouse event, and this is what I don't exactly know how to and for which I'd like some pointers.

Thanks

**Comment by popcornmix** [comment]
No plans for mouse support inside omxplayer, so an external app plus dbus is the right solution.
It depends on whether you want to run from console or from X.

If running from console, take a look at /opt/vc/src/hello_pi/hello_triangle2 which has simple mouse support. X programming is more involved and not something I'm very familar with.

But really the forum is the right place for asking general programming questions.
