### ISSUE TITLE
Compiling on Arch armv7

### ISSUE THREAD

**Issue by Farbdose** [popcornmix/omxplayer#388]
Hi 
I have some trouble compiling omxplayer on my pi (pacman Version hasn't working subtitles)
I am trying to build it directly on the pi
arch + armv7 + gcc 5.2.0

make
bash gen_version.sh > version.h
/bin/g++ --sysroot= -fPIC -DPIC -L/lib -L/lib -L/usr/lib -L/opt/vc/lib/ -Lpcre/build -L./ -Lffmpeg_compiled/usr/local/lib/ -lc -lWFC -lGLESv2 -lEGL -lbcm_host -lopenmaxil -lfreetype -lz -o omxplayer.bin linux/XMemUtils.o utils/log.o DynamicDll.o utils/PCMRemap.o utils/RegExp.o OMXSubtitleTagSami.o OMXOverlayCodecText.o BitstreamConverter.o linux/RBP.o OMXThread.o OMXReader.o OMXStreamInfo.o OMXAudioCodecOMX.o OMXCore.o OMXVideo.o OMXAudio.o OMXClock.o File.o OMXPlayerVideo.o OMXPlayerAudio.o OMXPlayerSubtitles.o SubtitleRenderer.o Unicode.o Srt.o KeyConfig.o OMXControl.o Keyboard.o omxplayer.o -lvchiq_arm -lvcos -ldbus-1 -lrt -lpthread -lavutil -lavcodec -lavformat -lswscale -lswresample -lpcre
/bin/ld: SubtitleRenderer.o: undefined reference to symbol 'vgDestroyPath'
/opt/vc/lib/libEGL.so: error adding symbols: DSO missing from command line
collect2: Fehler: ld gab 1 als Ende-Status zurück
Makefile:54: die Regel für Ziel „omxplayer.bin“ scheiterte
make: **\* [omxplayer.bin] Fehler

I thought that maybe libEGL is outdated.... But trying to get a new ffmpeg created even more problems... So I thought maybe you can help before I continiue on the wrong path

**Comment by popcornmix** [comment]
Does adding ``-lOpenVG`` to the Makefile help?

**Comment by Farbdose** [comment]
Thx that worked

....but....

-> Installed the new omxplayer
-> added the correct font path to the shell script
-> pressed s after starting the player
.... and still no subtitles :(

**Comment by popcornmix** [comment]
What is gpu_mem set to? For 1080p+subs you need more than 64M. 128M is likely to be enough.

**Comment by Farbdose** [comment]
Its at 64M but i used a 720p mkv file with soft-coded subs
(I will test it in the next hours)

**Comment by Farbdose** [comment]
tested with 128M
still no subtitles (going to install kodi now.... maybe its working there - I didn't want to install the complete kodi just to watch a mkv with subtitles)

**Comment by popcornmix** [comment]
What sort of subs?
omxplayer only handles simple textual subs - no support for bitmapped.
kodi has much wider support.

**Comment by Ruffio** [comment]
@Farbdose ping

**Comment by Farbdose** [comment]
@Ruffio  I gave up on compiling omxplayer and just installed Kodi as @popcornmix  suggested. Consider the issue as wontfix/closed.
