### ISSUE TITLE
GetLevel  32 Bits versus 64 bits (m_cached_size)

### ISSUE THREAD

**Issue by romuald-maillet** [popcornmix/omxplayer#389]
Hello

The GetLevel () functions in OMXPlayerVideo and OMXAudio ,
are buggy when using an option like video_queue = 1000 ( overflow in the calculation ) .

I've changed
 GetLevel unsigned int () {return m_config.queue_size ? M_cached_size * 100 / ( m_config.queue_size * 1024 * 1024) : 0; } ;

by

unsigned char GetLevel () {return m_config.queue_size ? (char ) (100 * ( long long ) m_cached_size / ( ( long long ) m_config.queue_size * 1024 * 1024 ) ) : 0; } ;

I am sad to know that the maximum capacity is 32 bits . It will be just for me. (for my long pause)
 
Good day

Bonjour

Les fonctions GetLevel()  dans OMXPlayerVideo et OMXAudio,
sont buggué  si on utilise une option comme video_queue=1000 (dépassement de capacité dans le calcul ).

J'ai changé
 unsigned int GetLevel() { return m_config.queue_size ? 100 * m_cached_size / (m_config.queue_size * 1024 * 1024) : 0; };

par

unsigned char GetLevel() { return m_config.queue_size ? (char) (100 *  (long long) m_cached_size / ( (long long) m_config.queue_size * 1024 * 1024)) : 0; };

Je suis triste de savoir que la capacité max est codé sur 32 bits. Ca va être tout juste pour moi. (pour ma longue pause)
 
Bonne journée

**Comment by popcornmix** [comment]
video_queue is in MB, so it wouldn't make sense to set it to 1000 (there is only 1GB of ram in total, and the GPU and linux itself will be using a couple of hundred MB).

Currently overflow will occur if 100 * m_cached_size > 4G or m_cached_size > 40M. I guess that could happen. m_config.queue_size is already floating point, so that doesn't have the problem. Forcing 100 * m_cached_size to be floating point should fix it.

I've pushed the change - can you test.

**Comment by romuald-maillet** [comment]
Good evening everybody,

PopcornMix thank you for your answer . It's nice to be heard .

I am at home but tomorrow morning I will hasten to test it all and I 'll keep you posted .

For me, it is imperative to use the 64-bit in these functions .

I know GetLevel returns a number between 0 and 100 (sufficient char) . I also know that this value is used in calculations .
So use Unsigned Int to avoid casting OK but this causes nuisance understanding .

Personally I think : GetLevel returns a char is enough and logical.

This is philosophy . I am French. LOL .

Finally, if I'm not mistaken ( I will test tomorrow) I think about Raspberry Pi2 on 32bit float is therefore the problem persists.

I wish you a nice day / night and has told you tomorrow for the continuation.

Thank you again for having me answer this proves that I do not tell too much bullshit . ;-)


Romuald


Bonsoir tout le monde,

Merci PopcornMix pour ta réponse. Ca fait plaisir d'etre entendu.

Je suis a la maison mais demain matin je vais m'empresser de tester tout ça et je te tiendrai au courant.

Pour moi, il est impératif d'utiliser du 64 bits dans ces fonctions.

Je sais que GetLevel retourne un  nombre entre 0 et 100 (char suffisant). Je sais aussi que cette valeur est utilisé dans des calculs.
Et donc utiliser Unsigned Int pour éviter les casting OK mais cela provoque des nuisances de compréhension.

Personnellement Je crois que : GetLevel retourne un char est suffisant et logique.

C'est de la philosophie. Je suis français. LOL.

Pour finir, si je me trompe pas (je testerai demain)  il me semble que sur RaspBerry Pi2 float est sur 32bits donc le probleme persiste.

Je te souhaite une bonne journée/nuit  et te dit a demain pour la suite.

Merci encore de m'avoir répondu cela prouve que je ne raconte pas trop de connerie. ;-)


Romuald

**Comment by romuald-maillet** [comment]
Hello

The size of a float and an Int is the same: 4 bytes.
The problem is not corrected .

To really fix the problem , we should spend queue_size double (because m_config.queue_size * 1024 * 1024 ) and  m_cached_size in long long (because m_cached_size + pkt- > size )

I look away if the problem exists on other variables.
 
Thank you

See you soon , Romuald

Bonjour

La taille d'un float et d'un Int est identique : 4 octets. 
Le probleme n'est donc pas corrigé.

Pour vraiment corriger le problème, il faudrait passer queue_size en double (parce que m_config.queue_size * 1024 * 1024 ) et m_cached_size en long long (parce que m_cached_size + pkt->size) 

Je regarde ailleurs si le probleme existe sur d'autres variables.
 
Merci

A bientot,  Romuald

**Comment by popcornmix** [comment]
Please test. A float has plenty of precision for a calculation that returns a percentage.
And an (unsigned) integer is the correct return type. The integer type typically matches the processor register size in C and is the most efficient type to use. Narrower types should only be used when there is a good reason (e.g. large arrays when data size is important).

**Comment by romuald-maillet** [comment]
Hello Popcornmix

For the return type between char and unsigned int I shared OK but because of the performance, then this is not the subject (though).

By cons I am surprised that a man like you asked me to test this change, which changes nothing. It's probably because of the google translation.
Here is the problem
unsigned int a = 0xFFFFFFFF
unsigned long long b = 2 * a (capacity Overtake because a 32bits is explicitly and implicitly the number two 32-bit (native machine type))
unsigned long long b = 2.0f * a (Overtake same thing capacity and casting compiler warning: 2.0f * A is 32 bits)
unsigned long long  b=2ULL * a  (OK explicit cast 64 bits, no overflow during the calculation)

The problem is not the formula of calculation but in the types of data used during  the calculation.

 I made the changes that go well (in m_cached_size m_config.queue_size long long and double) and printf with% llu and now I have another problem (the same ?).

To recap my goal is to have a very long pause.

I started by testing with a virtual memory of 2 gigabytes and option video_queue audio_queue = 1500 = 500
It works very very well. There are still 15 mega RAM memory and the swap meets.
I use virtual memory as data storage not to launch 3 tons of process.
With a stream FullHD I get about 25 minute break to swap 1giga, impeccable.
But going further there after a bug: it does not resume playing.
My raspberry still works very well.
When I paused puts it continues to store the swap.
I think the bug is the same as GetLevel.
A calculation somewhere in the programmel causes an overflow and returns a false result. I'm looking for.

I am afraid when I see in the following prototypes omxplayeraudio.h
   Double GetDelay ();
  Double GetCacheTime ();
  Double GetCacheTotal ();
and the delegated functions omxaudio.h
  GetDelay float ();
  GetCacheTime float ();
  GetCacheTotal float ();

What it is used to declare Double GetDelay knowing he will never return to true 64-bit value: To avoid a calculation error, right?

If not the only problem was when I leave the application: You have to release some giga and AC takes some time: Less than 10 seconds to break 20 minutes but I can do nothing.

Hope to read you, Romuald

Bonjour Popcornmix

Pour le type de retour entre char et unsigned int je suis partagé mais OK a cause de la performance et puis ce n'est pas le sujet (quoique).

Par contre je suis surpris qu'un homme tel que vous me demande de tester ce changement qui ne change rien. C'est surement a cause de la traduction google.
Voici le probleme
unsigned int a = 0xFFFFFFFF
unsigned long long  b=2*a (depassement de capacité parce que a is 32bits explicitement and le nombre 2 est 32 bits implicitement (type natif de la machine) )
unsigned long long b=2.0f*a (depassement de capacité meme chose et avertissement casting compilateur: 2.0f*A est 32 bits)
unsigned long long b= 2ULL*a (ok casting explicite 64 bits, pas de dépassement durant le calcul)

Le probleme n'est pas la formule du calcul mais dans les types de données utilisés pour le calcul.

Sinon j'ai fait les modifications qui vont bien ( m_cached_size en long long et m_config.queue_size en double)  et les printf avec %llu et maintenant j'ai un autre probleme.

Pour rappel mon but est d'avoir une tres longue pause.

J'ai commencé par tester avec une memoire virtuelle de 2 giga et l'option video_queue=1500 audio_queue=500
Ca fonctionne tres tres bien. Il reste toujours 15 méga de memoire vive et le swap ce remplit.
J'utilise la mémoire virtuelle comme stockage de données pas pour lancer 3 tonnes de processus.
Avec un flux FullHD j'obtient environ 25 minutes de pause pour 1giga de swap, impeccable.
Mais en allant plus loin il y a un bug aprés : il ne reprend pas la lecture. 
Mon raspberry fonctionne encore tres bien. 
Quand je remet en pause il continue de stocker dans le swap.
Je pense que le bug est le même que GetLevel.
Un calcul quelque part dans le programmel provoque un dépassement de capacité et retourne un faux résultat. Je cherche.

J'ai peur quand je vois dans omxplayeraudio.h les prototypes suivants
   double GetDelay();
  double GetCacheTime();
  double GetCacheTotal();
et dans les fonctions délégué de omxaudio.h
  float GetDelay();
  float GetCacheTime();
  float GetCacheTotal();

A quoi ca sert de déclarer Double GetDelay sachant qu'il ne retournera jamais de vraie valeur 64 bits  : Pour éviter une erreur de calcul, non ?

Sinon le seul inconvénient c'est lorsque je quitte l'application: Il faut libérer quelques giga et ca prend un certain temps : Moins de 10 secondes pour 20 minutes de pause mais je peux rien faire.

Au plaisir de vous lire, Romuald

**Comment by popcornmix** [comment]
Can you explain in this formula:
``100.0f * m_cached_size / (m_config.queue_size * 1024 * 1024)``
What the values of m_cached_size and m_config.queue_size are when you get the overflow?

Note: that m_config.queue_size is the size is MB, so cannot be more than 1000 on a Pi.

**Comment by romuald-maillet** [comment]
Hello Popcornmix,

You understood that I speak of the overflow when the value of m_config.queue_size, m_cached_size is very high because RESULT formula requires (if we want natural integers) 7 bits to be stored, 0-100 value expressing a percentage Use the video / audio buffer but it also needs to be 64 bits TEMPORARILY calculated correctly when using high values.

The SWAP 1Giga limit on a PI 2, as mentioned in my previous post, I passed. For now I am testing with 2GB SWAP. The Raspberry is slower course, but it works perfectly. I will come to you to give you the results of two instances omxplayer pause / play with 3 or 4 gigabytes swap.

I would simply say that it is a shame not to use the opportunity to make calculations in 64-bit and have power and that would allow us to do things in a very long pause on a real-time stream.

I think I explained the problem well: OMXPlayer certain formulas used in 32-bit data typed, the result can be only 32 bits even if the storage variable is declared 64bit. See my previous post when I speak of
 Double GetCacheTime () call that float GetCacheTime () -> 64 bits to store a 32-bit result! (Potential vicious Bug)

It is less powerful than it could have been: Today, in 32-bit calculation, I have a pause of 20 minutes on  stream FullHD but in 64Bits calculation, how I can get in my good Raspberry Pi 
 2 if OMXPlayer not clamped in the source code.

I never know if I'm having trouble finding places where I do all my castings 64-bit, you better put, that going to do you?

1) Undertake mounted power of OMXPlayer?
2) leave as is?
3) Help me telling me places where I have to correct my version (long pause)?

Congratulations to the entire team of OMXPlayer which is a great study software for me.

Have a nice day ;-) Romuald

PS: OMXPlayer is programmed only for Raspberry or it is multi-architecture? 

Bonjour Popcornmix,

Vous avez compris que je parle du débordement lorsque la valeur de m_config.queue_size, m_cached_size est très élevé car LE RESULTAT de la formule nécessite (si on veut que des entiers naturel)  7 bits pour être stocké , valeur de 0-100 exprimant un pourcentage d'utilisation du buffer video/audio mais elle a aussi besoin de 64 bits TEMPORAIREMENT pour être calculé correctement quand on utilise des valeurs elevé.

La limite de 1Giga de SWAP sur un PI 2 ,comme mentionné dans mon précédant courrier, je l'ai  dépassé. Pour l'instant je teste avec 2Go de SWAP. Le Raspberry est plus lent certes, mais il fonctionne parfaitement. Je reviendrai vers vous pour vous donner les résultats de deux instances omxplayer en pause/lecture avec 3 ou 4 giga de swap.

Je voudrais simplement dire qu'il est dommage de ne pas utiliser la possibilité de faire des calculs en 64 bits et d'avoir ainsi une puissance qui nous permettrait en autres choses de faire une très longue pause sur un flux temps réel.

Je pense avoir bien exposé le problème : OMXPlayer utilise dans certaines formules des données typés 32 bits dont le résultat ne peut être que 32 bits même si la variable de stockage est déclaré 64 bits.  Voir mon précédent courrier quand je parles de 
 double GetCacheTime () qui appel float GetCacheTime () -> 64 bits pour stocker un résultat 32 bits ! (Bug vicieux potentiel)

Il est moins puissant que ce qu'il aurait pu être : Aujourd'hui j'ai 20 minutes de pause en 32 bits sur un flux FullHD mais combien j'aurai pu avoir en 64Bits sur mon brave Raspberry Pi 2 si OMXPlayer n'avait pas été bridé dans le code source. 

Je ne le saurai jamais si je ne parviens pas a trouver les endroits ou je dois faire tous mes castings 64 bits, vous êtes le mieux placer, qu'aller vous faire ? 

1) Entreprendre la monté en puissance d'OMXPlayer ?
2) Le laisser tel quel ?
3) M'aider en m'indiquant les endroits ou je dois corriger pour ma version (longue pause) ?

Encore bravo a toute l'équipe d'OMXPlayer qui est un formidable logiciel d'étude pour moi.

Have a nice day ;-) Romuald 

PS: OMXPlayer est programmé seulement pour Raspberry ou il est multi-architecture ?

**Comment by popcornmix** [comment]
Can you test with:
```100.0f * m_cached_size / (m_config.queue_size * 1024.0f * 1024.0f)```

**Comment by romuald-maillet** [comment]
Hello PopCormix ,

I will test and you send logs since you insist .

But I will write a demonstration program that I think will be more telling than fine speech .

To recap what I want to say is :
32bits * 32bits / ( 32bit * 32bit * 32bit ) = 32 BITS result is that simple
64bits * 32bits * / 8bit / 16bit =  64 Bits result right
Attention because the evaluation order of the expression is very important
 32-bit * 32 bit / 64 bit = 64-bit result but may be false because in the early 32 bits * 32 bits = 32 bits

I am sending you a demonstration program and tomorrow I will send you logs of OMXPLayer .
Until tomorrow,

Good day to you, Romuald

Bonjour PopCormix,

Je vais tester et vous envoyez des logs puisque vous insistez.

Mais je vais écrire un programme de démonstration qui sera je pense plus parlant que de beau discours.

Pour rappel ce que je veux vous dire c'est :
32bits*32bits/(32bits*32bits*32bits) = 32 BITS Résultat c'est aussi simple que cela
Ou bien 64bits*32bits/8bits/16bits=64 Bits résultat
Attention car l'ordre d'évaluation de l'expression est très important
32 bits * 32 bits / 64 bits = 64 bits Résultat mais peut être faux parce que au début 32 bits * 32 bits = 32 bits

Je vous envoie un programme de démonstration et demain je vous enverrai des logs d'OMXPLayer.
A demain,
Bonne journée a vous, Romuald

**Comment by romuald-maillet** [comment]
Hello Popcornmix.

I made a test program and I am surprised at the result!
I have spent much of the day. You will find below the program output and program. I did the C / C ++ 1988 to 1999, much has changed since.

In OMXPlayer 32Bits, the calculation becomes wrong when m_cached_size> 4096 * 1024 * 1024 because m_cached_size is 32 bits. It's normal.

By cons I 'm expecting a false result from the very first test of the formula (100.0f m_cached_size *)> 32 bit (float) during the calculation.

I concluded that float calculation with more than 32 bits and carries a 32-bit cast before stored.
Is what I will have the same behavior on other 32-bit machines?

I think that with 32 bits so 4GB of memory will be enough for my long break and the 64-bit version will wait for the raspberry pi 4.

By cons when I pause and I 1Giga exceeds SWAP does not resume play but it continues to operate (raspberry and omxplayer).

Thursday I will send you logs of omxplayer today I have not had time.

Thank you for listening and responding.

See you soon. Romuald

Output of program : overflow at execute 6
------------------------------------------
Size of data type signed/unsigned are same
------------------------------------------
float : 4 bytes,double 8 bytes
int 4 bytes, unsigned int 4 bytes
long 4 bytes, long long 8 bytes
unsigned long 4 bytes, unsigned long long 8 bytes
------------------------------------------
Value of data type  
------------------------------------------
float: 4294967296.000000
double: 18446744073709551616.000000
long: -1
int: -1
unsigned int: 4294967295
long long : -1
unsigned long : 4294967295
unsigned long long : 18446744073709551615
------------------------------------------
Test GetLevel 32 Bits versus 64bits
---------------------------------------------------
queue_size=1024  Execution Test : 01
 --------------------------------------------------
32 bits: when   m_cached_size=1073741824 (107374182400) the result is:  100%
64 bits: when m_cached_size64=1073741824 (107374182400) the result is: 100%
---------------------------------------------------
queue_size=1025  Execution Test : 02
 --------------------------------------------------
32 bits: when   m_cached_size=1074790400 (107479040000) the result is:  100%
64 bits: when m_cached_size64=1074790400 (107479040000) the result is: 100%
---------------------------------------------------
queue_size=2048  Execution Test : 03
 --------------------------------------------------
32 bits: when   m_cached_size=2147483648 (214748364800) the result is:  100%
64 bits: when m_cached_size64=2147483648 (214748364800) the result is: 100%
---------------------------------------------------
queue_size=2048  Execution Test : 04
 --------------------------------------------------
32 bits: when   m_cached_size=2147483648 (214748364800) the result is:  100%
64 bits: when m_cached_size64=2147483648 (214748364800) the result is: 100%
---------------------------------------------------
queue_size=4096  Execution Test : 05
 --------------------------------------------------
32 bits: when   m_cached_size=4294967295 (429496729600) the result is:  100%
64 bits: when m_cached_size64=4294967296 (429496729600) the result is: 100%
---------------------------------------------------
queue_size=4097  Execution Test : 06
 --------------------------------------------------
32 bits: when   m_cached_size=4294967295 (429496729600) the result is:  99%
64 bits: when m_cached_size64=4296015872 (429601587200) the result is: 100%
---------------------------------------------------
queue_size=5100  Execution Test : 07
 --------------------------------------------------
32 bits: when   m_cached_size=4294967295 (429496729600) the result is:  80%
64 bits: when m_cached_size64=5347737600 (534773760000) the result is: 100%
---------------------------------------------------
queue_size=5120  Execution Test : 08
 --------------------------------------------------
32 bits: when   m_cached_size=4294967295 (429496729600) the result is:  80%
64 bits: when m_cached_size64=5368709120 (536870912000) the result is: 100%
---------------------------------------------------
queue_size=6000  Execution Test : 09
 --------------------------------------------------
32 bits: when   m_cached_size=4294967295 (429496729600) the result is:  68%
64 bits: when m_cached_size64=6291456000 (629145600000) the result is: 100%
---------------------------------------------------
queue_size=7000  Execution Test : 10
 --------------------------------------------------
32 bits: when   m_cached_size=4294967295 (429496729600) the result is:  58%
64 bits: when m_cached_size64=7340032000 (734003200000) the result is: 100%
---------------------------------------------------
queue_size=8193  Execution Test : 11
 --------------------------------------------------
32 bits: when   m_cached_size=4294967295 (429496729600) the result is:  49%
64 bits: when m_cached_size64=8590983168 (859098316800) the result is: 100%
---------------------------------------------------
queue_size=16384  Execution Test : 12
 --------------------------------------------------
32 bits: when   m_cached_size=4294967295 (429496729600) the result is:  25%
64 bits: when m_cached_size64=17179869184 (1717986918400) the result is: 100%


///////////////////////////////////////////////////////////////////////////////////////////////////// THE PROGRAMM


#include <stdio.h>

// 2147483648

// 4294967296 = 2^32
// 1073741824 = 1024*1024*1024 = 1 Giga
 

/***** Original Variable OMXPlayer *****/
float queue_size;
unsigned int m_cached_size;
unsigned long long m_cached_size64; // The new type for OMXPlayer 64 bits version capability ->

/**
 * Original prototype in OMXPlayer : 32 bits calculation
 * m_cached_size > 42 949 672 do a overflow calculation because (32 bits X 32 bits =  32 Bits result max)
 * 
 */
unsigned int getLevel() {
    return queue_size ? (100.0f * m_cached_size / (queue_size * 1024 * 1024)) : 0;
}

/**
 * Modified Prototype for 64Bits calculation
 * 
 * @return   Use a char or unsigned int as the return type
 *   is a philosophical question and depending on the future use of the variable. (What it will serve)
 * 
 *  But, this is not the subject here. Use unsigned int if you prefer, the result of test is same.
 * 
 *  m_cached_size64 > ( 2^64 /100 ) do a overflow calculation
 * 
 */
char getLevel64() {
    return queue_size ? (100 * m_cached_size64 / (queue_size * 1024 * 1024)) : 0;
}


static int nbexecute = 0;

/**
 * Show value of variable m_cached_size, and begin calcul of formula, and result.
 */
void executeTest() {
    printf("32 bits: when   m_cached_size=%u (%0.f) the result is:  %u%%\n", m_cached_size,m_cached_size*100.0f, getLevel());
    printf("64 bits: when m_cached_size64=%llu (%llu) the result is: %d%%\n", m_cached_size64,m_cached_size64*100, getLevel64());
    
}

int main(void) {

    float sfvar = 0xFFFFFFFF;
    double sdvar = 0xFFFFFFFFFFFFFFFF;
    int sivar = 0xFFFFFFFF;
    unsigned int uivar = 0xFFFFFFFF;

    long slvar = 0xFFFFFFFF;
    long long sllvar = 0xFFFFFFFFFFFFFFFF;

    unsigned long ulvar = 0xFFFFFFFF;
    unsigned long long ullvar = 0xFFFFFFFFFFFFFFFF;

    printf("------------------------------------------\n");
    printf("Size of data type signed/unsigned are same\n");
    printf("------------------------------------------\n");

    printf("float : %d bytes,double %d bytes\nint %d bytes, unsigned int %d bytes\nlong %d bytes, long long %d bytes\nunsigned long %d bytes, unsigned long long %d bytes\n",
            sizeof (sfvar), sizeof (sdvar), sizeof (sivar), sizeof (uivar), sizeof (slvar), sizeof (sllvar), sizeof (ulvar), sizeof (ullvar));

  
    printf("------------------------------------------\n");
    printf("Value of data type  \n");
    printf("------------------------------------------\n");

    printf("float: %f\ndouble: %f\nlong: %ld\nint: %d\nunsigned int: %u\nlong long : %lld\nunsigned long : %lu\nunsigned long long : %llu\n",
            sfvar, sdvar, slvar, sivar, uivar, sllvar, ulvar, ullvar);
    
 //  printf("float+10: %f float-10: %f\n",sfvar+10.0f,sfvar-10.0f);

    printf("------------------------------------------\n");
    printf("Test GetLevel 32 Bits versus 64bits\n");
    int i, j;
    
    float testqueue_size[] = {1024, 1025, 2048, 2048, 4096, 4097,5100,5120,6000,7000, 8193,16384};
    float coeff[]={0.25,0.50,0.75,1};
    
    for (i = 0; i < 12; i++) {
        queue_size = testqueue_size[i]; // 50
        printf("---------------------------------------------------\n");
        printf("queue_size=%0.f  Execution Test : %02d\n ", queue_size, ++nbexecute);
        printf("--------------------------------------------------\n");
        for (j = 3; j < 4; j++) {
            m_cached_size= coeff[j]*(queue_size * 1024 *1024) ; // 32bits * (32 bits * 32bits * 32 bits) store to 32 bits : How many bits during calcul, 32 or + ?
            m_cached_size64=coeff[j]*( queue_size * 1024 *1024); // 32 bits * (32bits * 32bits * 32 bits) store to 64 bits :  How many bits during calcul, 32 or + ?
            
            executeTest();
        }
    }
    
    return 0;
}

Bonjour Popcornmix.

J'ai fait un programme de test et je suis surpris du résultat ! 
J' y ai passé une bonne partie de la journée. Vous trouverez ci-dessous la sortie du programme et le programme. J'ai fait du C/C++ de 1988 à 1999, beaucoup de choses ont changés depuis. 

Dans OMXPlayer 32Bits, le calcul devient faux quand m_cached_size > 4096*1024*1024 parce que m_cached_size est 32 bits. C'est normal.

Par contre je m' attendais à un résultat faux dés le premier test de la formule (100.0f * m_cached_size ) > 32 bits (float) durant le calcul.

Je conclu que float calcul avec plus de 32 bits et réalise un casting 32 bits avant de stocké.
Est ce que j' aurai le même comportement sur d'autres machines 32 bits ?

Je pense qu' avec 32 bits donc 4 Go de mémoire sera suffisant pour ma longue pause et que la version 64 bits pourra attendre le raspberry pi 4.

Par contre quand je met en pause et que je dépasse 1Giga SWAP il ne reprend pas la lecture mais il continue de fonctionner (raspberry and omxplayer).

Jeudi je vous enverrai des logs d'omxplayer, aujourd'hui je n'ai pas eu le temps.

Merci de m'avoir écouté et répondu.

A bientôt. Romuald

**Comment by romuald-maillet** [comment]
Hello Popcornmix

I am amazed . I do not understand. The float caclul in 128 bits and 1024 bits in double !

Is sizeof (float) is buggy . How can he stored a 32 bit higher result.
The small test program with part of the output

    int i=0;
    double r=1.0;
    float v=1.0f;

    for (i=1;i<=1025;i++) {
        v=v*2;
        r=r*2;
        printf("%d bits, v=%f r=%f\n",(i+1),v,r);
    }

2 bits, v=2.000000 r=2.000000
3 bits, v=4.000000 r=4.000000
4 bits, v=8.000000 r=8.000000
5 bits, v=16.000000 r=16.000000
6 bits, v=32.000000 r=32.000000
7 bits, v=64.000000 r=64.000000
8 bits, v=128.000000 r=128.000000
.....
127 bits, v=85070591730234615865843651857942052864.000000 r=85070591730234615865843651857942052864.000000
128 bits, v=170141183460469231731687303715884105728.000000 r=170141183460469231731687303715884105728.000000

129 bits, v=inf r=340282366920938463463374607431768211456.000000
1
1024 bits, v=inf r=89884656743115795386465259539451236680898848947115328636715040578866337902750481566354238661203768010560056939935696678829394884407208311246423715319737062188883946712432742638151109800623047059726541476042502884419075341171231440736956555270413618581675255342293149119973622969239858152417678164812112068608.000000

1025 bits, v=inf r=inf
1026 bits, v=inf r=inf

Good day, Romuald


Bonjour Popcornmix

Je suis stupéfait. Je ne comprend pas. Le float caclul en 128 bits et le double en 1024 bits !

Est ce que sizeof(float) est bugué. Comment peut il stocké un résultat supérieur à 32 bits. 
Le petit programme de test avec une partie de la sortie

**Comment by romuald-maillet** [comment]
Re,

I made revisions. I remember that a miscalculation computer if they are not whole numbers. Float and double that uses powers of 10 ( mantissa and exponent) which explains the results are approximate .

You can cloturer discution this if you wish.

I still have the reading bug at times beyond 1GB . Can you give me more detail why it does not work . Is there would not be the same calculation problem somewhere other .

Good day, Romuald

Re,

J'ai fait des révisions. Je me souvient qu'un ordinateur calcul faux si ce ne sont pas des nombres entiers. Que float et double utilise des puissances de 10 (mantisse et exposant) ce qui explique les résultats qui sont approximatif.

Vous pouvez cloturer cette discution si vous le souhaitez.

Il me reste le bug de reprises de lecture au dela d'1Go. Pouvez-vous me donner plus de détail pourquoi ca ne marche pas. Est ce qu'il n'y aurait pas le meme probleme de calcul quelque part d'autres.

Bonne journée, Romuald

**Comment by popcornmix** [comment]
My suggestion of ``100.0f * m_cached_size / (m_config.queue_size * 1024.0f * 1024.0f)`` should fix the 1G limit.

**Comment by romuald-maillet** [comment]
Hello,

Yes , the formula corrects the overflow bug.
You can close this discution . We have trouble communicating .

What interests me is that a PAUSE goes beyond 1Giga . I am currently testing with 2Giga .
I will keep you informed of my test by opening another discution .

Good day , Romuald

Bonjour,

Oui, la formule corrige le bug de dépassement.
Vous pouvez clôturer cette discution. Nous avons du mal à communiquer.

Ce qui m'interesse c'est une PAUSE qui va au delà d'1Giga. Je suis en train de tester avec 2Giga. 
Je vous tiendrai au courant de mes test en ouvrant une autre discution.

Bonne journée, Romuald

**Comment by popcornmix** [comment]
I've pushed the change.
