### ISSUE TITLE
HDMI remote support

### ISSUE THREAD

**Issue by kaihendry** [popcornmix/omxplayer#392]
omxplayer is typically connected to a HDMI screen which often comes along with a remote with Stop/Play/Forward/Back playback buttons. Could omxplayer please have some option to work with such input devices?

Previously filed wrongly upon https://github.com/huceke/omxplayer/issues/252

**Comment by popcornmix** [comment]
This is unlikely to be added to core omxplayer.
omxplayer has support for external scripts/apps to control it using dbus. This means a bash script could be written using cecclient to detect presses and then send commands with dbus.

See: https://github.com/popcornmix/omxplayer/blob/master/dbuscontrol.sh

**Comment by Ruffio** [comment]
@popcornmix consider closing this, as means are already available to control omxplayer using dbus
