### ISSUE TITLE
 dbuscontrol.sh syntax error

### ISSUE THREAD

**Issue by tonyrh** [popcornmix/omxplayer#395]
Hello when I try to run  dbuscontrol.sh I get

     osmc@osmc:~$ sh dbuscontrol.sh status
     dbuscontrol.sh: 16: dbuscontrol.sh: Syntax error: redirection unexpected

Any hints?

**Comment by blakee** [comment]
dbuscontrol.sh is a bash script, your sh doesn't seem to like the "<<<" operator.

If you have bash available, and 99.9% of systems do, just run it as

```./dbuscontrol.sh status```

**Comment by tonyrh** [comment]
Thanks @blakee 
I'm on OSMC and /bin/sh is a link to /bin/dash ... Debian Almquist shell!
