### ISSUE TITLE
Support for playing 'file:///home/user/video.mp4'

### ISSUE THREAD

**Issue by pickfire** [popcornmix/omxplayer#400]
Hi, I hope that omxplayer can be like ffplay which could play:

    file:///home/user/video.mp4

which is equivalent to:

    ~/video.mp4

This enables browser to play videos.

**Comment by popcornmix** [comment]
It may make more sense for a wrapper script to mangle the filename. Using sed or similar could adjust the filename as desired.

**Comment by pickfire** [comment]
That's right, but most applications support it as default such as ffmpeg. This could help to increase portablility of omplayer so it will work just like any other player.

**Comment by jehutting** [comment]
@popcornmix Isn't a matter of (sub-)stripping in OMXReader::Open() the "file://" part from the filename given?

What's the catch?

**Comment by popcornmix** [comment]
I've added https://github.com/popcornmix/omxplayer/commit/c4b166f9976fdceb788b4cb7452bf34242dfdcde
Does that solve the issue?

**Comment by pickfire** [comment]
@popcornmix Thanks a lot for that, it works now. I will appreciate it.

Good luck and have a nice day.
