### ISSUE TITLE
SubStationAudio (SSA) subtitles not working?

### ISSUE THREAD

**Issue by JontomXire** [popcornmix/omxplayer#402]
Does OMXPlayer support SSA (SubStationAlpha) subtitles?

I have some really nice 1080p MKV format anime, but the subtitles don't display. I have been using VLC to convert them as overlay on the video, but it keeps dropping iframes or something during the conversion with the result that the video gets corrupted here and there for several seconds at a time.

It would be great if the subtitles displayed natively. I can get a sample if necessary. I have a 4MB, 10 second sample (like I said the video is 1080P). I could always download a lower resolution and cut out 10 seconds of that if required.

Thanks.

**Comment by popcornmix** [comment]
Advanced subtitles are not supported by omxplayer
@torarin added "rudimentary SSA parsing" long ago - he may be able to confirm exactly what should be supported.
Kodi may be a better option as it includes libass and supports many subtitles formats.

**Comment by JontomXire** [comment]
What is "Kodi"?

**Comment by popcornmix** [comment]
http://kodi.tv/

If you are on jessie then ``sudo apt-get install kodi`` should work, although dedicated images are recommened like OpenELEC or OSMC.

**Comment by torarin** [comment]
Omxplayer attempts to convert embedded SSA subtitles to plain text and display them. It does not support reading SSA files.

**Comment by JontomXire** [comment]
It doesn't seem to work for my files :( I may have to dig into the code somewhat as the script I wrote to convert them can result in simultaneous STR subtitles and OMXPlayer only displays the first oen it comes to.

I see that Kodi=XBMC. I decided not to use XBMC a long time ago as I didn't want all the fancy overhead, and didn't want UPNP, and did want to have more control over my system, so now I have a self-written and easily customisable and very simple menu system to browse my NAS that calls OMXPlayer in the background.


I'll try to get around to checking out the OMXPlayer code eventually. I may just modify it to correctly display when there are two subtitles at the same time.


--------------------------------------------
On Mon, 7/12/15, torarin <notifications@github.com> wrote:

 Subject: Re: [omxplayer] SubStationAudio (SSA) subtitles not working? (#402)
 To: "popcornmix/omxplayer" <omxplayer@noreply.github.com>
 Cc: "JontomXire" <JontomXire@yahoo.co.uk>
 Date: Monday, 7 December, 2015, 21:18
 
 Omxplayer attempts to convert
 embedded SSA subtitles to plain text and display them. It
 does not support reading SSA files.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by JontomXire** [comment]
I just tried to play back a file I have watched before, which on inspection contains SSA subtitles. The subtitles definitely worked, without any question, when I last played it a year or two ago. They don't work now.

Something has changed to break SSA subtitles. Between kids, refitting the bath in the bathroom to cure a damp problem, and all sorts of other stuff I need to do in my "free" time, I don't really have time to look at this right now in depth. Does anyone have any idea of any recent changes that might have caused this to break?

**Comment by jehutting** [comment]
As far as I know there are no changes made. Tested some subtitled movies; they all shows the subtitles correct. Sample available?

**Comment by JontomXire** [comment]
I have a sample: https://www.dropbox.com/s/ehrq9z2a3privco/test.mkv.gz?dl=0

I tested it and the subtitles play back fine on VLC, and it's from a file I know used to work played back via OMXPlayer on my RPi, but when I tested just now it didn't show subtitles on playback.

**Comment by jehutting** [comment]
`mediainfo ` of the file shows

> Text
ID                                       : 3
**Format                                   : ASS**
**Codec ID                                 : S_TEXT/ASS**
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Title                                    : Styled .ass
Language                                 : English
Default                                  : Yes
Forced                                   : No

The subtitle Text Format ASS (Codec ID S_TEXT/ASS) is NOT supported by omxplayer. See https://github.com/popcornmix/omxplayer/issues/289#issuecomment-942524

If you have found an omxplayer which does...that  would be interesting!

**Comment by JontomXire** [comment]
Well, the OMXPlayer version I was using a couple of years ago, which I was using when I watched that series originally, did support it.

As I have said several times already.

Neither my wife nor I speak Japanese, but we really did watch Soul Eater, and understand it, but we only have the subtitle version available, and that exact version from which I made that sample.

I vaguely remember that that was the series that made me make some adjustments a while back to fix up subtitle positioning. You can see my commits way back in 2013/2014 for fixing that. I am fairly sure I pushed them up and they were accepted.

Having looked at the git log, I suspect that this (https://github.com/popcornmix/omxplayer/commit/42d0e2622e59404c004a2bf144a387a6c4b35d3a) commit is the most likely suspect for removing the support, based on the timestamps on my OMXPlayer files and commits and the timestamps on the movie files.

I suspect that you, like me, think that adding functionality can only be a good thing, and removing perfectly good working functionality can only be a bad thing. It would be nice to get OMXPlayer to support this again.


I just checked the git log on this repo and I cannot find my changes for fixing subtitle repositioning. Perhaps they were never accepted. Which would be a bummer because I deleted my original fork of this repo, and while I have a backup of my local copy of my repo, I deleted a couple of branches (one by accident while distracted by a kid) and don't have a backup. However I am sure that commit was accepted.

Is there an easier way to search the git log for this repo? Maybe I could pinpoint the exact version that actually supported these subtitles that way.

**Comment by jehutting** [comment]
AFAIK omxplayer has only support for SSA, and not for ASS.

Using - sorry don't know how to bypass the per-page view, so I redirect the output to a file- `git log >file` and searching in that file for ASS gives no matches. A search on your name gives some hits, but not in relation to subtitles.

The logging goes way back to Huceke initial import.

So, I am afraid that support for ASS has to be done again / restored.

Please, correct me if I'm wrong!

**Comment by torarin** [comment]
It seems the codec id for SSA subtitles has changed from AV_CODEC_ID_SSA to AV_CODEC_ID_ASS in FFmpeg (See https://github.com/FFmpeg/FFmpeg/commit/7c1a002c78f15470f76d5c03e619b954d1a22839).

So quite possibly this issue could be fixed by updating those names in OMXPlayerSubtitles.cpp and OMXOverlayCodecText.cpp.

**Comment by JontomXire** [comment]
Awesome work, Torarin.

I'm still trying to get OMXPlayer to build (I had some compile errors I haven't had time to look at). Once I get it compiling I'll try this and see if it fixes the issue. I also need to try and track down the work I did previously for word-wrapping subtitles. I'm not sure why it never got pushed, but once I find it I'll generate a push request for that too.

This may take a while as I am in the middle of re-fitting the bath, plus 8 hours of programming at work all day takes its toll on my inclination to do more in the evening.

**Comment by jehutting** [comment]
@torarin if I understand it correct, detecting AV_CODEC_ID_ASS **or** AV_CODEC_ID_SSA, the decoding follows the same (SSA current) implementation? So it is just a matter of **adding** AV_CODEC_ID_ASS in forementioned files?

**Comment by torarin** [comment]
@jehutting Yes, that is my understanding from the FFmpeg notes. It looks like the latest FFmpeg code will never give us an AV_CODEC_ID_SSA, but checking for `AV_CODEC_ID_SSA || AV_CODEC_ID_ASS` should be fine.

**Comment by popcornmix** [comment]
I'm happy to change to ``AV_CODEC_ID_SSA || AV_CODEC_ID_ASS `` if someone can confirm it makes a positive difference.

**Comment by jehutting** [comment]
Yes it works...
```
diff --git a/OMXOverlayCodecText.cpp b/OMXOverlayCodecText.cpp
index dc49de2..1b12461 100644
--- a/OMXOverlayCodecText.cpp
+++ b/OMXOverlayCodecText.cpp
@@ -41,8 +41,11 @@ COMXOverlayCodecText::~COMXOverlayCodecText()
 
 bool COMXOverlayCodecText::Open(COMXStreamInfo &hints)
 {
-  m_bIsSSA = (hints.codec == AV_CODEC_ID_SSA);
-  if(hints.codec == AV_CODEC_ID_SUBRIP || hints.codec == AV_CODEC_ID_SSA)
+  m_bIsSSA = hints.codec == AV_CODEC_ID_SSA || hints.codec == AV_CODEC_ID_ASS;
+  /* 20160205 OMXPlayerSubtitles doesn't use the return value */
+  if(hints.codec == AV_CODEC_ID_SUBRIP || 
+     hints.codec == AV_CODEC_ID_SSA ||
+     hints.codec == AV_CODEC_ID_ASS)
     return true;
   return false;
 }
@@ -58,7 +61,6 @@ int COMXOverlayCodecText::Decode(BYTE* data, int size, double pts, double durati
 {
   if(m_pOverlay)
     delete m_pOverlay;
-  m_pOverlay = NULL;
 
   m_pOverlay = new COMXOverlayText();
   m_pOverlay->iPTSStartTime = 0;
@@ -72,8 +74,8 @@ int COMXOverlayCodecText::Decode(BYTE* data, int size, double pts, double durati
 
   if (m_bIsSSA)
   {
-    // currently just skip the prefixed ssa fields (8 (9?) fields)
-    int nFieldCount = 9;
+    // currently just skip the prefixed ssa/ass fields (8 fields)
+    int nFieldCount = 8;
     while (nFieldCount > 0 && start < end)
     {
       if (*start == ',')
diff --git a/OMXPlayerSubtitles.cpp b/OMXPlayerSubtitles.cpp
index 539d6ef..8b8238c 100644
--- a/OMXPlayerSubtitles.cpp
+++ b/OMXPlayerSubtitles.cpp
@@ -429,17 +429,19 @@ vector<string> OMXPlayerSubtitles::GetTextLines(OMXPacket *pkt)
   vector<string> text_lines;
 
   auto e = ((COMXOverlayText*) overlay)->m_pHead;
-  if(e && e->IsElementType(COMXOverlayText::ELEMENT_TYPE_TEXT))
+  while(e && e->IsElementType(COMXOverlayText::ELEMENT_TYPE_TEXT))
   {
-    split(text_lines,
+    std::vector<std::string> lines;
+    boost::split(lines,
           ((COMXOverlayText::CElementText*) e)->m_text,
-          is_any_of("\r\n"),
-          token_compress_on);
+          boost::algorithm::is_any_of("\r\n"),
+          boost::algorithm::token_compress_on);
+    text_lines.insert(text_lines.end(), lines.begin(), lines.end());
+    e = e->pNext;
   }
 
   return text_lines;
 }
-
 bool OMXPlayerSubtitles::AddPacket(OMXPacket *pkt, size_t stream_index) BOOST_NOEXCEPT
 {
   assert(m_open);
@@ -454,7 +456,8 @@ bool OMXPlayerSubtitles::AddPacket(OMXPacket *pkt, size_t stream_index) BOOST_NO
   };
 
   if(pkt->hints.codec != AV_CODEC_ID_SUBRIP && 
-     pkt->hints.codec != AV_CODEC_ID_SSA)
+     pkt->hints.codec != AV_CODEC_ID_SSA &&
+     pkt->hints.codec != AV_CODEC_ID_ASS)
   {
     return true;
   }
diff --git a/OMXSubtitleTagSami.cpp b/OMXSubtitleTagSami.cpp
index e8e51a6..613aceb 100644
--- a/OMXSubtitleTagSami.cpp
+++ b/OMXSubtitleTagSami.cpp
@@ -200,8 +200,12 @@ void COMXSubtitleTagSami::ConvertLine(COMXOverlayText* pOverlay, const char* lin
   boost::algorithm::replace_all(strUTF8, "\\n", "\n");
   boost::algorithm::replace_all(strUTF8, "\\N", "\n");
 
-  // add a new text element to our container
-  pOverlay->AddElement(new COMXOverlayText::CElementText(strUTF8.c_str()));
+  // don't add an empty line
+  if(strUTF8 != "\n")
+  {
+    // add a new text element to our container
+    pOverlay->AddElement(new COMXOverlayText::CElementText(strUTF8.c_str()));
+  }
 }
 
 void COMXSubtitleTagSami::CloseTag(COMXOverlayText* pOverlay)
```
Thanks to all!

**Comment by popcornmix** [comment]
@torarin are you happy with the other changes in @jehutting 's patch?

**Comment by torarin** [comment]
Looks good! I don't know why the nFieldCount is changed to 8 or why we are skipping empty lines, but there may well be a good reason to do so.

**Comment by jehutting** [comment]
Well I needed to skip 8 fields before getting to the text
```
ffmpeg creates packet:
                                  x = Id
                                    x = Layer      
                                      |-----Style, Name, MarginL, MarginR, MarginV, Effect, Text---------->
COMXOverlayCodecText::Decode #A p=1,0,Soul basic,,0000,0000,0000,,The Technical School for Reaper Weapons Wielders.
                                   1 2          34    5    6    78 
COMXOverlayCodecText::Decode #B p=The Technical School for Reaper Weapons Wielders.
```
Besides JontomXire test.mkv I tested it with another movie and needed also to skip 8 fields.

My test movie has empty text lines between the top and the bottom subtitle line which causes the top subtitle line going partly outside the (defined) window.

**Comment by torarin** [comment]
If the blank lines are part of the layout of the subtitle, I don't think we should remove them. One can make room for more lines with the --lines option.

**Comment by jehutting** [comment]
Agree. It may be that my test video has these silly empty lines in between, which makes it unpleasant to read :-)

**Comment by popcornmix** [comment]
I've added the ASS support as that seems uncontroversial.
The layout/blank lines changes can be added later is the desired behaviour is agreed upon.

**Comment by JontomXire** [comment]
The fix as committed doesn't work. The change from 9 fields skipped to 8 is not present, and the change from an "if" statement to a "while" loop is missing.

I am going to test each of these changes individually to see what happens.

**Comment by JontomXire** [comment]
Switching 9 to 8 fields solves my issue. I don't seem to have a multi-line sample to test right now, but I vaguely remember a file which will do. i will try to hunt it down.

**Comment by JontomXire** [comment]
Switching the "if" statement to a while loop does not seem to make any difference.

**Comment by jehutting** [comment]
@JontomXire any progress on debugging your video not showing the multilines subtitle?
Otherwise If you have a sample available, I can have a look at it too.

**Comment by JontomXire** [comment]
Sorry for slow reply. Been doing a lot of DIY lately.

I tested with a multilines sample both with and without the change from an "if" to a "while" and they both worked fine. I'm fairly sure that the multi-line was from the original subtitle and not a result of my subtitle word-wrapping changes. Either way I am happy.

The only remaining issue, which is a whole different issue, is when there are two lots of subtitles at the same time. At the start of some Hunter X Hunter episodes they explain "Ren" etc. with a sort of "title" subtitle that lasts for the whole explanation and then a second set of subtitles with the explanation where there are multiple different subtitles in the explanation. Because the "title" subtitle occurs first, time-wise, it is displayed but the others are not. I got a similar effect on another series when there were overlapping subtitle sets.

If we can change the field count from 9 to 8 then the fix is good and we can close this issue.

**Comment by torarin** [comment]
Sounds like changing the field count is a good idea.

**Comment by popcornmix** [comment]
@torarin you mean:
```
   if (m_bIsSSA)
   {
-    // currently just skip the prefixed ssa fields (8 (9?) fields)
-    int nFieldCount = 9;
+    // currently just skip the prefixed ssa/ass fields (8 fields)
+    int nFieldCount = 8;
     while (nFieldCount > 0 && start < end)
```

**Comment by torarin** [comment]
@popcornmix Yes.

**Comment by popcornmix** [comment]
Thanks. It is done.
@jehutting @JontomXire all good now?

**Comment by jehutting** [comment]
It's OK for me. Thanks.

**Comment by JontomXire** [comment]
As before, with the field count change it is all good.
