### ISSUE TITLE
Feature request : support xdcam HD 422

### ISSUE THREAD

**Issue by madjarian** [popcornmix/omxplayer#405]
Hello,
On pi2 raspbian with mpeg2 license and ram for gpu to 256mb I tried to play
XDCAM-HD-422 video file

But this video didn't play correctly, there is a lot of colored macroblock and noise.
Only the audio is ok.

The file is a XDCAM HD-422@ 50 Mbits in mxf container. 
the video track is Mpeg2 422@50 Mbits 1080i 25 fps

I can provide sample if you wish

Thx

**Comment by popcornmix** [comment]
No the hardware doesn't support 422 (a broadcast rather than consumer standard). Not possible.
