### ISSUE TITLE
Can't play ISO files

### ISSUE THREAD

**Issue by wizkids** [popcornmix/omxplayer#408]
I'm not sure if this is intentional or not (I know Kodi can do it and I've also seen [this old issue](https://github.com/huceke/omxplayer/issues/40)), but I'm missing aa "official" statement on whether or not the standalone OMXPlayer is capable of this.

In any case, I'm using preinstalled Raspbian (jesse) on Raspberry Pi 2 (with MPEG-2 license) with pre-installed  OMXPlayer (using apt-get install I assume):

omxplayer - Commandline multimedia player for the Raspberry Pi
    Build date: Sat, 12 Sep 2015 00:49:19 +0000
    Version   : d99bd86 [master]

I'm playing ISO DVD rips with everything but main video + audio (AC3 or DTS) + 1/2 subtitle tracks removed.

CLI output:

    pi@SRS-PI-2 /media/pi/Popcorn Hour Data/Video/DVD ISO/[MOVIE] $ omxplayer -o hdmi [MOVIE].iso
    Video codec omx-mpeg2 width 720 height 576 profile 4 fps 25.000000
    Audio codec ac3 channels 6 samplerate 48000 bitspersample 16
    Subtitle count: 0, state: off, index: 1, delay: 0
    Seek to: 00:10:00
    V:PortSettingsChanged: 720x576@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.42 layer:0 alpha:255
    Stopped at: 00:10:00
    have a nice day ;)

Keyboard shortcuts seem to be working, but the HDMI output is just black screen.

The ISO plays fine (with subtitles) in VLC (on PC) and on my Popcorn Hour (from which the disk drive is taken).

If this is not a bug and there is no ISO support, by all means, close this issue - but please drop a comment saying that that's the case for other people looking for the same info.

If there is another standalone video player that can do this on the Raspberry Pi  (and as good/simple as OMXPlayer does it for H.264) that'd be great to know too.

**Comment by jehutting** [comment]
Seeing the Video/Audio message I was surprised that omxplayer was able to do so.
Maybe omxplayer is able to read it...

But looking at it...**omxplayer unfortunately can't!**

OMXReader uses FFmpeg av_read_frame() which returns -11 = AVERROR(EAGAIN).
The av_strerror() gives "Resource temporarily unavailable".

Even a looping until this av_read_frame() not returning this error gives a never ending loop.

What happens is that omxplayer interpretes all <0 values as an EOF. After this "EOF detecton" omxplayer waits until the playing is finished..but it hasn't even started it :-) So during this waiting nothing happens (the black screen; I don't get the 'Seek...' nor the 'have a nice day'). The fault handling isn't correct.

I believe Kodi or others use libdvdcss/libdvdnav/libdvdread/or-something-alike to handle the DVD iso?

No way to read ISO.

**Well, not necessarily true...**

A way to play the ISO is to mount it!
First create (only once) a mounting point 
> $ sudo mkdir /mnt/iso

Then mount it
> $ sudo mount /path/to/the/ISO /mnt/iso -o loop,ro

You now can look at /mnt/iso in the VIDEO_TS folder for the main VOB and play.
After playing just
> sudo umount /mnt/iso

Of course you need the MPEG license.

**Comment by wizkids** [comment]
Yeah, I did try the mounting solution (that's how I came upon https://github.com/popcornmix/omxplayer/issues/407), but because it needs a script to select/loop the correct VOB files and has a noticeable pause between each file I started looking for alternatives.

I ended up using Kodi as you suggested. If anyone else is looking for an alternative, I think that's a good one. It can be installed on Raspbian with apt-get or you can go with another OS with Kodi, such as OSMC (I wouldn't recommend OpenELEC, because it's underlying Linux kernel is very limited).

**Comment by popcornmix** [comment]
Yes, omxplayer uses ffmpeg for demuxing so supports what ffmpeg supports.
ffmpeg does not support ISO files. What you've noticed is it's probe function tries quite hard to identify video (and is often quite slow because of this). Basically it will blunder through the ISO file until by chance it happens on an m2ts stream and detects the video type. But it will soon hit the end of that file and find more unparsable data and fail.

There are no plans for proper ISO support in omxplayer. The options are to use Kodi which fully supports ISO. Or to mount the ISO and play the m2ts files manually (or through a wrapper script/app).
