### ISSUE TITLE
omxplayer --win not work

### ISSUE THREAD

**Issue by PaoloBasso** [popcornmix/omxplayer#41]
The parameter --win "x1 y1 x2 y2"       for Set position of video window not work ... since the version "omxplayer_0.2.6~git20130427~fcfb7911_armhf.deb" it work

Thanks for your attention

**Comment by Ruffio** [comment]
@popcornmix, if it is fixed this issue should be closed...

**Comment by PaoloBasso** [comment]
Thanks 
for your attention!!!! 

----- Messaggio originale -----

Da: "Rasmus Christiansen" <notifications@github.com> 
A: "popcornmix/omxplayer" <omxplayer@noreply.github.com> 
Cc: "PaoloBasso" <basso.paolo@gmail.com> 
Inviato: Martedì, 9 giugno 2015 9:24:59 
Oggetto: Re: [omxplayer] omxplayer --win not work (#41) 


@popcornmix , if it is fixed this issue should be closed...
