### ISSUE TITLE
rtmp stream bug?

### ISSUE THREAD

**Issue by hanyuwei70** [popcornmix/omxplayer#410]
When I am testing omxplayer on rpi, I found that there is a chance which omxplayer can't get video stream in rtmp:// and seconds later it says "Have a nice day". So is it a bug or the problem of the configuration of rtmp server?

**Comment by jehutting** [comment]
Same as #361?
Try running omxplayer with the -g (--genlog) option and have a look in the created logging file *omxplayer.log*.

**Comment by jehutting** [comment]
@hanyuwei70 ...and how about this one? What is the current status of this issue?

**Comment by hanyuwei70** [comment]
I am not working on omxplayer now...
