### ISSUE TITLE
Different Return Code When User Exits

### ISSUE THREAD

**Issue by pafera** [popcornmix/omxplayer#413]
Hey, guys, and thanks for the excellent work on omxplayer.

I'm using omxplayer to implement playback function while providing dual interfaces where the Pi can be controlled by from a web interface and from the keyboard at the same time. I've implemented playlist functionality, but my problem is that since omxplayer does not implement playlists, I have no indication if the player exited due to playback being finished or if the user quits the video from the keyboard. If playback is finished, then I can start playing the next file in the playlist. If the user quits, then I want to stop playback entirely and not play the next file.

Could you possibly change the end of main() to

  // normal exit status on user quit or playback end
  if (m_send_eos)
    return 0;

  if (m_stop)
    return 2;

That way, I can check for a return code of 2 and quit playback. I have no problems compiling my own version, but it would be nice if I could take care of this upstream.

**Comment by popcornmix** [comment]
Seems okay to me. Can we leave this for a little while to give anyone a chance to object? (e.g. someone already making use of return codes).
Ping this in about a week and if no objections I'll add it.

**Comment by jehutting** [comment]
Value 2 has already a special meaning when using bash scripting. Seems also that sysexits.h values are used.
See [Exit Codes With Special Meanings](http://tldp.org/LDP/abs/html/exitcodes.htm) or [one] (http://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux) of the many stackoverflow discussions found.

**Comment by pafera** [comment]
The actual value is not important as long as it's distinct to the condition where the user has quit. If there's an exit code that no one is using, then it's a viable option.

**Comment by pafera** [comment]
[pinging this thread to see if we can add user exit as exit code 3]

**Comment by jehutting** [comment]
@popcornmix seems @pafera modification (with exit code 3 ;-) to get done by a pull request is a little bit overkill?

**Comment by popcornmix** [comment]
This has been merged in #453
