### ISSUE TITLE
omxplayer exits at random with peerflix.

### ISSUE THREAD

**Issue by dennisdevulder** [popcornmix/omxplayer#415]
Hi guys,

I've been trying to tackle this problem for quite some time now and haven't found a solution so far.
I use peerflix to stream a torrent-file and select omxplayer to start when the data is coming in.

While viewing the movie at any random point (sometimes 10 minutes in other times 90 minutes) the video simply exits. I have a log on the latest occurence.

Heres the log:

DEBUG: Normal M:1219023987 (A:1219072000 V:1218759208) P:0 A:0.05 V:-0.26/T:0.20 (1,1,0,0) A:0% V:0% (0.01,4.02)
15:33:28 T:18446744072955107966   DEBUG: Normal M:1219044531 (A:1219072000 V:1218759208) P:0 A:0.03 V:-0.29/T:0.20 (1,1,0,0) A:0% V:0% (-0.02,4.02)
15:33:28 T:18446744072955128540   DEBUG: Normal M:1219065103 (A:1219072000 V:1218759208) P:0 A:0.01 V:-0.31/T:0.20 (1,1,0,0) A:0% V:0% (-0.04,4.02)
15:33:28 T:18446744072955139004    INFO: COMXAudio::IsEOS
15:33:28 T:18446744072955145821   DEBUG: OMXClock::OMXStop
15:33:28 T:18446744072955220661   DEBUG: OMXThread::Run - Exited thread with  id 1872753728
15:33:28 T:18446744072955249290   DEBUG: OMXThread::StopThread - Thread stopped
15:33:28 T:18446744072955249684   DEBUG: OMXThread::Run - Exited thread with  id 1881142336
15:33:28 T:18446744072955249954   DEBUG: OMXThread::StopThread - Thread stopped
15:33:28 T:18446744072955255096   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.video_scheduler handle 0x71b3f988
15:33:28 T:18446744072955262062   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.video_decode handle 0x71ba80b0
15:33:28 T:18446744072955262952   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.video_render handle 0x6f188ed8
15:33:28 T:18446744072955286133   DEBUG: OMXThread::Run - Exited thread with  id 1859122240
15:33:28 T:18446744072955286417   DEBUG: OMXThread::StopThread - Thread stopped
15:33:28 T:18446744072955287291   DEBUG: COMXCoreComponent::DecoderEventHandler - OMX.broadcom.audio_mixer Ignoring expected event: eEvent(0x1), nData1(0x8000101c), nData2(0x0), pEventData(0x(nil))
15:33:28 T:18446744072955346392   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.audio_decode handle 0x703648b8
15:33:28 T:18446744072955365884   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.audio_mixer handle 0x19e9d08
15:33:28 T:18446744072955366774   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.audio_render handle 0x19f2438
15:33:28 T:18446744072955378456   DEBUG: OMXThread::Run - Exited thread with  id 1916970048
15:33:28 T:18446744072955378682   DEBUG: OMXThread::StopThread - Thread stopped
15:33:29 T:18446744072955442814   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.clock handle 0x71bcfbc0

any ideas?

**Comment by popcornmix** [comment]
ffmpeg has reported end of stream.
Possibly a network issue, or possibly the server kicked you off, but I don't think the problem lies within omxplayer.

**Comment by Ruffio** [comment]
@dennisdevulder can this be closed?
