### ISSUE TITLE
Compile errors.

### ISSUE THREAD

**Issue by JontomXire** [popcornmix/omxplayer#421]
When I try to compile I get:

BitstreamConverter.cpp:587:19: error: ‘CODEC_ID_H264’ was not declared in this scope

Should it be AV_CODEC_ID_H264?

**Comment by JontomXire** [comment]
And then I get:

In file included from DllAvFormat.h:27:0,
                 from BitstreamConverter.h:27,
                 from BitstreamConverter.cpp:26:
DllAvCodec.h:79:64: error: ‘PixelFormat’ has not been declared
DllAvCodec.h:84:34: error: ‘PixelFormat’ has not been declared
DllAvCodec.h:101:51: error: ‘PixelFormat’ has not been declared
DllAvCodec.h:102:16: error: use of enum ‘PixelFormat’ without previous declaration
DllAvCodec.h:102:92: error: use of enum ‘PixelFormat’ without previous declaration


What I did was to do a fresh fork of this repo on Saturday or Sunday, and then clone it to my local machine. On my RPi I did an "apt-get upgrade" and then re-synced the rootfs to my local build machine. Finally I did "make ffmpeg" before "make".

Is there a problem with my environment somehow?

Is there a full list of dependencies somewhere? I installed the ones I had written down somewhere from years ago.

**Comment by JontomXire** [comment]
Having had a quick look, ffmpeg defines an AVPixelFormat type. Also I got the error:

DllAvCodec.h:165:82: error: ‘::avcodec_default_release_buffer’ has not been declared

And ffmpeg defines function avcodec_default_release_buffer2() nad has a few comments about avcodec_default_release_buffer(), so it looks like there is a compatability issue between OMXPlayer and the ffmpeg version.


I tried rebuilding ffmpeg and spotted the following error/warning in the process:

warning: Remote branch n2.8.1 not found in upstream origin, using HEAD instead


Any ideas?

**Comment by JontomXire** [comment]
It looks like n2.8.1 is a tag not a branch, and so the -b option doesn't work somehow.

I'm upgrading all the packages on my system, including git, so maybe that will fix it. Otherwise I found that the following worked:

git clone git://source.ffmpeg.org/ffmpeg ffmpeg -b release/2.8
cd ffmpeg; git reset --hard n2.8.1

I haven't got around to actually building omxplayer yet, but I feel confident I have the right version of ffmpeg, so I should be good.

**Comment by JontomXire** [comment]
A newer version of git did not help. "-b n2.8.1" still does not work. I guess it must have once?

**Comment by JontomXire** [comment]
Now I am getting:

ffmpeg_compiled/usr/local/lib//libavcodec.so: undefined reference to `_dl_hwcap'
collect2: error: ld returned 1 exit status

Which according to the internet may be due to unresolved symbolic links in my local copy of the rootfs. I'm too tired to debug this further, but I would appreciate any advice that anyone may offer.

**Comment by JontomXire** [comment]
I should have gone to bed hours ago.

It looks like this issue is because when building libavcodec.so it is set to link statically to libc, but ffmpeg links dynamically to libc. I say this because libc.a contains this symbol, but libc.so does not.

However I am now so tired and mentally fatigued that I can barely type straight and I am surprised that my brains haven't started dribbling out of my ears.

I really need help fixing this. I seem to be dealing with issues like this every time I try to build OMXPlayer from scratch. It would be so nice if it all just worked.

**Comment by popcornmix** [comment]
I had a problem with _dl_hwcap years ago. I had to remove /usr/lib/libm.a
(remove libc.a too if you find one). Not sure what caused it. Haven't seen the issue since.

**Comment by popcornmix** [comment]
CODEC_ID has been deprecated for AV_CODEC_ID for a while, but it still works for me (CODEC_ID_H264 is defined in ffmpeg/libavcodec/old_codec_ids.h).
But it will stop working at some point so I've added a commit to switch to AV_CODEC_ID

**Comment by JontomXire** [comment]
Thanks for the help. I'll probably be too busy plumbing the new bath and spending time with the wife to do over tonight, but I'll give it a go as soon as possible.

You also need to fix the checkout of the ffmpeg code. As I reported above the CODEC_ID_H264 issue, and all following issues, are because the git command to clone branch n2.8.1 failed because that is actually a tag not a branch, so I ended up with HEAD. The commands above fix this, but are much slower since I had to remove the "depth=1" option to make sure I got the tag.

**Comment by popcornmix** [comment]
I've tried:
``git clone git://source.ffmpeg.org/ffmpeg ffmpeg -b n2.8.1 --depth=1``
on both Ubuntu and Raspbian (Jessie) and in both cases I get a valid ffmpeg directory with the top commit listed as "Update for 2.8.1".

**Comment by popcornmix** [comment]
On raspbian I have:

```
$ git --version
git version 2.1.4
```
and Ubuntu:
```
$ git version
git version 2.5.0
```

**Comment by JontomXire** [comment]
It appears I have git version 1.7.9.5. I already tried to upgrade before and a repeat attempt gives me nothing new. I am using 3.8.0-44-generic #66~precise1-Ubuntu.

On the libm.a issue, when I remove libm.a I get lots of errors to the effect that functions like truncf() have been defined twice, once static, once non-static. When I investigated, I found that libm.a implements truncf(). However I cannot find a header file which defines it. Curiously, on the RPi, "man truncf" states that it is included in "math.h", yet a quick grep of that file proves that to be incorrect. A search of all header files under /usr doesn't find me the guilty culprit either.

So now I am very confused. Configuring ffmpeg without libm.a shows that truncf() is not implemented, but compiling ffmpeg is showing that we are finding truncf() in a system header file somewhere with a slightly different definition.

I am stymied :(

**Comment by JontomXire** [comment]
I upgraded to "Trusty Tahr" and now, many hours later, I have git version 1.9.1 :(

I'm told that I'm in a "detached HEAD" state, but I seem now to be able to checkout ffmpeg with the command in the Makefile.ffmpeg makefile.

Now I just need to sort out the compile/link errors.

Oh, that this was as easy as going to the supermarket to buy a loaf of bread.

**Comment by JontomXire** [comment]
I'm guessing that the duplicate function definitions of truncf() and friends are built into the cross compiler somehow. As such it is impossible to compile ffmpeg if you remove libm.a and libc.a.

I've been trying to figure out how to force omxplayer to statically link to libm.a, but i can't figure it out.

Any more ideas?

**Comment by JontomXire** [comment]
For anyone else who is having problems, this might help: http://stackoverflow.com/questions/13626726/an-error-building-qt-libraries-for-the-raspberry-pi

It's not helped me though - I've fixed a whole bunch of broken symlinks and it still doesn't work!

**Comment by JontomXire** [comment]
Please can someone help me!

I wrote a test program:

#include "libavcodec/avcodec.h"

int main(int argc, char **argv)
{
    (void)avcodec_close(NULL);

    return 0;
}


I then copied the contents of ffmpeg_compiled to the raspberry pi.
I then compiled my program with:

gcc -o test test.c -lavcodec -lswresample -lavutil

I got the same linking error. So it looks like I am missing a library somewhere. Or not linking a library that I need and don't have.

Please could someone who can successfully build omxplayer run this same experiment on their system. If the test program builds ok then please send me the output from running ldd on the output file.

Thanks in advance.

**Comment by JontomXire** [comment]
Never mind. I solved it finally. For reference, just add:

LDFLAGS+=$(SYSROOT)/usr/lib/arm-linux-gnueabihf/libc.a

to the makefile.
