### ISSUE TITLE
Change color of letterboxes when using --blank option

### ISSUE THREAD

**Issue by Niksko** [popcornmix/omxplayer#424]
Hi

Is it possible to change the color of the black letterboxes that appear when the --blank option is enabled?

**Comment by jehutting** [comment]
Hi, can you clarify what you mean with 'black letterboxes'? And do they only appear with the --blank option?

**Comment by obskyr** [comment]
I was just thinking of asking for / implementing this feature, and lo and behld, someone had already asked just 4 days prior. But then closed it today? Huh?

**Comment by jehutting** [comment]
Yes, strange enough he did, even without telling what he wanted or no longer wants... :-)

**Comment by obskyr** [comment]
If I ever manage to get omxplayer to compile (loootsa trouble, probably
going to have to try cross-compiling) I might take a shot at it. It's a
feature I feel like I kinda want.

**Comment by popcornmix** [comment]
What colour do you want the letterbox?

**Comment by obskyr** [comment]
I'd like to be able to set it to any color. I figure I'll change `VC_IMAGE_TYPE_T type = VC_IMAGE_RGB565;` in `omxplayer.cpp` to `VC_IMAGE_TYPE_T type = VC_IMAGE_RGBA32;` (man, there was really *no* documentation at all for dispmanx...) and do some parsing on an optional hex-color argument to `--blank`.

...If I ever do get it to compile, that is.

**Comment by jehutting** [comment]
Sounds to me that you are trying to do something like pull-request #376.

**Comment by obskyr** [comment]
Yeah, basically that, actually. The way I was thinking, though, it'd be 1)
an extension of `--blank` in the form of an optional argument, and 2) using
an RGBA hex code for precise control of the color. The default, if
`--blank` was present without argument, would be black. This way, there's
no extra complexity in the form of a new option. And you still get the
ability to do things like setting a white background for bright video.

**Comment by Niksko** [comment]
Hey. Sorry for closing this without explanation. I wanted it basically just to add a little customizability to a video player applet I'm working on. The videos will be displayed on large TV screens, and I thought it would just be nice aesthetically to be able to select a background color.

I found a hacky method of getting what I wanted (which is why I closed it. Also because I felt like it almost certainly wasn't currently possible and didn't want to waste people's time), however funnily enough that method is no longer suitable, so it would actually be great if this could be implemented again.

**Comment by obskyr** [comment]
Well, you're in luck! As you've probably seen, I implemented this just yesterday in #428. Let's hope it gets merged!

In the meantime, it's possible to clone [the color-blank fork](https://github.com/obskyr/omxplayer/tree/color-blank) and compile that for use. Warning, however - getting omxplayer to compile is not for the faint of heart.

**Comment by popcornmix** [comment]
I've implemented a scheme to do this in https://github.com/popcornmix/omxplayer/commit/6c90c7503ba4658221774759edf7f2ae816711de

Basically the ``--blank``/``-b`` now can take an optional argument. It should be ``0xAARRGGBB`` for the alpha, red, green and blue components.
``0xff000000`` is opaque black (the same as without the argument).
``0xffff0000`` is opaque red
``0xff00ff00`` is opaque green
``0xff0000ff`` is opaque blue
``0x80ffffff`` is semi-transparent white

You can specify them with either ``--blank=0xff0000ff`` or ``-b0xff0000ff``

**Comment by obskyr** [comment]
Ah. I kept away from the optional argument thing due to space separation
being ambiguous, but I guess it works if you've got a `=` or just plain
nothing there.
