### ISSUE TITLE
Screen flash at end of video

### ISSUE THREAD

**Issue by Niksko** [popcornmix/omxplayer#425]
At the ends of some videos, there is a brief moment where the screen flashes white. Is this due to improperly encoded videos, or is this something that I can prevent with a particular option?

I'm building something that will be used to display promotional videos, so I'd rather avoid this particular graphical glitch.

**Comment by popcornmix** [comment]
I don't think that is normal. Does this [file](https://dl.dropboxusercontent.com/u/3669512/temp/h264_1080p_hp_4.1_10mbps_dts_unstyled_subs_monsters.mkv) for example?

**Comment by jehutting** [comment]
Related to #250?

**Comment by exidyboy** [comment]
I confirmed the white flash ( with MPEG-2 files at least) here https://github.com/popcornmix/omxplayer/issues/250#issuecomment-60534531 - that was with https://github.com/popcornmix/omxplayer/commit/6ee9a0a5488119786990b6f91990d59d6e35427c . I happen to still have that SD card (Oct 2014) and I could still see it - its very obvious. Moved the MPEG-2 file over to a card running version 4d8ffd1 [master] (Jul 2015) and it looped cleanly.

Need a test file and omxplayer version info from @Niksko

**Comment by jehutting** [comment]
Still see the white flash (after first run) when looping the synctest.mp4 file from issue nr. 250.
Also video starts seeking on 00:53:18 whereas it is a 60 seconds video.
Running latest omxplayer.

**Comment by Niksko** [comment]
Sorry guys. I haven't been in to work lately which is where the hardware is. As soon as I'm in next (probably Tuesday) I'll add the omxplayer version and I'll point you to videos that I have this issue on (and a video that I don't).

**Comment by exidyboy** [comment]
@jehutting I see a brief white flash running synctest.mp4 on d99bd86 [master] Sep 2015 on the first loop only as you say. This is the current version via apt-get-upgrade.
Also I agree it plays the whole file on first loop but subsequently I see the premature end which I thought had been fixed at https://github.com/popcornmix/omxplayer/commit/497a5c61141870e3cf007971e222b3a5213dd8ef

Not sure if the white flash and premature end have been re-introduced at some point or were just never fixed (with this file).

**Comment by jehutting** [comment]
@Niksko & @exidyboy Can you verify with the latest (fix/commit 2085f85) if the white flash issue is fixed?

**Comment by exidyboy** [comment]
To summarise: No Change on my Pi 1 Model B running omxplayer
Build date: Sat, 11 Jul 2015 00:44:53 +1000
        Version   : 4d8ffd1 [master]

In detail:
I started with:
pi@ashmore ~ $ vcgencmd version
Apr 21 2015 14:42:19 
Copyright (c) 2012 Broadcom
version 2d5ad04b63af4233440c3f7c8587108223201102 (clean) (release)

Performed:
pi@ashmore ~ $ sudo rpi-update

To get up to:
pi@ashmore ~ $ vcgencmd version
May  6 2016 13:53:23 
Copyright (c) 2012 Broadcom
version 0cc642d53eab041e67c8c373d989fef5847448f8 (clean) (release)

Behaviour with synctest.mp4 is identical. Namely brief flash of grey after first loop and subsequent loops terminating 7 seconds early with no flash and 'seamless' looping ie not even a dip to black.

Before the firmware update I was not seeing any flashes in MPEG-2 content which is the issue I reported here https://github.com/popcornmix/omxplayer/issues/250#issuecomment-60534531

Is it possible downgrade firmware to late 2014 version to try and reproduce the MPEG-2 flash (although so much has changed under the bonnet since them).

**Comment by jehutting** [comment]
@exidyboy Thanks for verifying it. I have to apologize as I should have realized that the latest popcornmix repository version is no(t) (longer next day?) available for all (through http://omxplayer.sconde.net/). I didn't requested to do a firmware update. Again, sorry.

BUT :) now I am a little bit confused: my RPI 1B is stuck (?) on
```
$ vcgencmd version
Jan 15 2016 17:21:55 
Copyright (c) 2012 Broadcom
version 50b1ff57f80db9c96b78757d2d2cfc226ed71f93 (clean) (release)
```

To be clear: with Apr 21 everything was OK. And with May 6 the white flash was re-introduced?
Can you post the output of ```omxplayer --version```?

You can downgrade but there has been so many changes...

**Comment by exidyboy** [comment]
Sorry. There has been so much discussion on the list about new firmware I assumed that was what I was testing. No there was no change in behaviour between the two firmware revisions. If you require further testing I will have to wait for sconde to catch up with 2085f85 as I don't have time to build from source at the moment.

**Comment by jehutting** [comment]
@exidyboy OK thanks for taking the time!

**Comment by Ruffio** [comment]
@Niksko & @exidyboy has this issue been resolved?

**Comment by exidyboy** [comment]
The problem is a gray flash after the first loop.
You don't see it on subsequent loops.
It exists in 6c90c75 (Friday 6 May)
This is the version you'd get if you did sudo apt-get install omxplayer today.
If you install the current build from sconde 66f9076 (July 13) it goes away.

**Comment by paolosabatino** [comment]
Just for future memories, if the video_fifo buffer size is less than 4.67 megabytes, it happens that with short videos you get the gray frame at the end. Apparently the broadcom omx video_decode component express this behavior if you give it less than 60 buffers of 80 kbytes each (that's where the 4.67 megabytes limit come from)

**Comment by jehutting** [comment]
@paolosabatino Thanks for sharing. Unexpectedly solution, but hey, if it works it works :-)

**Comment by OMID-313** [comment]
Dear @paolosabatino 
Thanks for suggesting to increase the video fifo size.
One question:
How should we determine the minimum video fifo size needed for an H-264 *.mp4 video file with `x` MB size and `y` seconds duration !?

**Comment by OMID-313** [comment]
Any suggestions @popcornmix and @jehutting about the minimum video fifo size ?

**Comment by paolosabatino** [comment]
@OMID-313 no real suggestion about the size of the buffer, I stopped doing experiments on such issue after being pleasant with 8MB of video fifo size, nonetheless I still experience the gray frame at the end with a couple of videos. I also never tried to study a possible correlation against video bitrate or duration

**Comment by OMID-313** [comment]
Thanks @paolosabatino for your reply.

Since my video files are 30 ~ 100 MB in size, I've preferred to set 200 MB fifo size :D
I know that 200 MB is too large, but I feel safe this way. And I haven't experienced any white flicker after doing so.

One more question:
Does setting fifo as large as 200 MB result in any issues later ?

**Comment by paolosabatino** [comment]
You should not experience any issue, but such buffer is way too big: in practice you are not streaming the video from the mass storage but are actually preloading it wholly in memory. 16 megabytes is fairly reasonable buffer to me, but it depends on the file bitrate and how much seconds of buffer you want.
