### ISSUE TITLE
OMXPlayer core dumps.

### ISSUE THREAD

**Issue by JontomXire** [popcornmix/omxplayer#427]
So having finally managed to build the latest and greatest version of OMXPlayer (bar a few commits), by forcibly linking it to the static version of libc, I run it on my Raspberry Pi only to find that it segfaults.

I used the native GDB but it gave me nothing useful at all.

Do I need to copy the corefile onto my development VM and use the cross-gdb?

**Comment by popcornmix** [comment]
You should be able to get a backtrace from running gdb on the pi itself.
Make sure your configured omxplayer with debug.
The makefile for omxplayer doesn't track changes to header files, so you may need to ``make clean`` after editing header files (and that includes reverting commits).

**Comment by JontomXire** [comment]
I used the native gdb, i.e. "the gdb on the pi itself" and it gave me nothing useful.

This usually means it has crashed inside some system library that doesn't have debug.

I suspect that manually specifying libm.a on the link line is causing the issue.

**Comment by JontomXire** [comment]
Linking the static version of libc.a was the cause. I managed to get OMXPlayer to link properly eventually, and it works fine now.

Now to go fix the subtitling issues.
