### ISSUE TITLE
Cross Compiling help

### ISSUE THREAD

**Issue by itsjasonc** [popcornmix/omxplayer#435]
I'm a beginner at using Makefiles, but I believe my problem is missing libraries either by installation or incorrectly configured Makefile.

From a stock image of Raspbian Jessie on a Raspberry Pi 2, I expanded the filesystem, updated, and upgraded. Then cloned the repo and ran the prepare-native-raspbian script.

From a stock image of Ubuntu 14.04 LTS 64-bit on a VM, I updated, upgraded and installed build-essential, git, rsync, gcc-multilib. In my home folder, I created a directory called rpi, cloned the raspberry pi tools into that folder. I appended 

> export PATH=$PATH:$HOME/rpi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin

 to my .bashrc  and was able to verify that I could access the compiler via 

> arm-linux-gnueabihf-gcc -v

Then I made a directory called rootfs inside of my rpi folder and copied files from the raspberry pi to my VM by running 

> rsync -rl --delete-after --safe-links pi@192.168.1.0:/{lib,usr,opt} $HOME/rpi/rootfs

Then I cloned the omxplayer repository and modified the Makefile.include like this

>FLOAT=hard
>
>BUILDROOT	:=/home/jason/rpi
>SDKSTAGE	:=$(BUILDROOT)
>TARGETFS	:=$(BUILDROOT)
>TOOLCHAIN	:=$(BUILDROOT)/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
>HOST		:=arm-linux-gnueabihf
>SYSROOT		:=$(BUILDROOT)
>
>JOBS=7
>
>CFLAGS			:= -isystem$(PREFIX)/include
>CXXFLAGS		:= $(CFLAGS)
>CPPFLAGS		:= $(CFLAGS)
>LDFLAGS			:= -L$(BUILDROOT)/lib
>LD					:= $(TOOLCHAIN)/$(HOST)-ld --sysroot=$(SYSROOT)
>CC					:= $(TOOLCHAIN)/$(HOST)-gcc --sysroot=$(SYSROOT)
>CXX         := $(TOOLCHAIN)/$(HOST)-g++ --sysroot=$(SYSROOT)
>OBJDUMP			:= $(TOOLCHAIN)/$(HOST)-objdump
>RANLIB			:= $(TOOLCHAIN)/$(HOST)-ranlib
>STRIP				:= $(TOOLCHAIN)/$(HOST)-strip
>AR 					:= $(TOOLCHAIN)/$(HOST)-ar
>CXXCP 			:= $(CXX) -E
>PATH 				:= $(PREFIX)/bin:$(BUILDROOT)/output/host/usr/bin:$(PATH)

>CFLAGS			+= -pipe -mfloat-abi=$(FLOAT) -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -g -mstructure-size-boundary=32 -mno-sched-prolog
>LDFLAGS			+= -L$(SDKSTAGE)/lib -L$(SDKSTAGE)/usr/lib -L$(SDKSTAGE)/opt/vc/lib/ -Lpcre/build
>INCLUDES		+= -isystem$(SDKSTAGE)/opt/vc/include -isystem$(SYSROOT)/usr/include -isystem$(SDKSTAGE)/opt/vc/include/interface/vcos/pthreads -Ipcre/build -Iboost-trunk -Ifreetype2/include

Then when I run 

> make ffmpeg

it successfully installs everything with the exception of a few warnings, but when I run

> make

I get this error:

>/home/jason/rpi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ --sysroot=/home/jason/rpi -isystem/include -pipe -mfloat-abi=hard -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -g -mstructure-size-boundary=32 -mno-sched-prolog -std=c++0x -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -DTARGET_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CMAKE_CONFIG -D__VIDEOCORE4__ -U_FORTIFY_SOURCE -Wall -DHAVE_OMXLIB -DUSE_EXTERNAL_FFMPEG  -DHAVE_LIBAVCODEC_AVCODEC_H -DHAVE_LIBAVUTIL_OPT_H -DHAVE_LIBAVUTIL_MEM_H -DHAVE_LIBAVUTIL_AVUTIL_H -DHAVE_LIBAVFORMAT_AVFORMAT_H -DHAVE_LIBAVFILTER_AVFILTER_H -DHAVE_LIBSWRESAMPLE_SWRESAMPLE_H -DOMX -DOMX_SKIP64BIT -ftree-vectorize -DUSE_EXTERNAL_OMX -DTARGET_RASPBERRY_PI -DUSE_EXTERNAL_LIBBCM_HOST -isystem/home/jason/rpi/opt/vc/include -isystem/home/jason/rpi/usr/include -isystem/home/jason/rpi/opt/vc/include/interface/vcos/pthreads  -Ipcre/build -Iboost-trunk -Ifreetype2/include -isystem./ -isystemlinux -Iffmpeg_compiled/usr/local/include/ -isystem /usr/include/dbus-1.0 -isystem /usr/lib/arm-linux-gnueabihf/dbus-1.0/include -c linux/RBP.cpp -o linux/RBP.o -Wno-deprecated-declarations
In file included from linux/RBP.h:45:0,
                 from linux/RBP.cpp:22:
./DllBCM.h:34:22: fatal error: bcm_host.h: No such file or directory
 #include <bcm_host.h>
                      ^
compilation terminated.
make: *** [linux/RBP.o] Error 1

Any idea how to continue?

**Comment by fcarlier** [comment]
Have you bcm_host.h file in your -isystem$(SDKSTAGE)/opt/vc/include (-isystem/home/jason/rpi/opt/vc/include) ??

Your rootfs is $HOME/rpi/rootfs and your $SDKSTAGE is /home/jason/rpi/

**Comment by itsjasonc** [comment]
Hi, thanks for replying. I modified my Makefile.include to look like this

> FLOAT=hard
RPI		:= /home/jason/rpi
BUILDROOT	:= /home/jason/omxplayer/build
ROOTFS		:= $(RPI)/rootfs
TOOLCHAIN	:=$(RPI)/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64
HOST		:= arm-linux-gnueabihf
CFLAGS		:= -I$(ROOTFS)/include
CXXFLAGS	:= $(CFLAGS)
CPPFLAGS	:= $(CFLAGS)
LDFLAGS		:= -L$(ROOTFS)/lib
LD		:= $(TOOLCHAIN)/bin/$(HOST)-ld
CC		:= $(TOOLCHAIN)/bin/$(HOST)-gcc
CXX       	:= $(TOOLCHAIN)/bin/$(HOST)-g++
OBJDUMP		:= $(TOOLCHAIN)/bin/$(HOST)-objdump
RANLIB		:= $(TOOLCHAIN)/bin/$(HOST)-ranlib
STRIP		:= $(TOOLCHAIN)/bin/$(HOST)-strip
AR		:= $(TOOLCHAIN)/bin/$(HOST)-ar
CXXCP 		:= $(CXX) -E
CFLAGS +=  -mfloat-abi=hard -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -O3 -mstructure-size-boundary=32 -mno-sched-prolog -march=armv6zk -I$(ROOTFS)/usr/include/dbus-1.0 -I$(ROOTFS)/usr/lib/x86_64-linux-gnu/dbus-1.0/include  
LDFLAGS		+= -L$(ROOTFS)/opt/vc/lib -L$(ROOTFS)/lib -L$(ROOTFS)/usr/lib -lfreetype
INCLUDES	+= -I$(ROOTFS)/opt/vc/include/interface/vcos/pthreads 			-I$(ROOTFS)/opt/vc/include 			-I$(ROOTFS)/opt/vc/include/interface/vmcs_host 			-I$(ROOTFS)/opt/vc/include/interface/vmcs_host/linux 			-I$(ROOTFS)/usr/lib/arm-linux-gnueabihf/dbus-1.0/include 			-I$(ROOTFS)/usr/include 			-I$(ROOTFS)/usr/include/freetype2

bcm_host.h is inside of my /home/jason/rpi/opt/vc/include directory.

Now I'm getting this error, I'm looking for the correct library to download at the moment.

>/home/jason/rpi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -I/home/jason/rpi/rootfs/include -mfloat-abi=hard -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -O3 -mstructure-size-boundary=32 -mno-sched-prolog -march=armv6zk -I/home/jason/rpi/rootfs/usr/include/dbus-1.0 -I/home/jason/rpi/rootfs/usr/lib/x86_64-linux-gnu/dbus-1.0/include   -std=c++0x -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -DTARGET_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CMAKE_CONFIG -D__VIDEOCORE4__ -U_FORTIFY_SOURCE -Wall -DHAVE_OMXLIB -DUSE_EXTERNAL_FFMPEG  -DHAVE_LIBAVCODEC_AVCODEC_H -DHAVE_LIBAVUTIL_OPT_H -DHAVE_LIBAVUTIL_MEM_H -DHAVE_LIBAVUTIL_AVUTIL_H -DHAVE_LIBAVFORMAT_AVFORMAT_H -DHAVE_LIBAVFILTER_AVFILTER_H -DHAVE_LIBSWRESAMPLE_SWRESAMPLE_H -DOMX -DOMX_SKIP64BIT -ftree-vectorize -DUSE_EXTERNAL_OMX -DTARGET_RASPBERRY_PI -DUSE_EXTERNAL_LIBBCM_HOST -I/home/jason/rpi/rootfs/opt/vc/include/interface/vcos/pthreads 			-I/home/jason/rpi/rootfs/opt/vc/include 			-I/home/jason/rpi/rootfs/opt/vc/include/interface/vmcs_host 			-I/home/jason/rpi/rootfs/opt/vc/include/interface/vmcs_host/linux 			-I/home/jason/rpi/rootfs/usr/lib/arm-linux-gnueabihf/dbus-1.0/include 			-I/home/jason/rpi/rootfs/usr/include 			-I/home/jason/rpi/rootfs/usr/include/freetype2 -isystem./ -isystemlinux -Iffmpeg_compiled/usr/local/include/ -isystem /usr/include/dbus-1.0 -isystem /usr/lib/arm-linux-gnueabihf/dbus-1.0/include -c linux/RBP.cpp -o linux/RBP.o -Wno-deprecated-declarations
In file included from /home/jason/rpi/rootfs/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:59:0,
                 from /home/jason/rpi/rootfs/opt/vc/include/interface/vcos/vcos.h:116,
                 from /home/jason/rpi/rootfs/opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /home/jason/rpi/rootfs/opt/vc/include/bcm_host.h:50,
                 from ./DllBCM.h:34,
                 from linux/RBP.h:45,
                 from linux/RBP.cpp:22:
/home/jason/rpi/rootfs/usr/include/stdlib.h:760:34: fatal error: bits/stdlib-bsearch.h: No such file or directory
 # include <bits/stdlib-bsearch.h>
                                  ^
compilation terminated.

**Comment by itsjasonc** [comment]
Updated my Makefile.include, I don't know if I'm making progress or going back a few steps.
>FLOAT=hard
RPI		:= /home/jason/rpi
BUILDROOT	:= /home/jason/omxplayer/build
ROOTFS		:= $(RPI)/rootfs
TOOLCHAIN	:= $(RPI)/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64
HOST		:= arm-linux-gnueabihf
CFLAGS		:= -I$(ROOTFS)/include
CXXFLAGS	:= $(CFLAGS)
CPPFLAGS	:= $(CFLAGS)
LDFLAGS		:= -L$(ROOTFS)/lib
LD		:= $(TOOLCHAIN)/bin/$(HOST)-ld --sysroot=$(ROOTFS)
CC		:= $(TOOLCHAIN)/bin/$(HOST)-gcc --sysroot=$(ROOTFS)
CXX       	:= $(TOOLCHAIN)/bin/$(HOST)-g++ --sysroot=$(ROOTFS)
OBJDUMP		:= $(TOOLCHAIN)/bin/$(HOST)-objdump
RANLIB		:= $(TOOLCHAIN)/bin/$(HOST)-ranlib
STRIP		:= $(TOOLCHAIN)/bin/$(HOST)-strip
AR		:= $(TOOLCHAIN)/bin/$(HOST)-ar
CXXCP 		:= $(CXX) -E
CFLAGS 		+= -pipe -mfloat-abi=$(FLOAT) -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -g -mstructure-size-boundary=32 -mno-sched-prolog
LDFLAGS		+= -L$(ROOTFS)/lib -L$(ROOTFS)/usr/lib -L$(ROOTFS)/opt/vc/lib -Lpcre/build 
INCLUDES	+= -I$(ROOTFS)/opt/vc/include -I$(ROOTFS)/usr/include -I$(ROOTFS)/opt/vc/include/interface/vcos/pthreads -Ipcre/build -Iboost-trunk -I$(ROOTFS)/usr/include/freetype2 -I$(ROOTFS)/opt/vc/include/interface/vmcs_host/linux

The new error is:
>In file included from OMXControl.cpp:6:0:
/usr/include/dbus-1.0/dbus/dbus.h:29:33: fatal error: dbus/dbus-arch-deps.h: No such file or directory
 #include <dbus/dbus-arch-deps.h>
                                 ^
compilation terminated.

In the original Makefile, dbus is included from my system. In Makefile.include, I even attempted to add the include directory for the dbus-arch-deps.h file but it still can't find it.

**Comment by itsjasonc** [comment]
Not sure if this will negatively impact it later but I looked into the directories and instead of pointing to /usr/lib/XXXX/dbus, I only included /usr/include/XXXX/dbus and then copy and pasted the dbus-arch-deps.h file from the lib folder to the include folder and it worked.

Here is my Makefile.include if anyone wants it.

>FLOAT=hard
RPI		:= /home/jason/rpi
BUILDROOT	:= /home/jason/omxplayer/build
ROOTFS		:= $(RPI)/rootfs
TOOLCHAIN	:= $(RPI)/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64
HOST		:= arm-linux-gnueabihf
CFLAGS		:= -I$(ROOTFS)/include
CXXFLAGS	:= $(CFLAGS)
CPPFLAGS	:= $(CFLAGS)
LDFLAGS		:= -L$(ROOTFS)/lib
LD		:= $(TOOLCHAIN)/bin/$(HOST)-ld --sysroot=$(ROOTFS)
CC		:= $(TOOLCHAIN)/bin/$(HOST)-gcc --sysroot=$(ROOTFS)
CXX       	:= $(TOOLCHAIN)/bin/$(HOST)-g++ --sysroot=$(ROOTFS)
OBJDUMP		:= $(TOOLCHAIN)/bin/$(HOST)-objdump
RANLIB		:= $(TOOLCHAIN)/bin/$(HOST)-ranlib
STRIP		:= $(TOOLCHAIN)/bin/$(HOST)-strip
AR		:= $(TOOLCHAIN)/bin/$(HOST)-ar
CXXCP 		:= $(CXX) -E
CFLAGS 		+= -pipe -mfloat-abi=$(FLOAT) -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -g -mstructure-size-boundary=32 -mno-sched-prolog
LDFLAGS		+= -L$(ROOTFS)/lib -L$(ROOTFS)/usr/lib -L$(ROOTFS)/opt/vc/lib -Lpcre/build 
INCLUDES	+= -I$(ROOTFS)/opt/vc/include -I$(ROOTFS)/usr/include -I$(ROOTFS)/opt/vc/include/interface/vcos/pthreads -Ipcre/build -Iboost-trunk -I$(ROOTFS)/usr/include/freetype2 -I$(ROOTFS)/opt/vc/include/interface/vmcs_host/linux -I$(ROOTFS)/usr/include/dbus-1.0 $(ROOTFS)/usr/lib/arm-linux-gnueabihf/dbus-1.0/include

I can now do make and make install BUT when rsyncing the omxplayer-dist folder to the Pi's root directory, changing directory to the bin folder and running omxplayer; the following error occurs:

>pi@raspberrypi:/omxplayer-dist/usr/bin $ ./omxplayer
./omxplayer.bin: error while loading shared libraries: libavutil.so.55: cannot open shared object file: No such file or directory

**Comment by fcarlier** [comment]
in your Makefile, with adaptation : 
"""
LDFLAGS+=-L./ -Lffmpeg_compiled/usr/local/lib/ -lc -lWFC -lGLESv2 -lEGL -lbcm_host -lopenmaxil -lfreetype -lz -lboost_regex
INCLUDES+=-I./ -Ilinux -Iffmpeg_compiled/usr/local/include/
"""

**Comment by Ruffio** [comment]
@itsjasonc do you still experience this issue? If not, please close this issue. Thanks.
