### ISSUE TITLE
Q: is there a way to programmatically control opacity ?

### ISSUE THREAD

**Issue by vitalik** [popcornmix/omxplayer#436]
Hi everyone,

I'm working on solution to make video fade-in at the end..

is there a way programmatically or on system level to control opacity of the video output ?

**Comment by popcornmix** [comment]
``./dbuscontrol.sh setalpha 128``

0 will be fully transparent video and 255 will be fully opaque video.

**Comment by jehutting** [comment]
@vitalik Does popcornmix's answer satifies your question?

**Comment by vitalik** [comment]
yes, works 100%, thanks!

**Comment by jehutting** [comment]
Good to hear you are good to go. Good luck with your project and post somewhere, somehow how your project is going. Maybe you can help/share thoughts with @ChrisLaurie in #366.
Can you close this issue? Thanks!
