### ISSUE TITLE
Feature Request, debian directory

### ISSUE THREAD

**Issue by TheSin-** [popcornmix/omxplayer#439]
You provide prebuilt deb files, would it be possible to include your debian directory in this repo?  I'd like to be able to start building armel, armhf and arm64 versions for pure debian installs.

**Comment by popcornmix** [comment]
We actually just use builds from http://omxplayer.sconde.net/
I believe he builds with https://github.com/skgsergio/rpi-buildenv

**Comment by TheSin-** [comment]
okay thanks I'll use that as a base then, though I'll expand on it.  Thanks for the help.
