### ISSUE TITLE
Problem playing some WMA files.

### ISSUE THREAD

**Issue by Psi-Star** [popcornmix/omxplayer#440]
With some WMA files Omxplayer exits with:
/usr/bin/omxplayer: line 67:  7195 Aborted LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"

The same files play correctly on Windows Media Player.  Omxplayer version is f544084.

**Comment by jehutting** [comment]
@Psi-Star I downloaded some wma files and they played all fine.
Could you run omxplayer with the **-g** option, which generates logging in omxplayer.log, and post (dropbox?) the file?

**Comment by Psi-Star** [comment]
I have created a log file and also included a sample of the WMA files that are causing the error.  Here is a Dropbox link:
https://dl.dropboxusercontent.com/u/104131380/omxplayer_error.zip

Any help would be most appreciated.  I would guess that about 10% of my WMA files are giving this error even though they play fine with Windows Media Player.

**Comment by jehutting** [comment]
Thanks for the logging and the wma file.

Whereas your omxplayer stops very soon (or almost immediately, does it even given some sound?), mine plays the file completely.

The logging shows a lot of
`ERROR: COMXAudioCodecOMX::GetData Unexpected change of size (32768->65536)`
Need a deeper looking at this :-)

I also see this error in (the logging) of the other wma files I downloaded.

**Comment by Psi-Star** [comment]
When the error occurs, it seems to occur randomly within the song.  It is just happenstance that the error occurs at the beginning of the file I posted.  If you think it will be helpful, I will post a few more examples later today.

**Comment by jehutting** [comment]
@Psi-Star Try to update your omxplayer version (from [sconde.net](http://omxplayer.sconde.net/)) 

On Jan 26 2016, omxplayer was update to fix issue #411, where omxplayer crashed at the beginning when playing mp3 files. Your version doesn't have this fix. 

I ran your file with the latest version.

Otherwise I will try to roll back to your version to see if that reproduce your problem.

**Comment by Psi-Star** [comment]
@jehutting Updating from the January build to the February build seems to have fixed the problem.  I have tried three different WMA files that previously generated an error including the one in the linked zip file.  The "Unexpected change of size" error is still in the log files but the files play fine.

Thank you very much for your help in this matter.  While I have many years of programming experience, I am just a three-week noob with the RPi, but having a great time relearning Unix and learning Python.

**Comment by jehutting** [comment]
@Psi-Star Thanks for reporting back that the update works for you!
Have a lot of fun with your RPI.
