### ISSUE TITLE
ALSA support (support for HiFi berry audio) when playing video (MP4) inside GPU

### ISSUE THREAD

**Issue by vdegrandpre** [popcornmix/omxplayer#442]
Hi,

I want to use the rPI's GPU to decode a mp4 video and to send included AAC audio to HiFiBerry DAC+ Light sound card (currently ALSA).

Searches pointed out that no support for ALSA exist in omxplayer but I want to get engaged to provide such functionality.

Can you tell what's the related effort and/or it ALSA support (or HiFiBerry support by other means) is already achieved ?

If not .. where should I start ?

N.B. Raspbian is the OS that is needed, XBMC/OpenELEC is NOT going to be used.

Very best,
Vincent de Grandpré

**Comment by popcornmix** [comment]
No. omxplayer is a purely gpu based player that doesn't support ALSA.
You may be better off with VLC which can support HW acceleration.
https://www.raspberrypi.org/forums/viewtopic.php?t=59814

**Comment by pylover** [comment]
So, i can not transfer the playing movie's audio to bluetooth ad2p and or usb sound card.

**Comment by popcornmix** [comment]
Not with omxplayer. It may be possible with VLC (or any video player that does use alsa).

**Comment by pylover** [comment]
Of-course, thanks very much for the link. vlc is good idea

**Comment by pylover** [comment]
I am thinking about adding this feature to the omxplayer, is it technically possible ? i am ready to fork it.

**Comment by popcornmix** [comment]
Not really possible.
The clock, video_decode,  video_schedule, video_render, audio_decode, audio_mixer, audio_render are tunnelled components that all run on the GPU. audio_render can only output to GPU controlled audio (i.e. hdmi or analogue headphone socket).
To output audio to ALSA you would want a completely different architecture.
Something very like VLC (which can support GPU video acceleration), which handles the clock scheduling and audio paths on the ARM.
Kodi is another option that supports ALSA.

**Comment by pylover** [comment]
Tanks a lot for the time.
On May 9, 2016 6:36 PM, popcornmix <notifications@github.com> wrote:Not really possible.
The clock, video_decode,  video_schedule, video_render, audio_decode, audio_mixer, audio_render are tunnelled components that all run on the GPU. audio_render can only output to GPU controlled audio (i.e. hdmi or analogue headphone socket).
To output audio to ALSA you would want a completely different architecture.
Something very like VLC (which can support GPU video acceleration), which handles the clock scheduling and audio paths on the ARM.
Kodi is another option that supports ALSA.

**Comment by chengjianwen** [comment]
The newest omxplayer has support output to also,
after install raspbian, man omxplayer, it shows:
-o  --adev  device          Audio out device      : e.g. hdmi/local/both/alsa[:device]
