### ISSUE TITLE
Get a flashing green screen with profile 77 [Video: h264 (Main)], when output to a 1k device or higher

### ISSUE THREAD

**Issue by tzraeq** [popcornmix/omxplayer#447]
When raspberry pi palying a mp4 output to a 1k device or higher resolution using hdmi, I got a flashing green screen. I checked the video's information, the profile is 77, "Video : h264 (Main)". Would you please help me to fix this problem?

**Comment by jehutting** [comment]
Have you set the 'gpu_mem' or 'gpu_mem_256' to 128 in the /boot/config.txt?

**Comment by popcornmix** [comment]
Could you start by posting [mediainfo](https://mediaarea.net/en/MediaInfo) of file?

**Comment by tzraeq** [comment]
It seems that default value of gpu_mem is 128.
And there is another circumstance.I am using omxd,this omxd can hold a playlist. It fork 2 omxplayer proc, and pause the second proc, then play the second  one at the first's ending, an so on.When the system boot up, I run a playlist using omxd, the first video on the list is very ok, but from the second one, any video with profile 77 played by omxplayer gives me a flashing green screen, and video with profile 100 is also ok.
I gauss there is some problom with the codec selection code,or pi's hardcodec problem.
Would you please check the code again?

**Comment by tzraeq** [comment]
The video plays very well,also with audio, but only the output device get a flashing green screen.
It happens when the output resolution is 1k or higher.
It is ok on the 720p device.

**Comment by popcornmix** [comment]
Could you start by posting [mediainfo](https://mediaarea.net/en/MediaInfo) of file?

**Comment by tzraeq** [comment]
@popcornmix I'm sorry, yesterday I did'n understand what the mediainfo is! 
The mediainfo is here, 
[2.mp4.txt](https://github.com/popcornmix/omxplayer/files/225109/2.mp4.txt)

Thank you very much!

**Comment by popcornmix** [comment]
The mediainfo details look okay.
If the file is run directly using omxplayer to a HDMI display that is, say, 1920x1080 then you see a flashing green screen, correct?

Can I get hold of the file? Looks to only be 10 seconds long and quite small. A site like google drive or dropbox can be used.

**Comment by tzraeq** [comment]
@popcornmix 
Hi, here is the google driver link.
https://drive.google.com/folderview?id=0B9cEHrCtBPRybTRlTWlNQ0lNd3M&usp=sharing.

Thank you very much!

**Comment by jehutting** [comment]
A 1k device is just a FULL HD tv with a 1920x1080 resolution.
@tzraeq I played your files and I don't see a green flash.
Probably similar to #425.
It could be an issue of omxd. Have you asked @subogero ([here](https://github.com/subogero/omxd)), the creator of omxd?

**Comment by jehutting** [comment]
@tzraeq @subogero Any update/progress/comment on '_it could be an omxd issue_'?

**Comment by jehutting** [comment]
@tzraeq I guess with the latest omxplayer version your issue is solved?

**Comment by Ruffio** [comment]
@jehutting I guess this can be closed...

**Comment by jehutting** [comment]
@Ruffio I agree. So @popcornmix can you close this one?

**Comment by Ruffio** [comment]
@popcornmix this should be closed due to possible resolve of issue/lack of response
