### ISSUE TITLE
loop on a specific files does not work properly

### ISSUE THREAD

**Issue by vitalik** [popcornmix/omxplayer#449]
Here is file example

https://dl.dropboxusercontent.com/u/1933399/out.mp4

if I run it like this:

`omxplayer  --no-keys --loop out.mp4`

if plays correctly first loop, but on 2nd loop it only goes up to 5th second and then seeks to 0

---
do you have any advise where to patch omxplayer  or maybe how to re-encode my video so it loops fine ?

**Comment by jehutting** [comment]
OMXPlayer has trouble playing short video's.
See [here](https://github.com/popcornmix/omxplayer/issues/316#issuecomment-74889984) for a workaround.

**Comment by Ruffio** [comment]
Is it possible to enable some debug logging that shows why this is the case? I don't see why omxplayer shouldn't support Short Videos.

**Comment by popcornmix** [comment]
I've pushed a fix for this issue. Please test.

**Comment by jehutting** [comment]
Hi @popcornmix 
That is a part of the solution :-) I spent also some time on the looping resulting in the PR.

I tested my fix and even [KenT2 1 sec movie](https://github.com/popcornmix/omxplayer/issues/124#issue-25058636) is looping correct! I also tried other known short videos (as the one the OP supplied): all OK to me.

The white flicker seen with [synctest.mp4](https://github.com/popcornmix/omxplayer/issues/250#issuecomment-55147315) is gone too.

The only.. trouble is exidiboy big_pi_streamclip.mp4 (huceke repository # 16). The first loop runs to 00:00:09.24 whereas the following ends up on 00:00:09.14. I don't know why (firmware issue? :)

**Comment by popcornmix** [comment]
I'm  still unable to reproduce the white flicker with synctest.mp4
Does that occur for you with latest code from this repo? And you don't see it with your PR?

out.mp4 is also behaving correctly with latest repo code.
1sec.mp4 is also behaving correctly with latest repo code.
big_pi_streamclip.mp4 is also behaving correctly (well, 9:14) with latest repo code.

Would be useful to confirm which files are still wrong with latest repo code, and what changes I should see with PR.

**Comment by vitalik** [comment]
@popcornmix, works perfect on all my "problematic" videos
Thanks!

**Comment by OMID-313** [comment]
@popcornmix ,
Is the fix to this bug included in the latest build at http://omxplayer.sconde.net/ !?

**Comment by popcornmix** [comment]
No, latest build is from 6th May.
The loop fix was on 9th May.
https://github.com/popcornmix/omxplayer/commits/master

**Comment by OMID-313** [comment]
Thanks @popcornmix for your comment.
Would you please release an updated deb. build including all the recent bug fixes?
