### ISSUE TITLE
Multiple (external) subtitles

### ISSUE THREAD

**Issue by basvdheijden** [popcornmix/omxplayer#45]
How do I open a file with multiple (external) subtitle streams?
Tried different builds, but this is always the result:

`omxplayer --subtitles 1.srt 2.srt test.mkv`

```
Subtitle count: 2, state:  on, index: 1, delay: 0
have a nice day ;)
```

If I load a single subtitle, everything works. Apparently it discovered my two subtitle files, and closes immediately after that?

My log file:

```
13:44:33 T:18446744072231426888   DEBUG: DllBcm: Using omx system library
13:44:33 T:18446744072231432295   DEBUG: DllOMX: Using omx system library
13:44:33 T:18446744072231437561   DEBUG: Previous line repeats 1 times.
13:44:33 T:18446744072231437561   DEBUG: DllAvFormat: Using libavformat system library
13:44:33 T:18446744072231439376   DEBUG: DllAvUtilBase: Using libavutil system library
13:44:33 T:18446744072231440661   DEBUG: DllAvCodec: Using libavcodec system library
13:44:33 T:18446744072231441571   DEBUG: DllAvFormat: Using libavformat system library
13:44:33 T:18446744072231559119   DEBUG: COMXCoreComponent::Initialize : OMX.broadcom.clock handle 0x1b2a7d0 dllopen : 1
13:44:33 T:18446744072231566801   DEBUG: COMXCoreComponent::Initialize OMX.broadcom.clock input port 80 output port 81
13:44:33 T:18446744072231643744   DEBUG: OMXThread::Create - Thread with id -1289739168 started
13:44:33 T:18446744072231654808   DEBUG: OMXClock::OMXSetSpeed(0.00) pause_resume:1
13:44:33 T:18446744072231660684   DEBUG: COMXPlayer::HandleMessages - player started RESET
13:44:33 T:18446744072231661730  NOTICE: OMXClock using video as reference
13:44:34 T:18446744072231663204   DEBUG: Normal M:0 (A:0 V:0) P:1 A:0.00 V:0.00/T:0.20 (0,0,1,1) A:0% V:0% (0.00,0.00)
13:44:34 T:18446744072231664617   DEBUG: Resume 0.00,0.00 (0,0,1,1) EOF:0 PKT:(nil)
13:44:34 T:18446744072231665640   DEBUG: OMXClock::OMXSetSpeed(1.00) pause_resume:1
13:44:34 T:18446744072231669547   DEBUG: Normal M:0 (A:0 V:0) P:0 A:0.00 V:0.00/T:0.20 (0,0,1,1) A:0% V:0% (0.00,0.00)
13:44:35 T:18446744072233106991   DEBUG: Previous line repeats 1451 times.
13:44:35 T:18446744072233106991   DEBUG: OMXClock::OMXStop
13:44:35 T:18446744072233128496   DEBUG: OMXThread::Run - Exited thread with  id -1289739168
13:44:35 T:18446744072233131620   DEBUG: OMXThread::StopThread - Thread stopped
13:44:35 T:18446744072233145281   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.clock handle 0x1b2a7d0 dllopen : 1
```

**Comment by exidyboy** [comment]
I'm working a solution that uses the DBUS interface command SelectSubtitles to change subtitle language playback without interrupting video playback.

See discussion of the DBUS subtitle commands in https://github.com/popcornmix/omxplayer/blob/master/README.md such as:
ListSubtitles
SelectSubtitles

and in the Key Bindings ie:
n           previous subtitle stream
m           next subtitle stream

Have I misunderstood what these DBUS commands are keyboard bindings are for ?

**Comment by exidyboy** [comment]
Update.
Q: Why does omxplayer have keyboard bindings and a DBUS interface to select between multiple subtitle streams if, as @torarin says above 'It's not currently possible to load more than one subtitle file...'.
A: Because at least one container format (.mkv) can have multiple .srt subtitle streams multiplexed __within a single file__ using (say) mkvmerge.

**Comment by CentaurWarchief** [comment]
@exidyboy any updates? can I today use multiple external subtitles?

**Comment by jehutting** [comment]
@CentaurWarchief omxplayer supports (with the --subtitles option) __only ONE external subtitle file__.

**Comment by exidyboy** [comment]
@CentaurWarchief There has been no work done on this. As @jehutting says you can only play one file although confusingly omxplayer will recognise an attempt to load multiple subtitle files from the command line ... and then exit :-)

The workaround is to use mkvmerge to mux the multiple .srt files and the video payload together ie mkvmerge -o MLA2012.mkv MLA2012_te_reo.srt MLA2012_english.srt MLA2012.mp4

The muxing can be done on the Pi if you install mkvmerge.
