### ISSUE TITLE
Question: OMXplayer and /boot/config.txt settings

### ISSUE THREAD

**Issue by fredericofs** [popcornmix/omxplayer#454]
Been using my raspberry to play videos 24hours a day / Seven Days a week, I found in the past: Tvservice droputs and audio dropouts. Reading OPENELEC forum posts about related issues, I ended up using:
`gpu_mem=256
dispmanx_offline=1
hvs_priority=0xffff
config_hdmi_boost=7
hdmi_clock_change_limit=20
`
I would like to know if I still need to use hvs_priority and hdmi_clock_change with lastest raspberry firmware and Omxplayer versions.

**Comment by popcornmix** [comment]
Are you using openelec or (command line) omxplayer?

**Comment by fredericofs** [comment]
Command line omxplayer, with fundation's raspbian lite (no desktop)

**Comment by popcornmix** [comment]
Definitely remove ``dispmanx_offline=1``. That will harm video playback.
``hvs_priority=0xffff`` won't be doing you any good (probably no harm either).
Most people don't need ``hdmi_clock_change_limit=20`` or ``config_hdmi_boost=7``, but they can help. I'd suggest removing them one at a time and see if any problems occur.

**Comment by Ruffio** [comment]
@fredericofs has your issue been resolved? Have you tried @popcornmix suggestions? If resolved, please close this issue or provide additional informations to highlight your issue. Thanks.
