### ISSUE TITLE
The problem of running two  omxplayer

### ISSUE THREAD

**Issue by piaoxueboy** [popcornmix/omxplayer#459]
Hi 

My environment 
PI 3
os:2016-03-18-raspbian-jessie.img

open the first one xterm windows
pi@raspberrypi:/opt $ omxplayer --win 0,0,400,300 1.mp4 --layer 0

open the second xterm windows
pi@raspberrypi:/opt $ omxplayer --win 300,0,700,300 2.mp4 --layer 1

    This time can hear the sound of the two video, then I press the P button in the first terminal, will find that did not hear the voice of the two video, later, and then press the P button in the first terminal, this time can hear the sound of the two video, but found that the second video voice in the broadcast, the image is pause a few seconds.

**Comment by jehutting** [comment]
There are issues when doing so. See #317.

By the way, omxplayer uses the layer-value+1 for the On-Screen-Display info (Pause/Play/Seek short messages).

**Comment by popcornmix** [comment]
Duplicate to #317. Closing.
