### ISSUE TITLE
Player crashes after continuous seeking

### ISSUE THREAD

**Issue by omninonsense** [popcornmix/omxplayer#462]
OMXPlayer crashes after seeking operations. It seems to be somewhat sporadic. Sometimes it crashes after a handful of seeks and sometimes it won't even crash after ~1000 seeks. I suppose, if you seek more frequently there's a higher chance this will occur. The error I get (and it floods the log at a fast pace until it eventually freezes or crashes) is this one:

~~~
COMXVideo::Decode - OMX_EmptyThisBuffer() failed with result(0x80001018)
~~~

Restarting the player works (most of the time, sometimes it does not), however the seeking is done via D-BUS from a different program, so this isn't very convenient. Furthermore, the seeking isn't that erratic, or frequent. It generally seeks every ~15 seconds, sometimes every 2-10 seconds.

Right now we grep the log files and restart the player when this happens, but I don't feel like that's the appropriate solution.

**Comment by popcornmix** [comment]
Can you update? ``sudo apt-get update && sudo apt-get dist-upgrade``.
There have been firmware and omxplayer updates recently.

**Comment by Ruffio** [comment]
@omninonsense has this issue been resolved? Please close this issue if it has been resolved or provide a detailed description of how to reproduce. Thanks.

**Comment by omninonsense** [comment]
Hello!

After I upgraded the firmware, the frequency in which this occurs is much much less, once every week, or less even. I am content with that, actually; it's easy to detect "externally" and fix the issue.

In hindsight, I don't think it's an omxplayer-specific issue anyway, so I'll close this issue; feel free to reopen if you want.
