### ISSUE TITLE
OMXPlayer wishes a nice day, but won't play videos

### ISSUE THREAD

**Issue by mensurdurakovic** [popcornmix/omxplayer#471]
Hi! Today I made clean installation of Raspbian Jessie image (2016-03-18), did sudo apt-get update and sudo rpi-update, but my omxplayer won't play any .mp4 video. It just displays message "have a nice day" and thats all. Here is my log file:

    16:43:52 T:18446744073544364278   DEBUG: DllBcm: Using omx system library
    16:43:52 T:18446744073544367606   DEBUG: DllOMX: Using omx system library
    16:43:52 T:18446744073544368268   DEBUG: DllAvFormat: Using libavformat system library
    16:43:52 T:18446744073544370731   DEBUG: DBus connection succeeded
    16:43:52 T:18446744073544371917   DEBUG: Keyboard: DBus connection succeeded
    16:43:52 T:18446744073544372099   DEBUG: OMXThread::Create - Thread with id 1900016688 started
    16:43:52 T:18446744073544372265   DEBUG: DllAvUtilBase: Using libavutil system library
    16:43:52 T:18446744073544372292   DEBUG: DllAvCodec: Using libavcodec system library
    16:43:52 T:18446744073544372314   DEBUG: DllAvFormat: Using libavformat system library
    16:43:52 T:18446744073544472669   DEBUG: OMXThread::Run - Exited thread with  id 1900016688
    16:43:52 T:18446744073544473000   DEBUG: OMXThread::StopThread - Thread stopped

Any help will be appreciated...

**Comment by popcornmix** [comment]
Can you post mediainfo of your file? (https://mediaarea.net/en/MediaInfo).

**Comment by mensurdurakovic** [comment]
It was my stupid mystake, somehow video file downloaded by my python script was always 0 bytes, and omxplayer couldn't play it. Delete this post if you can, OMXPlayer works perfecly with latest updates.
