### ISSUE TITLE
How to play /dev/video0

### ISSUE THREAD

**Issue by pete111** [popcornmix/omxplayer#472]
Hello, how can I play /dev/video0 with omxplayer on RPi?  
I saw it is not so easy (maybe pipe it first?). I didn't find any solution for this. Any idea?

**Comment by Ruffio** [comment]
@pete111 this is not a 'how to site' but only for reporting bugs. Please use sites like stackoverflow or https://www.raspberrypi.org/forums for these kinds of questions.

Please close this 'issue'. Thanks.
