### ISSUE TITLE
Green screen with a specific file

### ISSUE THREAD

**Issue by olegantonyan** [popcornmix/omxplayer#475]
Build date: Fri, 06 May 2016 14:07:54 +0000
Version : 6c90c75 [master]
Raspberry Pi 3, Raspbian 8

This video https://yadi.sk/i/TcL6P0Ilt6ztK cannot be played. Instead it shows green screen with flashing bar in the top left corner

What I tried so far: update to latest firmware (07.07.2016), add audio track to the video, increase gpu_mem as proposed here https://www.raspberrypi.org/forums/viewtopic.php?t=73769&p=529805 
Nothing helps.

This is a ffmpeg command I use to convert all videos: `ffmpeg -i src_file -vcodec libx264 -acodec aac -strict -2 dst_file`

**Comment by olegantonyan** [comment]
Solved. The problem was caused by format profile (https://github.com/raspberrypi/firmware/issues/340).
Correct ffmpeg cli: `ffmpeg -i src_file -vcodec libx264 -vprofile main -pix_fmt yuv420p -acodec aac -strict -2 dst_file` (https://ffmpeg.org/pipermail/ffmpeg-user/2014-December/024488.html)

**Comment by kristjanmik** [comment]
@olegantonyan which ffmpeg version are you using? The command is not working for me :/

**Comment by olegantonyan** [comment]
@kristjanmik ffmpeg 3.0.2
