### ISSUE TITLE
Feature Request: Ability to pipe video output to other programs

### ISSUE THREAD

**Issue by trs79** [popcornmix/omxplayer#476]
Specifically I'm needing to pass the video stream as it is being played to another program like ccextractor to get the caption information in real time (ccextractor can read data from stdin). I know stdout is already being used to display information about the video being played, but maybe there would be some other way?

**Comment by popcornmix** [comment]
What do you mean by the "video output"?
Are you talking about the decoded pixels, or just the video format information (i.e. codec, dimensions etc?) or something else?

**Comment by trs79** [comment]
Sorry for the confusion, I mean the video file bytes (not pixels, but just
the file data). So if omxplayer was reading a .mp4 file, then as is is
playing it would pipe the file data so that another program could read it
as if that program was reading directly from the file (so if ccextractor
was reading file data from stdin it would get the bytes from omxplayer).
This way if you pause in omxplayer, then ccextractor would also stop
getting file data and caption decoding would temporarily stop.

**Comment by popcornmix** [comment]
Sorry that feels like a very niche feature that would be quite hard to plumb in and control.
Feel free to fork omxplayer and add this, but I can't see this happening in this omxplayer tree.
