### ISSUE TITLE
Install omxplayer on armbian

### ISSUE THREAD

**Issue by ionciubotaru** [popcornmix/omxplayer#477]
Is it possible to install omxplayer on armbian Jessie (http://www.armbian.com/) ?
I tried to compile, but it fails. 
I cannot install apt-get install  libboost1.50-dev gcc-4.7 g++-4.7 because packages are missing.

Thank's a lot for the good program (omxplayer) you developed
Ion Ciubotaru

**Comment by popcornmix** [comment]
What board are you running on?
omxplayer will only work on a raspberry pi.

**Comment by fcarlier** [comment]
What is Armbian?

    Lightweight Debian and Ubuntu based distribution specialized for ARM developing boards,
    It has powerfull build and software development tools,
    A vibrant community.

Which chips are supported?

    Allwinner A10, A20, A31, H3
    Amlogic S805
    Amlogic S905
    Actionsemi S500
    Freescale / NXP iMx6
    Marvell Armada A380
    Samsung Exynos 5422

Which boards are supported?

Beelink X2, Orange Pi PC plus, Orange Pi Plus 2E, Orange Pi Lite, Roseapple Pi, NanoPi M1, pcDuino2, pcDuino3, Odroid C0/C1/C1+, Banana Pi M2+, Hummingboard 2, Odroid C2, Orange Pi 2, Orange Pi One, Orange Pi PC, Orange Pi Plus 1 & 2, Clearfog, Lemaker Guitar, Odroid XU4, Udoo Neo, Banana Pi M2, Orange Pi A31S, Cubieboard 1, Cubieboard 2, Hummingboard, Lamobo R1, Banana Pi PRO, Orange Pi mini A20, Olimex Lime A10, Olimex Micro, Olimex Lime 2, pcDuino3 nano, Banana Pi Plus A20, Udoo quad, Orange Pi A20, Olimex Lime 1, Banana Pi, Cubox-i, Cubietruck

check http://www.armbian.com/download/

No Raspberry Pi n ;)

**Comment by Ruffio** [comment]
@popcornmix as RPi isn't Official supporter by Armbian, it should be considered to close this issue
