### ISSUE TITLE
Audio and video go out of sync when playing rtmp stream with --live

### ISSUE THREAD

**Issue by davidv1992** [popcornmix/omxplayer#478]
In trying to stream from my laptop to a raspberry pi model 3 running raspbian with omxplayer version 6c90c75, the audio and video drift fairly rapidly (audio ~10 seconds behind over a running time of ~10 minutes) out of sync. 

I suspect the issue is with omxplayer because the ammount resets back when quiting omxplayer and starting it again.

For reference, the test stream is generated using
`ffmpeg -f alsa -i pulse -f x11grab -s 1920x1080 -r 30 -i :0.0+0,0 -vcodec libx264 -pix_fmt yuv420p -acodec aac -strict experimental -f flv rtmp://localhost/live/test1`
which streams to an nginx-rtmp server that does nothing more but forward it to any clients requesting it (no recoding on the server).

**Comment by davidv1992** [comment]
Had a small issue on the broadcasting side (the pulse frequency bug) which did make things worse, but having fixed that the issue does not go away, it is now on the order of half a second to a second per 10 minutes. Furthermore, some testing also shows that the problem exists when using a premade flv. 

Attached flv file demonstrates the issue (courtesy of  Project Peach, (c) copyright 2008, Blender Foundation / www.bigbuckbunny.org)
[test.flv.zip](https://github.com/popcornmix/omxplayer/files/368029/test.flv.zip)

I would love to do some debugging if needed

**Comment by jehutting** [comment]
@davidv1992 have you already solved it?
Otherwise have a look at #441.

**Comment by jehutting** [comment]
@davidv1992 did you had a look, or do you have any info?

**Comment by Ruffio** [comment]
@davidv1992 any updates?

**Comment by davidv1992** [comment]
Sorry, had some issues that have prevented me from doing much over the past few months, and this one slipped between the cracks. I'll take a look at the suggestions tomorrow evening (dont have access to the hardware this was on at the moment).

**Comment by davidv1992** [comment]
Okay, redid my experiments from back when, and on version 6c90c75 the apple sound was somewhere around .2 of a second late (noticable, but not big). Also did an upgrade of the entire system, which upgraded omxplayer to version dfea8c9, which seems to have fixed the issue.
