### ISSUE TITLE
Multiple instances limited to four?

### ISSUE THREAD

**Issue by GaryDUK** [popcornmix/omxplayer#479]
I used to be able to launch maximum 8 instances of omxplayer using --win to not overlap, now I can only launch 4.

I have tried with different GPU memory arrangements and in a VGA mode to no avail.

Has this been limited in a recent version?

**Comment by GaryDUK** [comment]
Have more testing I discovered that using audio output option "-o both" with more than 4 instances didn't work, it also did not throw any errors even the statistics where being updated just no onscreen video.

**Comment by popcornmix** [comment]
Yes, audioplus which handles resampling/mixing on GPU has a limit of 8 clients.
Using ``-o both`` will act as two clients.

**Comment by GaryDUK** [comment]
Ok thanks, closing.
