### ISSUE TITLE
omxplayer doesn't play video above 1920x1080

### ISSUE THREAD

**Issue by walkupup** [popcornmix/omxplayer#480]
I tried to play video of 2048x1536 size or higher, but failed. I found omxplayer just doesn't play video above 1920x1080. Is there anything I can do to deal with high resolution video ?

**Comment by popcornmix** [comment]
The hardware was designed for 1920x1080 maximum. Higher resolutions are not possible.

**Comment by pietrondo** [comment]
excuse, it can play 1920x1200? thx
