### ISSUE TITLE
--live & --user-agent not working together

### ISSUE THREAD

**Issue by Aiexis** [popcornmix/omxplayer#482]
Hi
when using --live parameter, --user-agent is not working any more (meaning I get <USERAGENT>Lavf/57.25.100</USERAGENT> on my webradio server instead of my personnal user agent).
However, is --live setting usefull for webradios ?
Thanks for all !

**Comment by falaca** [comment]
falaca/omxplayer@f161dfb should fix it, but I haven't tested it.

@popcornmix is this a bug or intended behaviour?

**Comment by jehutting** [comment]
@falaca Seems reasonable to me but why the ```!live``` for the ```av_dict_set(seekable)```?

**Comment by falaca** [comment]
@jehutting For a live stream, you shouldn't be able to seek forward or backward in time.

**Comment by jehutting** [comment]
Yes, but shouldn't that be the case for sftp, ftp and smb also?

**Comment by falaca** [comment]
Based on the original code it seems like it should be seekable over http/ftp/sftp, unless that's also a bug. My patch only fixes the bug reported in the OP.

That being said, I have no problem seeking in videos from samba shares when using VLC (I haven't tried with omxplayer). I haven't tried ftp/sftp though.

**Comment by popcornmix** [comment]
@falaca your patch looks correct - I have cherry-picked it. Thanks.

**Comment by Aiexis** [comment]
Thank you all ;)
However, can you explain what --live does exactly ? omxplayer works without this flag for webradios.

**Comment by popcornmix** [comment]
The server generating the live stream has a clock
The client (omxplayer) has a clock for playback.
These clocks are no synchronous. There will be a drift between the two (of the order of 100ppm or 0.01% for a typical crystal oscillator).
If clock on the pi is faster than the server you will eventually drain the buffer and have to pause to buffer.
If the clock on the pi is slower than the server the buffered data will keep increasing until the buffer is full and data will be dropped. 

The --live mode manages the buffered data by speeding up and slowing down playback (through resampling audio) to keep the amount of buffered data in range. This effectively symchronises the client and server clocks.

**Comment by Aiexis** [comment]
this is a crystal clear explanation, thank you!

**Comment by jehutting** [comment]
So this ```--live```has nothing to do with the stream being ```seekable```?

**Comment by popcornmix** [comment]
@jehutting the ``--live`` option isn't directly related to being seekable.
A non-live stream can be read faster than real-time. A live stream can't and requires clock management to avoid buffered data emptying (or over-filling).

``--live`` streams almost certainly are non-seekable (if you can seek forward then there is no reason why you shouldn't be able to read faster than real-time), but the ``--live`` option doesn't imply that.

**Comment by jehutting** [comment]
@Aiexis As far as I'm concerned, this issue can be closed.
