### ISSUE TITLE
Question: Does using dual audio output (--adev both) cause more load to the gpu/cpu?

### ISSUE THREAD

**Issue by fredericofs** [popcornmix/omxplayer#484]
Does using dual audio output (--adev both) cause more load to the gpu/cpu?
Also, can it cause more noise to the sound output? 

I am in doubt if my script for playing movies should go with --adev both option as default, or if I better leave a selector for hdmi vs. local.

Thank you!

**Comment by popcornmix** [comment]
Not much difference to arm cpu.
There is more work on GPU with "both"
Also the analogue audio quality is theoretically lower in "both" mode.
There is logic to keep the video and audio synchronised (through either adjusting clocks or resampling) but that only applies to a single audio stream. With "both" that will be hdmi and analogue will potentially duplicate or drop samples. I'm not sure it's actually audible, but it's something to consider.

So yes, I'd suggest giving an option for audio output.

**Comment by fredericofs** [comment]
Thank you!
