### ISSUE TITLE
Subtitle Render failed

### ISSUE THREAD

**Issue by Windywind** [popcornmix/omxplayer#487]
I played some a mkv with Chinese-simplified subtitles and a specific font, but always failed.

This happened on several of my movies. The console feedback sth. like posted below:

root@raspberrypi:/mnt/Trans/Star.Trek.Beyond.2016.1080p.WEB-DL.H264.AC3-EVO[SN]# omxplayer -r Star.Trek.Beyond.2016.1080p.WEB-DL.H264.AC3-EVO.mkv --subtitles Star.Trek.Beyond.2016.HDTS.HC.x264.AAC-双语.srt --font /usr/share/fonts/truetype/wqy/wqy-zenhei.ttc
Chapter : 0 Chapter 1 0.00
Chapter : 1 Chapter 2 505.00
Chapter : 2 Chapter 3 970.00
Chapter : 3 Chapter 4 1957.00
Chapter : 4 Chapter 5 2535.00
Chapter : 5 Chapter 6 3141.00
Chapter : 6 Chapter 7 3589.00
Chapter : 7 Chapter 8 4324.00
Chapter : 8 Chapter 9 4953.00
Chapter : 9 Chapter 10 5580.00
Chapter : 10 Chapter 11 6032.00
Chapter : 11 Chapter 12 6458.00
Chapter : 12 Chapter 13 6751.00
Chapter : 13 Chapter 14 6940.00
Output mode 32: 1920x1080@24 :20
ntsc_freq:1
Video codec omx-h264 width 1912 height 800 profile 100 fps 23.976025
Audio codec ac3 channels 6 samplerate 48000 bitspersample 16
Subtitle count: 1, state: on, index: 1, delay: 0
V:PortSettingsChanged: 1912x800@23.98 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
omxplayer.bin: SubtitleRenderer.cpp:154: SubtitleRenderer::load_glyph(SubtitleRenderer::InternalChar)::: Assertion `!vgGetError()' failed.
/usr/bin/omxplayer: line 67: 858 Aborted LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"

Anyone can help me?

Version info:

omxplayer - Commandline multimedia player for the Raspberry Pi
Build date: Fri, 06 May 2016 14:07:54 +0000
Version : 6c90c75 [master]
Repository: https://github.com/popcornmix/omxplayer.git

**Comment by jehutting** [comment]
I downloaded from somewhere the subtitle srt and from somewhere the font ttc.
Played them along with a Star Trek Into Darkness mkv (almost identical video and audio coded) without giving the fault. On my tv the first two subtitles are shown in chinese font. 
Tried it with latest repository omxplayer on a RPI 3B  jessie with uname'd 4.4.13-v7+ Jun 13 and boot confige'd gpu mem 256.

**Comment by Windywind** [comment]
My piece of Raspberry is a Pi Zero, with the same latest Raspbian. 

Sth. Else, I also got some audio decoding error, it just keep poping-up, and the movie won't be played, maybe I will post it up later.

**Comment by jehutting** [comment]
Do you mean (with an other movie so unrelated to above fault?) the audio and video stops and some time later continuous?
Do you get your movie from a mounted usb drive or wifi connection? Could it be that the data read is not fast enough causing omxplayer to buffer?

**Comment by Windywind** [comment]
Yeah, I am sorry, that's another fault. Potential reason you mentioned could be true. Thanks for your info.

But I am still wandering about the first fault I encountered with…

**Comment by jehutting** [comment]
Try to run the movie 
- without subtitle and without font
- with subtitle and without font.

If I run my mkv movie on a model B, I have a lot of artifacts, stuttering play, even kicks out my mounted network drive, etc. The RPI is running in turbo mode. I'm just questioning if the Zero has enough power do run the movie smoothly.

**Comment by torarin** [comment]
Apparently the OpenVG call vgGaussianBlur fails. I don't have a good explanation for that, perhaps a lack of GPU memory?

**Comment by jehutting** [comment]
I lowered my RPI 3B gpu_mem_1024 to 64, and to my surprised it played very well...
Used gpu memory can be checked with `vcgencmd get_mem gpu`.

**Comment by Windywind** [comment]
Without the subtitle, it plays well.

**Comment by Windywind** [comment]
My Pi Zero has a 64M GPU mem.

**Comment by jehutting** [comment]
As torarin suggested, try to increase the gpu memory to 128 or 256.
You can do this by setting ```gpu_mem=256``` in ```/boot/config.txt```.

**Comment by Windywind** [comment]
Both problems solved as after I increased the GPU memo to 128M, 

THX you guys. ;D
