### ISSUE TITLE
dbuscontrol status command returns error

### ISSUE THREAD

**Issue by cvcs1** [popcornmix/omxplayer#488]
Hello guys! I've been making a web app to control my raspberry pi / omxplayer using dbuscontrol.sh! Every command I've been able to try works so far except "status. When I do this command (no matter how its being done, CLI, PIPE or otherwise. I get this error:

`Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`

There doesn't seem to be any reason and I've poured over the script file and nothing is apparently wrong. Can anyone shed some light on this? I'm running Raspbian.

**Comment by jehutting** [comment]
Try to eliminate which part of status fails. The status -see dbuscontrol.sh- is formed by retrieving duration, position and playstatus. Comment out lines and see which one leads to the error.
Which version does omxplayer has (```omxplayer --version```), and are you using the dbuscontrol.sh from this repository?

**Comment by cvcs1** [comment]
`omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Fri, 06 May 2016 14:07:54 +0000
        Version   : 6c90c75 [master]
        Repository: https://github.com/popcornmix/omxplayer.git`

Yes I am!

**Comment by jehutting** [comment]
OK not the latest omxplayer version.... Try from [here](http://omxplayer.sconde.net/), also not the latest but newer than yours. _On 27 may, the improved DBus MPRIS2 interface was added; the old dbus interface is still supported and at least it works for me._
Can you post your dbuscontrol.sh status part only? Just to be sure what dbus commands you are actually using.
Did you tried to comment out parts of the status command?

**Comment by cvcs1** [comment]
`
status)
	duration=`dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:"org.mpris.MediaPlayer2.Player" string:"Duration"`
	[ $? -ne 0 ] && exit 1
	duration="$(awk '{print $2}' <<< "$duration")"

	position=`dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:"org.mpris.MediaPlayer2.Player" string:"Position"`
	[ $? -ne 0 ] && exit 1
	position="$(awk '{print $2}' <<< "$position")"

	playstatus=`dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:"org.mpris.MediaPlayer2.Player" string:"PlaybackStatus"`
	[ $? -ne 0 ] && exit 1
	playstatus="$(sed 's/^ *//;s/ *$//;' <<< "$playstatus")"

	paused="true"
	[ "$playstatus" == "Playing" ] && paused="false"
	echo "Duration: $duration"
	echo "Position: $position"
	echo "Paused: $paused"
	;;`

I have tried to comment out parts and nothing fixes it. 
Also - how do you recommend updating omxplayer? Tried and failed.
