### ISSUE TITLE
Does omxplayer have sth. like 'Formatted Subtitles' in VLC?

### ISSUE THREAD

**Issue by Windywind** [popcornmix/omxplayer#489]
Hi guys,

I was still having some problems with Chinese subtitles, until today, I was playing around with my Linux Mint, and found the same problem occurs in Mint. No matter I use VLC or the 'Videos' to play the file, with some subtitles. It was being like either you got the Chinese, or you got the English.

Then I googled, and, I found out I can un-tick the box of 'Formatted Subtitles', then I got everything.

![screenshot from 2016-10-12 23-25-45](https://cloud.githubusercontent.com/assets/9924858/19330038/d5aa7be4-90d3-11e6-9349-f70a073d196c.png)

I don't know if omxplayer has a function like this, or not.(If not, can we :D )

**Comment by jehutting** [comment]
> It was being like either you got the Chinese, or you got the English

So you have a video with the Chinese as well as the English subtitle **in** it (/embedded)? Or do you mean **external** subtitles?  OMXPlayer can only play one external subtitle at the time.

What does the 'Formatted Subtitles' do or doesn't do? Can't quickly determine what this option does in VLC.

**Comment by Windywind** [comment]
For the subtitles I used, it's a **external** one, and combined with both Chinese and English.

For the  'Formatted Subtitles', I don't know well either. But basically, I turn it off, and boom~~~ We got both languages.

**Comment by jehutting** [comment]
Never knew an external subtitle file can have multiple languages in it. Are you able to share one, or tell how/where to get one?

**Comment by Windywind** [comment]
[The.Infiltrator.2016.1080p.BluRay.x264-GECKOS.zip](https://github.com/popcornmix/omxplayer/files/531816/The.Infiltrator.2016.1080p.BluRay.x264-GECKOS.zip)

**Comment by jehutting** [comment]
Thanks that clears some things.

```
﻿2
00:00:01,300 --> 00:00:06,300
翻译

3
00:00:01,300 --> 00:00:06,300     <<<--- same time as [2] so not shown
Poppins

5
00:00:06,300 --> 00:00:12,300
翻译

6
00:00:06,300 --> 00:00:12,300      <<<--- same
Yatamisaki

8
00:00:12,300 --> 00:00:18,300
初校

9
00:00:12,300 --> 00:00:18,300      <<<--- same 
Yatamisaki

11
00:00:18,300 --> 00:00:24,300
特效

12
00:00:18,300 --> 00:00:24,300
烟斗

14
00:00:24,300 --> 00:00:30,300
压制

15
00:00:24,300 --> 00:00:30,300
雄超哥

17
00:00:30,300 --> 00:00:36,300
总监

18
00:00:30,300 --> 00:00:36,300
Yatamisaki

27
01:59:57,980 --> 02:00:07,980      <<<--- almost two hours later...
扫码关注翻托邦
字幕组微博，获
取更多影视资源
资讯

28
02:00:07,980 --> 02:00:17,980
翻托邦字幕组
长期招募英翻
和日翻及后期
详见微博置顶

29
00:01:17,740 --> 00:01:24,450      
 <<<--- and two hours later back to 2 minutes from start
...will not be shown as OMXPlayer simply skips it
as time has long went over two hours ...I think...
{\an8}十九世纪八十年代 麦德林卡特尔贩毒集团在一周之内
向美国走私了十五吨的可卡因 价值超过四亿美元

```

But still after changing these timing (just open file in an editor and change the time stamps) you will see that with 4 lines of subtitles the top line is cut off (window for the subtitle is too small).
```{\an8}``` is not handled by omxplayer.

**Comment by torarin** [comment]
Correct, omxplayer will assume the subtitles in the file are in chronological order. You can make room for four lines of text with the switch "--lines 4".

**Comment by Windywind** [comment]
alright, THX for your info.
Although, I still got some a feeling that I have encountered with problems in other conditions, maybe I will try more and tell you later.

**Comment by Ruffio** [comment]
@Windywind any update or can this issue be closed?

**Comment by Windywind** [comment]
OK, but if I found sth. else useful I may reopen it.
