### ISSUE TITLE
find out the name of the file omxplayer is currently playing

### ISSUE THREAD

**Issue by aristosv** [popcornmix/omxplayer#490]
I am trying to see the name of the file omxplayer is currently playing. So I did this.
```
curl -O https://raw.githubusercontent.com/popcornmix/omxplayer/master/dbuscontrol.sh
chmod +x dbuscontrol.sh
./dbuscontrol.sh getsource
```
But I get this message:
`Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`

How can I see (from the command line) the name of the file omxplayer is currently playing?
Thanks

**Comment by jehutting** [comment]
The ```getsource``` seems to work (at least for me :-).
Does ```pause``` (or an other command) work?

You could use the ```-I```(capital i) option. It dumps the ffmpeg info on the stderr output.

**Comment by aristosv** [comment]
all the other options have the exact same output.
Also, adding -I before or after the option, shows me all the options for correct usage. Like it doesn't accept the -I option.

**Comment by jehutting** [comment]
What is your version of omxplayer? (Use ```omxplayer -v```or ```omxplayer --version```).

**Comment by aristosv** [comment]
oh, sorry for the confusion. Omxplayer can play mp3 and mp4 files just fine. I just need to be able to see which file its currently playing in the background. This is why I wanted to use the "getsource" option.

```
root@Client003:/var/rpi/media# omxplayer -I Dua\ Lipa\ Be\ The\ One.mp3
[mp3 @ 0x1c13600] Skipping 0 bytes of junk at 574.
Input #0, mp3, from 'Dua Lipa Be The One.mp3':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2015-10-28 11:57:02
    encoder         : Lavf54.20.4
  Duration: 00:03:24.33, start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
Audio codec mp3 channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
have a nice day ;)
```

```
root@Client003:~# omxplayer -v
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Fri, 06 May 2016 14:07:54 +0000
        Version   : 6c90c75 [master]
        Repository: https://github.com/popcornmix/omxplayer.git
```

**Comment by jehutting** [comment]
The ```-I```option is an alternative way to get the source name.

Are you running on a Raspbian Wheezy/Jessie distribution?
You can get a newer omxplayer version from [omxplayer.sconde.net](http://omxplayer.sconde.net/)._(Contains a little fix on the D-Bus handling, but that probably doesn't solve your issue, but you can do anyway to be sure)_

Let's view the D-Bus connection. Can you do ```omxplayer -g file_to_play```? This generates an omxplayer.log (in the folder where you run omxplayer).

Within the first couple of lines there should be 
```
15:02:58 T:18446744071732615352   DEBUG: DBus connection succeeded
15:02:59 T:18446744071732673757   DEBUG: Keyboard: DBus connection succeeded
```

**Comment by aristosv** [comment]
```
root@Client003:/var/rpi/media# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
03:15:26 T:446469872   DEBUG: DllBcm: Using omx system library
03:15:26 T:446470812   DEBUG: DllOMX: Using omx system library
03:15:26 T:446471441   DEBUG: DllAvFormat: Using libavformat system library
03:15:26 T:446473698 WARNING: Failed to acquire D-Bus name 'org.mpris.MediaPlayer2.omxplayer'
03:15:26 T:446474124 WARNING: DBus connection failed, trying alternate
03:15:26 T:446476072   DEBUG: DBus connection succeeded
03:15:26 T:446477377   DEBUG: Keyboard: DBus connection succeeded
03:15:26 T:446477539   DEBUG: OMXThread::Create - Thread with id 1900016688 started
03:15:26 T:446477619   DEBUG: DllAvUtilBase: Using libavutil system library
```

**Comment by jehutting** [comment]
All looks OK to me. _(not sure about the acquire warning being normal, I have to check that tonight on my RPI.)_

Can you show me the exact command you use to run omxplayer?
And, can you also run omxplayer with the -g option, execute a(or several)  dbuscontrol.sh command(s), and post the omxplayer.log?

**Comment by aristosv** [comment]
This is the bash script for playing mp3 & mp4 files
```
# Import Variables
source "${BASH_SOURCE%/*}/variables"
media=$localmedia/*
count=0
IFS='
'
while true
 do
  for f in $(ls ${media} | sort -R)
  do
  printf "%3d> %s\n" "$count" "$f"
  /usr/bin/omxplayer "$f"
  count=$((count+1))
  done
done
```
And this is how I call it
`/path/to/scripts/omxplayer &`
For testing, I run this:
`omxplayer -g Veorra\ -\ Run.mp3`
And while the mp3 was playing I run these two commands:
```
root@Client003:/var/rpi/scripts# ./dbuscontrol.sh getsource
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

root@Client003:/var/rpi/scripts# ./dbuscontrol.sh status
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
And this was the output http://pastebin.com/YfcHVL1G

**Comment by jehutting** [comment]
The D-Bus message handling goes wrong:

```
16:13:45 T:18446744073610227976   DEBUG: Popped message member: GetSource interface: org.mpris.MediaPlayer2.Player type: 1 path: /org/mpris/MediaPlayer2
16:13:45 T:18446744073610228176 WARNING: Unhandled dbus message, member: GetSource interface: 
```
_All arguments are correct (interface, member, path and it is of type METHOD_CALL) but the dbus_message_is_method_call function doesn't recognize it._

You need to update omxplayer from [omxplayer.sconde.net](http://omxplayer.sconde.net/).
Maybe the little fix on the D-Bus handling isn't as little as I think it is.

**Comment by aristosv** [comment]
Yup, now it works! Thanks man, that was really helpful.

**Comment by jehutting** [comment]
Great. Thanks for your reports!
