### ISSUE TITLE
support for Newtek NDI

### ISSUE THREAD

**Issue by knitehawk** [popcornmix/omxplayer#491]
Would be great if NDI support could be added to this.
could greatly expand and improve live video production capabilities.

SDK at
http://new.tk/NDISDKLINUX

**Comment by jehutting** [comment]
Certainly interesting. Are you already using it (with other open-source projects)?

**Comment by popcornmix** [comment]
As I said in the other issue. If ffmpeg doesn't support this format then omxplayer won't support it.
Can you play a stream using ffmpeg?

**Comment by Ruffio** [comment]
@knitehawk what do you say to @popcornmix question?

**Comment by Ruffio** [comment]
@knitehawk what is your status on this issue? Can it be closed?

**Comment by svenmalkus** [comment]
ffmpeg now supports it:
https://www.ffmpeg.org/ffmpeg-devices.html#libndi_005fnewtek

**Comment by 7ro** [comment]
any update ?

**Comment by xiCO2k** [comment]
Any Update on this? Thanks

**Comment by popcornmix** [comment]
omxplayer is not being actively developed. The suggestion is to switch to VLC.
It's not clear if VLC supports NDI (e.g. see [here](https://forum.videolan.org/viewtopic.php?t=153158))

**Comment by xiCO2k** [comment]
Got it, thanks @popcornmix
