### ISSUE TITLE
Error using debus for muting and unmuting

### ISSUE THREAD

**Issue by swburk** [popcornmix/omxplayer#492]
Im using python to run dbuscontrol.sh for muting and unmuting omx player while it plays videos. Half the time the command throws this error

Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files

currently i run the command with a sleep in a loop till it works but it can take over 100 attempts
# 

OS: Raspian Wheezy
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Sat, 12 Sep 2015 00:49:19 +0000
        Version   : d99bd86 [master]

here is the major portion of the dbuscontrol.sh

OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.${USER:-root}"
OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.${USER:-root}.pid"
export DBUS_SESSION_BUS_ADDRESS=`cat $OMXPLAYER_DBUS_ADDR`
export DBUS_SESSION_BUS_PID=`cat $OMXPLAYER_DBUS_PID`

[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && { echo "Must have DBUS_SESSION_BUS_ADDRESS" >&2; exit 1; }

case $1 in

mute)
   dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Mute
   ;;

unmute)
   dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Unmute
   ;;

**Comment by kennyyy24** [comment]
Mute and Unmute are not dbus properties but methods, so the correct syntax should be:

dbus-send --print-reply=double --session --reply-timeout=500 -dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Mute

and 

dbus-send --print-reply=double --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Unmute

Note the difference:
org.mpris.MediaPlayer2.**Properties**.Mute => org.mpris.MediaPlayer2.**Player**.Mute

Does that work any better?

**Comment by jehutting** [comment]
With the version @swburk has both commands are properties. It is a very old omxplayer version but could be that it is the latest version for raspbian wheezy. You could try to update omxplayer from [omxplayer.sconde.net](omxplayer.sconde.net). There were some D-Bus issues fixed. Hope it still works on raspbian wheezy. (So be sure to backup your SD card before doing the update!)
 
By the way, you know of [will price](https://github.com/willprice/python-omxplayer-wrapper) python omxplayer wrapper?

**Comment by jehutting** [comment]
@swburk a status update would be appreciated.

**Comment by Ruffio** [comment]
@swburk any update? Else please this this issue...
