### ISSUE TITLE
Feature Request: Remember file seek position

### ISSUE THREAD

**Issue by Osmosis311** [popcornmix/omxplayer#496]
Is it possible to save some metadata associated with each filename so when that file is played again it will immediately jump to the last seek position?

**Comment by popcornmix** [comment]
No plans to add this to omxplayer (compare this functionality to ffmpeg which also doesn't store metadata for files).
There are a number of gui wrappers for omxplayer. I'm not sure if any of those support what you are asking, but it would be quite possible for that to be done.

**Comment by jehutting** [comment]
@Osmosis311 any comment on popcornmix´s response?

**Comment by Ruffio** [comment]
Can this be closed?
