### ISSUE TITLE
live RTP streams don't work

### ISSUE THREAD

**Issue by jmeiners** [popcornmix/omxplayer#50]
Live RTP streams do not start on the current version.

Prior versions they did start, but the video was corrupted.

Same RTP stream works fine on VLC or with omxplayer using udp instead.

Here is the details of the .sdp file I am using
v=0
o=- 653 1 IN IN4 192.168.1.81
s=VS streaming video
t=0 0
m=audio 8892 RTP/AVP 97
a=tool:DM81xx
a=recvonly
a=type:broadcast
c=IN IP4 192.168.1.128
a=rtpmap:97 mpeg4-generic/48000/2
a=fmtp:97 streamtype=5; profile-level-id=14; mode=AAC-hbr; config=0990; sizeLength=13; indexLength=3; indexDeltaLength=3; constantDuration=1024
m=video 5006 RTP/AVP 102
c=IN IP4 192.168.1.128
a=rtpmap:102 H264/90000
a=fmtp:102 packetization-mode=1
b=AS:200

**Comment by Ruffio** [comment]
@popcornmix there have been no response for a year so this issue should be closed
