### ISSUE TITLE
Vcodec id unknown: a8

### ISSUE THREAD

**Issue by fredericofs** [popcornmix/omxplayer#501]
Any clue why omxplayer cannot play those music videos, while they play fine on desktop machine ?

Exits with:

Vcodec id unknown: a8
have a nice day ;)

Links for the 3 videos:
https://www.dropbox.com/sh/q9hqy82a8n4ze4e/AADtLmHowczHdvOXSzb4AIUpa?dl=0

Thank you!

**Comment by popcornmix** [comment]
```Format                                   : VP9```

omxplayer only supports codecs with hardware support (H.264, MPEG-4 and VC-1/MPEG-2 with hardware codec licence). No support for VP9 which requires software decode support.

Something like kodi will be able to play these files.

**Comment by fredericofs** [comment]
Can I use kodi system as a command line player, without the interface, so to make use of these codec solutions Kodi has builtin ?

**Comment by popcornmix** [comment]
No

**Comment by fredericofs** [comment]
Okay, thats all, Thank you popcornmix!

**Comment by jeffersonchua** [comment]
This is related. The error is ...

**Vcodec id unknown: ad**
    ENCODER         : Lavf57.25.100
  Duration: 00:53:16.44, start: 0.000000, bitrate: 1038 kb/s
    Stream #0:0(eng): Video: hevc (Main), yuv420p(tv), 1280x720 [SAR 1:1 DAR 169], 29.97 fps, 29.97 tbr, 1k tbn, 29.97 tbc (default)
    Metadata:
      ENCODER         : Lavc57.24.102 **libx265**

It's x265, and omxplayer can't play, but ffplay play with no lags/freeze on raspberry pi 3b+.

Question .. since omxplayer is compiled with ffmpeg library, and if ffplay can play the movie, would it be possible to play with omxplayer as well?

Thanks,
Jeff.

**Comment by premultiply** [comment]
`Video: hevc (Main)`
 
> omxplayer only supports codecs with hardware support (H.264, MPEG-4 and VC-1/MPEG-2 with hardware codec licence).

No support for other video codecs which requires software decode support.

**Comment by nagualcode** [comment]
I remember once omxplayer did not have support for alsa audio, and aparently it would never be possible, but one day... surprise! Alsa audio support... I wonder if the same may happen to software decode support?

**Comment by popcornmix** [comment]
Our focus for a video player that also handles software decode is VLC.
See: https://github.com/popcornmix/omxplayer/issues/717

**Comment by nagualcode** [comment]
Is the performance, and resources footprint of VLC, good as omxplayer, when playing videos supported by the GPU ?

**Comment by popcornmix** [comment]
Under the hood with the fullscreen flag vlc will be using the same gpu side video_decode and video_render components, so the video decode performance should be the same.

**Comment by christianeaton** [comment]
Now that the [Raspberry Pi 4 supports VP9 video decoding](https://www.slashgear.com/5-ways-the-raspberry-pi-4-is-a-huge-upgrade-24581476/), is this something that OMX Player will be able to do?

**Comment by popcornmix** [comment]
There is no hardware VP9 decoder in Pi4 (only a bitstream accelerator).

omxplayer won’t support vp9.

We are deprecating use of omxplayer in favour of VLC which will support software vp9 decode.
