### ISSUE TITLE
omxplayer never exits because of an error with the SubtitleRenderer

### ISSUE THREAD

**Issue by morphx666** [popcornmix/omxplayer#502]
I have developed an application that uses omxplayer to play videos and it works perfectly, unfortunately, one some Raspberry Pi's, there's a video that causes the following error:

`15:49:45 T:18446744071722446858   ERROR: OMXPlayerSubtitles::RenderLoop threw 13Enforce_error (Enforcement failed in SubtitleRenderer.cpp(488))`

And when this happens, omxplayer never exits.
All Raspberry Pi's are Raspberry Pi 3, using the exact same image.
The version of omxplayer is dfea8c9.

[Here's a link to video in case it helps](https://xfx.net/stackoverflow/omx_problem_video.mp4).

**Comment by popcornmix** [comment]
I'm not seeing a problem with that video.
It doesn't seem to have subtitles - should it?
What is the command line you are using to play it?

```
pi@domnfs:~ $ omxplayer https://xfx.net/stackoverflow/omx_problem_video.mp4
Video codec omx-h264 width 1920 height 1080 profile 77 fps 29.970030
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1920x1080@29.97 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
have a nice day ;)
```

**Comment by morphx666** [comment]
No, it shouldn't have subtitles.

The command line to launch omxplayer is: omxplayer --no-osd <video_file>

Something else I noticed is that when using omxplayer -I <video_file>, on the Raspberry Pi's where omxplayer generates the error, the last 4 lines (Video Codec, Audio Codec, etc...) of information are missing.

**Comment by popcornmix** [comment]
But it's not failing for me:
```
pi@domnfs:~ $ omxplayer -v
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Fri, 23 Sep 2016 00:56:49 +0000
        Version   : dfea8c9 [master]
        Repository: https://github.com/popcornmix/omxplayer.git
pi@domnfs:~ $ omxplayer -t 0 https://xfx.net/stackoverflow/omx_problem_video.mp4
Video codec omx-h264 width 1920 height 1080 profile 77 fps 29.970030
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1920x1080@29.97 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
have a nice day ;)
```
Does that same command line work for you?

**Comment by popcornmix** [comment]
Also what do you have gpu_mem set to? You may need more than 64M for some files (128M should be enough for anything).

**Comment by morphx666** [comment]
Thank you SO much!
That was the problem; apparently, some Pi's were configured with the default 64MB.
