### ISSUE TITLE
Notify or detect in the main thread when the first frame is being shown on screen?

### ISSUE THREAD

**Issue by xk** [popcornmix/omxplayer#503]
Hello,

If I start omxplayer and quickly press space (pause) the fist frame is (almost?) never shown. Wait a few seconds then press v (step) and the fist frame appears on the screen. I want to add a parameter/option to do just that: to start in pause until the first frame is on screen and then notify with the message "Ready to play" to stdout.

To do that I'd need to detect in the app's main thread that the first frame is being shown on the screen. I'm not sure where to look for whatever signals that, any ideas would be greatly appreciated.

Currently I'm pausing, waiting for m_player_video.GetLevel() to return > 90% then do:

m_av_clock->OMXStep();
printf("Ready to play\n");

But that's a botch and doesn't work with short videos because m_player_video.GetLevel() never gets to 90.

So I'm lost, anybody can point me please in the right direction?

Thank you very much.

**Comment by jehutting** [comment]
I don't think it is possible or it would not be be easy to hold omxplayer on the first video frame. There's no signalling from the _omx layer_ telling us it has shown a frame on the screen. _On the Raspberry Pi forum a user wanted to create a trigger pulse for each frame of the video when it is shown on the TV. See [here](https://www.raspberrypi.org/forums/viewtopic.php?f=70&t=147690) for the comments on that._

Maybe you can create an image of your first frame (using raspi2png) and show this on the screen  and when you want to play the movie, just run omxplayer.

**Comment by xk** [comment]
Ok, will look that, thank you !

**Comment by Ruffio** [comment]
@xk can this issue be closed? If yes, then please close it. Thanks.
