### ISSUE TITLE
How to launch omxplayer from browser?

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#504]
I was reading that it is possible to call/launch omxplayer from some browsers like chromium, uzbl and other webkit browsers, but is all the sunday that I search on the wbe how to do that, and I still didn't found istructions about it. I am using a raspberry PI 3 model B.

**Comment by gkreidl** [comment]
You need the kweb package:
https://www.raspberrypi.org/forums/viewtopic.php?t=40860
Solutions for firefox and chromium:https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=147484&
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=163018

**Comment by Ruffio** [comment]
@matteoraggi has this issue been resolved? Can it be closed?

**Comment by matteoraggi** [comment]
I skipped the problem launching omxplayer from command line..

**Comment by Ruffio** [comment]
@matteoraggi then please close this issue as it isn't really an issue, more a question of implementation. Thanks.
