### ISSUE TITLE
playing livestream crashes omxplayer

### ISSUE THREAD

**Issue by fscz** [popcornmix/omxplayer#507]
Using updated raspbian jesse with updated raspberry firmware on raspberry 2 and 3, executing
`omxplayer "http://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/index_1992_av-p.m3u8?sd=10&rebase=on"`
crashes after just a few seconds. 

FTR: I can play normal video files just fine on raspbian jesse with omxplayer.
FTR2: On a fresh installation of osmc (kodi) I can play the stream just fine.

I compiled omxplayer and ffmpeg with debug symbols and produced the following backtrace.

> pi@raspberrypi:~/omxplayer/omxplayer-dist/usr/bin $ gdb omxplayer.bin
> GNU gdb (Raspbian 7.7.1+dfsg-5+rpi1) 7.7.1
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "arm-linux-gnueabihf".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from omxplayer.bin...done.
> (gdb) set env LD_LIBRARY_PATH /opt/vc/lib:/home/pi/omxplayer/omxplayer-dist/usr/lib/omxplayer
> (gdb) set env ILCS_WARN 1
> (gdb) run --display 0 -o hdmi "http://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/index_1992_av-p.m3u8?sd=10&rebase=on"
> Starting program: /home/pi/omxplayer/omxplayer-dist/usr/bin/omxplayer.bin --display 0 -o hdmi "http://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/index_1992_av-p.m3u8?sd=10&rebase=on"
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
> Cannot access memory at address 0x0
> 
> Program received signal SIGILL, Illegal instruction.
> 0x75ab7de8 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
> (gdb) continue
> Continuing.
> [New Thread 0x74593420 (LWP 12088)]
> [New Thread 0x73bff420 (LWP 12089)]
> [New Thread 0x733ff420 (LWP 12090)]
> [New Thread 0x72bff420 (LWP 12091)]
> [New Thread 0x723ff420 (LWP 12092)]
> [New Thread 0x71bff420 (LWP 12093)]
> [New Thread 0x713ff420 (LWP 12094)]
> Video codec omx-h264 width 960 height 540 profile 77 fps 25.000000
> [New Thread 0x70532420 (LWP 12095)]
> [New Thread 0x6fd32420 (LWP 12096)]
> Audio codec aac channels 2 samplerate 48000 bitspersample 16
> [New Thread 0x6f181420 (LWP 12097)]
> Subtitle count: 0, state: off, index: 1, delay: 0
> V:PortSettingsChanged: 960x540@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
> 
> Program received signal SIGTERM, Terminated.
> 0x76caa730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
> 81  ../sysdeps/unix/syscall-template.S: No such file or directory.
> (gdb) info threads
>   Id   Target Id         Frame 
>   11   Thread 0x6f181420 (LWP 12097) "omxplayer.bin" 0x76caa730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
>   10   Thread 0x6fd32420 (LWP 12096) "omxplayer.bin" 0x76ca6b30 in __pthread_cond_timedwait (cond=0x786e0 <m_player_subtitles+184>, mutex=0x786c8 <m_player_subtitles+160>, abstime=0x6fd31cc8)
>     at pthread_cond_timedwait.c:199
>   9    Thread 0x70532420 (LWP 12095) "omxplayer.bin" 0x76caa730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
>   8    Thread 0x713ff420 (LWP 12094) "omxplayer.bin" 0x76caa730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
>   7    Thread 0x71bff420 (LWP 12093) "ILCS_HOST" 0x76ca8a40 in do_futex_wait (isem=isem@entry=0x93b3c) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
>   6    Thread 0x723ff420 (LWP 12092) "omxplayer.bin" 0x76ca67a4 in __pthread_cond_wait (cond=cond@entry=0x939a8, mutex=mutex@entry=0x9398c) at pthread_cond_wait.c:187
>   5    Thread 0x72bff420 (LWP 12091) "HCEC Notify" 0x76ca8a40 in do_futex_wait (isem=isem@entry=0x76e91a64 <cecservice_notify_available_event+24>) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
>   4    Thread 0x733ff420 (LWP 12090) "HTV Notify" 0x76ca8a40 in do_futex_wait (isem=isem@entry=0x76e90cdc <tvservice_notify_available_event+24>) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
>   3    Thread 0x73bff420 (LWP 12089) "HDispmanx Notif" 0x76ca8a40 in do_futex_wait (isem=isem@entry=0x76e91b60 <dispmanx_notify_available_event+24>) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
>   2    Thread 0x74593420 (LWP 12088) "VCHIQ completio" 0x75dd2f2c in ioctl () at ../sysdeps/unix/syscall-template.S:81
> * 1    Thread 0x74595000 (LWP 12085) "omxplayer.bin" 0x76caa730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
> (gdb) thread 2
> [Switching to thread 2 (Thread 0x74593420 (LWP 12088))]
> #0  0x75dd2f2c in ioctl () at ../sysdeps/unix/syscall-template.S:81
> 81  ../sysdeps/unix/syscall-template.S: No such file or directory.
> (gdb) bt
> #0  0x75dd2f2c in ioctl () at ../sysdeps/unix/syscall-template.S:81
> #1  0x76d42000 in completion_thread () from /opt/vc/lib/libvchiq_arm.so
> #2  0x76d28cdc in vcos_thread_entry (arg=0x76d55448 <vchiq_instance+16>) at /home/pi/userland/interface/vcos/pthreads/vcos_pthreads.c:144
> #3  0x76ca1e90 in start_thread (arg=0x74593420) at pthread_create.c:311
> #4  0x75dda598 in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92 from /lib/arm-linux-gnueabihf/libc.so.6
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> (gdb) 

There is no crash here, but a signal SIGTERM is received. All threads, except for no: 2 are idle/sleeping. 

To find out, about the condition in which SIGTERM arrises, I compiled a kernel and added
```
printk("__send signal %d from: %d\n", sig, task_pid_nr_ns(current, task_active_pid_ns(t)));
dump_stack();
```
to kernel/signal.c:__send_signal.

That gave me the following trace per dmesg:

> [  716.159433] __send signal 17 from: 0
> [  716.159463] CPU: 3 PID: 1357 Comm: omxplayer.bin Not tainted 4.4.39-v7 #15
> [  716.159473] Hardware name: BCM2709
> [  716.159523] [<80018794>] (unwind_backtrace) from [<80014058>] (show_stack+0x20/0x24)
> [  716.159549] [<80014058>] (show_stack) from [<80321804>] (dump_stack+0xd4/0x118)
> [  716.159576] [<80321804>] (dump_stack) from [<8003179c>] (__send_signal+0x94/0x458)
> [  716.159599] [<8003179c>] (__send_signal) from [<80031ba8>] (send_signal+0x48/0x98)
> [  716.159622] [<80031ba8>] (send_signal) from [<8003311c>] (do_notify_parent+0x1c8/0x208)
> [  716.159643] [<8003311c>] (do_notify_parent) from [<8002634c>] (release_task+0x498/0x4d8)
> [  716.159662] [<8002634c>] (release_task) from [<80027e44>] (do_exit+0x6c8/0xabc)
> [  716.159679] [<80027e44>] (do_exit) from [<800282d0>] (do_group_exit+0x4c/0xe4)
> [  716.159699] [<800282d0>] (do_group_exit) from [<8003358c>] (get_signal+0x370/0x6dc)
> [  716.159722] [<8003358c>] (get_signal) from [<800135d0>] (do_signal+0x278/0x3c0)
> [  716.159744] [<800135d0>] (do_signal) from [<80013900>] (do_work_pending+0xb8/0xd0)
> [  716.159766] [<80013900>] (do_work_pending) from [<8000fb68>] (slow_work_pending+0xc/0x20)
> [  716.165894] __send signal 17 from: 1341
> [  716.165929] CPU: 2 PID: 1341 Comm: omxplayer Not tainted 4.4.39-v7 #15
> [  716.165939] Hardware name: BCM2709
> [  716.165986] [<80018794>] (unwind_backtrace) from [<80014058>] (show_stack+0x20/0x24)
> [  716.166012] [<80014058>] (show_stack) from [<80321804>] (dump_stack+0xd4/0x118)
> [  716.166041] [<80321804>] (dump_stack) from [<8003179c>] (__send_signal+0x94/0x458)
> [  716.166064] [<8003179c>] (__send_signal) from [<80031ba8>] (send_signal+0x48/0x98)
> [  716.166093] [<80031ba8>] (send_signal) from [<8003311c>] (do_notify_parent+0x1c8/0x208)
> [  716.166114] [<8003311c>] (do_notify_parent) from [<800281d4>] (do_exit+0xa58/0xabc)
> [  716.166133] [<800281d4>] (do_exit) from [<800282d0>] (do_group_exit+0x4c/0xe4)
> [  716.166151] [<800282d0>] (do_group_exit) from [<80028388>] (__wake_up_parent+0x0/0x30)
> [  716.166173] [<80028388>] (__wake_up_parent) from [<8000fb40>] (ret_fast_syscall+0x0/0x1c)

**Comment by jehutting** [comment]
I can't confirm this crash: sometimes I get a time out (EOF?) upon which omxplayer just stops. Have to verify this issue when there is a live broadcast.

**Comment by fscz** [comment]
I am running a raspberry pi 3 with currently 64 mb video ram. But I tried 128 m and even 256. Still crashed.

**Comment by jehutting** [comment]
Isn't signal 17 SIGCHLD?
And, is ```--display 0``` valid? I thought only the values 4=LCD and 5=HDMI/TV can be used.
Can you post the omxplayer logging (option ```-g```)? Maybe that reveals something.

**Comment by fscz** [comment]
17 is SIGCHLD - yes. --display 0 is not the problem. I tried with various additional options. -- display 0, -o hdmi, --live for example. Unfortunately each time the player would crash. I also crashes if just do omxplayer "http://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/index_1992_av-p.m3u8?sd=10&rebase=on"

**Comment by fscz** [comment]
What is you configuration. I am using. Raspberry Pi 3 with updated firmware, updated raspbian and currently 64m video mem.

**Comment by fscz** [comment]
A python process on my system was periodically issuing "killall omxplayer" goddamnit.

**Comment by jehutting** [comment]
:-) That explains the SIGTERM. Nice catch anyway!
I would go for at least 128MB GPU, just to stay out of (strange) troubles.
Have a nice day...
