### ISSUE TITLE
Video does not play, no error message

### ISSUE THREAD

**Issue by ciex** [popcornmix/omxplayer#509]
I am trying to play a video with omxplayer on Debian 8.0 on a Raspberry Pi, but neither is a window opened, nor does the command line output hint at possible issues.

A 3.5 inch touchscreen display is connected, which works with mplayer.

**Problem description**

The command I am using is
`$ omxplayer /opt/vc/src/hello_pi/hello_video/test.h264`

The video file is included with the pi and works in mplayer. 

Output:
`Video codec omx-h264 width 1920 height 1080 profile 77 fps 25.000000`
`Subtitle count: 0, state: off, index: 1, delay: 0`
`V:PortSettingsChanged: 1920x1080@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.12 display:0 layer:0 alpha:255 aspectMode:0`
`have a nice day ;)`

Expected result: omxplayer window opens, video starts playing
Actual output: No error message, but also no playback. 

After a couple of seconds (I assume the length of the video), the process exits with no further output.

I also tried calling omxplayer with `--display=4` and `--display=6` in an attempt to select the display, but this changes nothing.

**Additional information**
`$ omxplayer --version`
`omxplayer - Commandline multimedia player for the Raspberry Pi`
`        Build date: Fri, 23 Sep 2016 00:56:49 +0000`
`        Version   : dfea8c9 [master]`
`        Repository: https://github.com/popcornmix/omxplayer.git`

I downloaded the omxplayer binary with build date `Build date: 23/09/2016` from `http://omxplayer.sconde.net/`. Installing it with `apt-get` yields the same results

Any help is much appreciated!

**Comment by jehutting** [comment]
Are you expecting to see the video on the 3.5 LCD? With omxplayer that is not directly possible. You have to use fbcp. See [omxplayer on TFT](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=63133).

**Comment by Ruffio** [comment]
@ciex can this be closed?

**Comment by Ruffio** [comment]
@popcornmix this issue should be closed due to lack of response (3 months) and it looks like omxplayer is working as designed (not able to play on TFT)

**Comment by ciex** [comment]
Sorry for the missing response. For some reason notification your previous answers were filtered as spam by my email client. As you already guessed I did not know that omxplayer was not supposed to play on TFTs, which I am trying to do. I will have a look at the linked thread. Thanks for your help.
