### ISSUE TITLE
Switching audio stream is too slow, how to handle?

### ISSUE THREAD

**Issue by gzyip** [popcornmix/omxplayer#512]

**Comment by jehutting** [comment]
when/how/one from multi in single?

**Comment by gzyip** [comment]
When playing any song.  switching vocal on /  vocal off is too slow.

**Comment by jehutting** [comment]
How do you do vocal on / vocal off?
Is this related to issue #345.

**Comment by gzyip** [comment]
#345 ==> --Timeout 0 and max_analyse_duration=500000 (0,5 second) and its encapsuled in a while true.
I don't know "its encapsuled in a while true".
Would you show detail?

**Comment by jehutting** [comment]
Can you please answer the question 'How do you do vocal on / vocal off?'.
I am not sure if # 345 is related, it is also a question to you.

**Comment by popcornmix** [comment]
omxplayer is designed to keep buffers of audio/video full on the GPU.
This allows maximum resistance to underrunning when ARM is busy or network speed drops.
There may be a number of seconds of audio/video buffered on GPU (it depends on bitrate).
In general changing audio stream will have this latency.
It should be possible to run omxplayer with less buffered data. Try playing with:
```
    --audio_fifo  n         Size of audio output fifo in seconds
    --video_fifo  n         Size of video output fifo in MB
    --audio_queue n         Size of audio input queue in MB
    --video_queue n         Size of video input queue in MB
```

**Comment by Ruffio** [comment]
@gzyip any comments? Else please close this issue...
