### ISSUE TITLE
Ffmpeg and omxplayer

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#513]
Which rules should I follow to make works well the mp4 created with ffmpeg into omxplayer?
If I create videos from shotcut and openshot for omxplayer, it is all right.
If instead I create videos from ffmpeg then I can't see the videos on omxplayer.
I am using raspbian 8 pixel with raspberry 3 model b and the default omxplayer installed in this os updated and upgraded at the last version.
I create the mp4 file with ffmpeg trough this command:
`ffmpeg -r 1/5 -i frame_%04d.png -s 1080x1920 -vcodec libx264  -pix_fmt yuv420p -preset fast -crf 18 -b-pyramid none -acodec ac3 -ab 1536k -scodec copy  -r 30 omxplayer.mp4`
And omxplayer then answer to me only this line of text and doesn't play:
`video codec omx-264 width 1080 height 1920 profile 100 fps 25.000000 Subtitle ount : 0, state : off, index: 1, delay: 0`
Here attached the 2 log files: NO is the log of the not working file (generated with ffmpeg) and YES is the working well file.
[YES.log.txt](https://github.com/popcornmix/omxplayer/files/687499/YES.log.txt)
[NO.log.txt](https://github.com/popcornmix/omxplayer/files/687500/NO.log.txt)
here the mp4 that doesn't works to me on omxplayer:
http://185.24.234.250/ffmpeg-test/out_123.mp4
http://185.24.234.250/ffmpeg-test/test2.mp4

**Comment by jehutting** [comment]
Is the GPU mem (in /boot/config.txt) too small (causing Enforce_error SubtitleRenderer in YES.log.txt)???

NO.log.txt shows no line ```COMXVideo::PortSettingsChangedLogger``` which is essential for playing. 

I can play both .mp4 (from commandline and GUI).

**Comment by matteoraggi** [comment]
Uou are right! I moved the GPU from 64 to 128 Mb and now it plays well! thanks!
