### ISSUE TITLE
what's different about omxplayer?

### ISSUE THREAD

**Issue by aristosv** [popcornmix/omxplayer#517]
This may not be relevant to omxplayer, but there's a chance it could be, so bare with me please. I am currently using this bash script to loop and shuffle media from a folder, on the Raspbian frame buffer. No X server is running on the Raspberry Pi.

Also this script is run with a & at the end, so it drops to the background. 
```
#!/bin/bash
# import variables
source "${BASH_SOURCE%/*}/variables"
# loop & shuffle
while true
do
 for audio in $(ls $localaudiomedia/* | shuf)
 do
 echo "playing $audio"
 omxplayer --no-osd $audio > /dev/null
 done
done
```
I had a friend write a C# application that will allow me to run bash scripts located on a Raspberry Pi. Any bash script on the Raspberry Pi,  that contains "omxplayer", get's the application frozen. The bash script runs, but the Windows application freezes, until I kill the bash script from the Linux temrinal.

So I thought I would try to run these bash scripts using Rundeck. Again, the bash script is executed, but Rundeck shows the command as "running" for ever. Or until I kill the bash script from the Linux temrinal. And this behaviour only happens with bash scripts that have to run omxplayer.

So I'm beginning to suspect that omxplayer player runs in a way that doesn't properly respond back to the Windows application, or to Rundeck. Or maybe I have to run it in a different way to make Rundeck understand that the script has run and finished.

Any thoughts on the matter would be appreciated.

**Comment by Ruffio** [comment]
@aristosv I also use a C# program to execute the Omxplayer, but I have no issue. From your description it sounds like it is the C# programs that have the issue, not omxplayer. I your code above you have 'while true' which makes the script run forever...

**Comment by aristosv** [comment]
the c# program and rundeck don't know what the script contains. They just run "play-audio.sh &"
This should drop the process in the background. So the c# program and rundeck should consider this finished. But they don't.

Do you have any suggestion on how to loop & shuffle, and avoid using 'while true'?

**Comment by Ruffio** [comment]
How do your program detect if the script has finished? As I wrote, the
script will run forever because of your 'while true' statement. This has
nothing to do with omxplayer and therefore not a bug with omxplayer... I
don't have any suggestions, but seach the web. Your are not the first one
with this request/question ;-)

Venlig hilsen Rasmus Christiansen

2017-01-09 15:57 GMT+01:00 aristosv <notifications@github.com>:

**Comment by aristosv** [comment]
I have actually created a script containing only this line and I have the exact same problem.
`omxplayer --no-osd 1.mp3`
I have also searched the web to find a way to loop & shuffle without using 'while', 'for' or any bash scripting loop, and even asked in this project if there's a way for omxplayer to loop a folder without bash scripting, but there is no way.

**Comment by Ruffio** [comment]
How do your program detect if the script has finished? ps? Without knowing how you detect if a script has finished then it is difficult to help you, but I don't this as an issue with omxplayer.

Correct, omxplayer doesn't support looping/playing multiple files.
Take a look at this 'project', he checks if omxplayer is running an loops thru a folder with files.

**Comment by aristosv** [comment]
did you want to post a link on the word "project"?

**Comment by Ruffio** [comment]
https://github.com/notandrewkaye/loopVideo/blob/master/loopVideo.sh

**Comment by aristosv** [comment]
if you remove the check if omxplayer is running, its exactly the same as my script. And it still uses 'while true' Anyway, it was a long shot. I'll keep searching for a solution.

**Comment by popcornmix** [comment]
If you are (effectively) running omxplayer in background with ``&`` then you should add ``--no-keys`` to command line.
No idea if that is related to your issue, but reading keys from background process won't work.

**Comment by jehutting** [comment]
@aristosv you said:
> the c# program and rundeck don't know what the script contains. They just run "play-audio.sh &"
This should drop the process in the background. So the c# program and rundeck should consider this finished. But they don't.

I created a small test c# program in which a _Process object_  calls a script. The script has a while forever loop calling omxplayer. After the _Process.Start()_ the c# program just continuous.

So I am interested to see how your c# program looks like, especially on how the backgrounding ('&') part is done. Maybe only through PM if you don't want to public it?

By the way, I execute the c# program from the CLI. Is your c# program a GUI program?

**Comment by aristosv** [comment]
I don't have the source code for the C# program, but my problem was resolved when I used this `> /dev/null 2>&1 &` to drop the script in the background.

**Comment by jehutting** [comment]
OK...but where did you made that modification? I assume not in the c# program!?
I just try to understand 'how do you get omxplayer running in the background'.

**Comment by aristosv** [comment]
I did the change in the bash scripts on the Linux computer. After that, both rundeck and the app were working just fine.

Its strange because on the Linux terminal everything was working just fine with just the &
