### ISSUE TITLE
RTSP TCP Support

### ISSUE THREAD

**Issue by radojko** [popcornmix/omxplayer#52]
I'm trying to play RTSP TCP stream but without success, it seems Omxplayer support only RTSP UDP?

To add: I have error message "Invalid framerate 90000, using forced 25fps and just trust timestamps"
Other players, vlc, android.. works properly with this stream. Omxplayer works properly with RTSP UDP.

**Comment by Ruffio** [comment]
@radojko is this still an issue?

**Comment by radojko** [comment]
This is not issue any more.
