### ISSUE TITLE
Neither Subtitles nor OSD text messages are shown in full screen.

### ISSUE THREAD

**Issue by jehutting** [popcornmix/omxplayer#521]
With the latest commit these don't appear.

Only within a window (--win option) they do.

**Comment by popcornmix** [comment]
@eysispeisi any thoughts?

**Comment by eysispeisi** [comment]
can you post the contents of ~/.tboplayer/tboplayer.cfg please?

**Comment by eysispeisi** [comment]
just managed to reproduce:
Options -> edit -> checked "Forbid windowed mode"

Short term, you can un-check "Forbid windowed mode" in options to get subtitles to show until we get a fix in. If that is what is happining in your case.

**Comment by eysispeisi** [comment]
oops, was thinking of the wrong project, i'll check this out

**Comment by eysispeisi** [comment]
Created a pull request with a fix for this issue

**Comment by jehutting** [comment]
The OSD and subtitles do appear with the fix. Thanks!
