### ISSUE TITLE
Connection between ffmpeg and omxplayer

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#524]
In your files I read not rarely some connections between omxplayer and ffmpeg, which connections could be?
omxplayer is just a player and ffmpeg is a video producer. I don't see big connections.
I am going to test a full hd video screen recording from ffmpeg to omxplayer while playing from raspbian 8 on raspberry pi 3 model b. any suggestions?

**Comment by popcornmix** [comment]
ffmpeg handles demuxing of video files (e.g. extracting streams from mkv) and decoding of audio and video.
omxplayer uses ffmpeg for demuxing and decoding of audio, and handles the decoding of video by the GPU. So omxplayer requires ffmpeg as a library to function.

I'm not really sure what your question is. Are you wanting to capture the display of the raspberry pi when it is running and encode that as a video stream or something else?

**Comment by matteoraggi** [comment]
Thanks for the great and quick answer! Yes, I would like to capture the display of the raspberry pi 3 model b while encoding an mp4 trough omxplayer, to check if it is playing well remotely.
The mp4 recorded from ffmpeg then will be saved nto a folder shared with me trough syncthing, so then I can check if it is all right whe nneeded, without use the old slow vnc.

**Comment by popcornmix** [comment]
omxplayer is a video decoder. It has no encode capability so isn't the right tool for what you want.

**Comment by matteoraggi** [comment]
I just would like to know why if I do CTRL+F here:
https://github.com/popcornmix/omxplayer
it is easy to finde texts speaking about ffmpeg in the page of omxplayer.

**Comment by popcornmix** [comment]
Because ffmpeg is a library used by omxplayer.
Encoding display output is nothing to do with omxplayer, so closing.
