### ISSUE TITLE
popcornmix vs  huceke which the best for raspberry?

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#525]
Hi, I am using from some month omxplayer of popcornmix with 8 raspberry from some month, and I am courious to know the difference between omxplayer of  huceke vs omxplayer of popcornmix (the omxplayer installed by default on raspbian 8 pixel for raspberry pi 3 model b).

**Comment by popcornmix** [comment]
This repo is dead don't post here.
