### ISSUE TITLE
omxplayer with playlist folder

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#526]
Is it possible to configure omxplayer to play a loop of vidoes from a playlist generated from the video files that are into a folder? So the if the videos into the folder change , then also the playlist of the playing loop would change periodically...

**Comment by popcornmix** [comment]
No plans for this. omxplayer is a simple video player comparable with ffplay and doesn't support handling multiple files.
See [here](https://ubuntuforums.org/showthread.php?t=2068478) for how to handle playing multiple files with ffmplay. A similar bash script can be used with omxplayer. e.g.
```
for f in *.{mp4,mov,m4v,mkv,avi,ts,vob,mpg,m2ts,wtv} ; do omxplayer "$f"; done
```

**Comment by matteoraggi** [comment]
thanks, just ffplay maybe it is not the best on raspbian, I see that all people are using omxplayer and they are so happy to use it!

**Comment by popcornmix** [comment]
My example was using omxplayer to play all video files in a directory.

This bug tracker is for reporting bugs in omxplayer.
For general question the forum is a better place.
https://www.raspberrypi.org/forums/index.php

**Comment by matteoraggi** [comment]
From terminal I launched the file playlist.sh wth the command `sh playlist.sh`
but then I receive this error in answer:
`File "*.{mp4,mov,m4v,mkv,avi,ts,vob,mpg,m2ts,wtv}" not found.`
But in the folder there are 8 .mp4 videos and all of the mare working well with omxplayer, so I suppose that the problem is the code, because if I write `for f in *.mp4 ; do omxplayer "$f"; done` it wors well!

**Comment by matteoraggi** [comment]
So your suggested bash script is essentially working well!
I just found 2 main issues:
1) after playing all the videos in the folder it stop instead to loop itself again and again, and being not an expert in .sh files, at the moment I have no idea about how to loop this script too.
2) between a video and another there is a gap showing the raspbian desktop and this is very ugly to see.. I was reading that some people was preloading a second instance of omxplayer with transparent color and then starting the new instance exactly at the end of the last instance to hide the time that omxplayer need to close and open. Do you have some code suggestions or tips to build a script like this?

**Comment by popcornmix** [comment]
You can wrap the whole bash command in an infinite loop. e.g.
```
while : ; do for f in *.{mp4,mov,m4v,mkv,avi,ts,vob,mpg,m2ts,wtv} ; do omxplayer "$f"; done; done
```
You can blank the screen with:
```
sudo sh -c "echo 0 > /sys/class/graphics/fb0/blank"
```
echo 1 to enable it again.

**Comment by msongz** [comment]
nice , but I run the command `while : ; do for file ...` in ssh, it could not be killed by `ctrl +c` 
i have a lcd screen connect to the pi2
