### ISSUE TITLE
Trouble with playback after ffmpeg padding

### ISSUE THREAD

**Issue by tlemmons** [popcornmix/omxplayer#530]
I do not know if this is a direct problem with omxplayer but the videos play back fine in several pc based players.
If a video is processed by ffmpeg with a pad filter, for example -filter:v "pad=height=1280:y=0:color=black", then omxplayer displays very large block distorted video.  No error conditions are logged.  I can attach sample videos or provide more information if that will help.  I am willing to help in any way if needed.  Thanks.

**Comment by popcornmix** [comment]
A small sample file that shows the problem would be useful.
Might also be useful explaining why the padding is useful.

**Comment by tlemmons** [comment]
I have included an original file and a converted bad file.  the converted file was first transposed, then padded and cropped.  I have verified that the padding alone causes the problem.  The reason for needing this is to allow placement and sizing on the output from a server side component. 
[bad.zip](https://github.com/popcornmix/omxplayer/files/761870/bad.zip)

**Comment by tlemmons** [comment]
Any ideas on this?

**Comment by popcornmix** [comment]
I think the problem is the height.
The HW codec is designed for up to 1920x1080 resolution.
I suspect the height of 1280 is causing the problem. Do any videos with a height <=1080 have this issue?

**Comment by tlemmons** [comment]
Sorry I missed the notification.  I will look into the height issue.  To get around the issue I have not been using padding and just letting it get expanded to full screen.  I may look at modifying first then rotating.

**Comment by Ruffio** [comment]
@tlemmons any news on this issue? have yoy done some more experimentation with different heights?  Can it be closed?

**Comment by popcornmix** [comment]
It is also worth testing with latest firmware (``sudo apt-get update && sudo apt-get dist-upgrade``).
There has been a fix for "tall" videos.

**Comment by tlemmons** [comment]
I am sorry, I have not had time to do much testing, and it might be a while before I do.  I do have a good work around for now so I would suggest closing this and I will open a new issue if and when needed.
