### ISSUE TITLE
Is remote control possible?

### ISSUE THREAD

**Issue by gregfr** [popcornmix/omxplayer#531]
Greetings
Is there a possibility to control omxplayer from a shell script or network (like vlc http interface)? Not remote the hardware device like the ones on TV sets, remote like a process outside the player.
TIA

**Comment by popcornmix** [comment]
Yes, see https://github.com/popcornmix/omxplayer/blob/master/dbuscontrol.sh
and read the DBUS control section of readme:
https://github.com/popcornmix/omxplayer

**Comment by gregfr** [comment]
Sweet, thanks a lot!!!
