### ISSUE TITLE
Subtitles won't show

### ISSUE THREAD

**Issue by lefebvresam** [popcornmix/omxplayer#535]
When I play my video with:
sudo omxplayer -o hdmi ~/videotest.mp4 --subtitles ~/videotest.srt

The subtitles will not show at all. 

I use a Pi3 with HD screen.
Previously I used a Pi2 and a lower resolution screen and it worked with the same files.

The content of videotest.srt is:

1
00:00:28,0 --> 00:00:29,0
00:10

2
00:00:29,0 --> 00:00:30,0
00:09

3
00:00:30,0 --> 00:00:31,0
00:08

4
00:00:31,0 --> 00:00:32,0
00:07

5
00:00:32,0 --> 00:00:33,0
<u>00:06</u>

6
00:00:33,0 --> 00:00:34,0
<font color="red">00:05</font>

7
00:00:34,0 --> 00:00:35,0
<font color="red">00:04</font>

8
00:00:35,0 --> 00:00:36,0
<font color="red">00:03</font>

9
00:00:36,0 --> 00:00:37,0
<font color="red">00:02</font>

10
00:00:37,0 --> 00:00:38,0
<font color="red">00:01</font>

11
00:00:38,0 --> 00:00:39,0
<font color="red">00:00</font>

Version info:

pi@raspberrypi:~ $ omxplayer -v
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Fri, 23 Sep 2016 00:56:49 +0000
        Version   : dfea8c9 [master]
        Repository: https://github.com/popcornmix/omxplayer.git

**Comment by popcornmix** [comment]
What is gpu_mem set to?
You may need more than 64 for HD video with subtitles. Try ``gpu_mem=128`` in config.txt.

**Comment by lefebvresam** [comment]
There was no gpu_mem in config.txt with default setting of 64 as result. By putting gpu_mem=128 in the file the problem is resolved after reboot. Thanks.

Another issue I have is that system do not boots by using full HD display area. Even after starting my kiosk application I have black borders. Can I change it in the same file?

**Comment by lefebvresam** [comment]
I solved the problem with:
hdmi_group=2
hdmi_mode=82
hdmi_drive=2 (for having sound)

**Comment by Ruffio** [comment]
@lefebvresam this issue can be closed, right?

**Comment by lefebvresam** [comment]
Yes problem was solved by changing the config like described.

**Comment by Ruffio** [comment]
@lefebvresam then close the issue ;-)
