### ISSUE TITLE
Quad Warp Distortion

### ISSUE THREAD

**Issue by danielmorena** [popcornmix/omxplayer#540]
It will be awsome to have it, like so:
--quad x1,y1,x2,y2,x3,y3,x4,y4
pi will be a (even more) serious competitor for a lot media players.
I'm willing to develop, but In order to it, can u elaborate (roughly) the render logic of omxplayer? which class is the actual renderer for the software?

**Comment by popcornmix** [comment]
omxplayer displays video frames using the video_render component (which uses dispmanx / HVS internally). This has no ability to support distorted quads.

The only option is to convert decoded video frames to textures and use OpenGL ES to distort them.

The code would look like this: https://github.com/raspberrypi/firmware/tree/master/opt/vc/src/hello_pi/hello_videocube
Doing this would harm performance (smooth 1080p30 video is unlikely to be possible) so isn't a direction omxplayer will be going in.

Feel free to create your own omxplayer fork that supports this, but I suspect the changes required will be substantial.

**Comment by danielmorena** [comment]
agree on the performance, but most projectors are (in a pratical way) 1024x768. I can live with this resolution, if oxmplayer could handle it at 30fps :) I will investigate the linked code. Thanks for your time :)

**Comment by popcornmix** [comment]
I'll close this - it is not something omxplayer will be supporting.
