### ISSUE TITLE
vertical / 90* rotate video playback

### ISSUE THREAD

**Issue by protoloco** [popcornmix/omxplayer#549]
hi , 

I am try to play some video's who set to 1080*1920 (vertical HD) and it's not working well. the video is played but not cover all screen. i tried to use ''--orientation'' command but it creat a strange effects. the video is still ''standing'' (i want it to lie down on screen). i allso try to set RPI screen to portrait using ''display_rotate=1/2/3" but then omxplayer doesn't worked at all. there is any other solution for that ?

**Comment by popcornmix** [comment]
Transposing video requires additional gpu buffers.
Make sure gpu_mem is high enough (e.g. 128M).

**Comment by protoloco** [comment]
thank man, that was so simple, it's work like a magic :)

thanks alot.
