### ISSUE TITLE
Omxplayer stops when rtsp stream is paused

### ISSUE THREAD

**Issue by johannesjansson** [popcornmix/omxplayer#550]
Hi,
I'm playing an rtsp stream (broadcast started in VLC using VLM) using the command
`omxplayer -r --live rtsp://169.254.218.72:8858/LIVE0.sdp --win 1100,0,1356,144 -g` 
I have the problem that if the stream is paused, omxplayer stops after a couple of seconds. I don't see the issue if I play the stream in e.g. VLC.

In the log I see `ERROR: COMXPlayer::interrupt_cb - Timed out` which seems to cause the issue. Is this something that has been seen before?

`omxplayer -v` gives
```
omxplayer - Commandline multimedia player for the Raspberry Pi
    Build date: Mon, 30 Jan 2017 01:52:37 +0000
    Version   : 62fb580 [master]
    Repository: https://github.com/popcornmix/omxplayer.git
```
Log attached:
[omxplayer.txt](https://github.com/popcornmix/omxplayer/files/1080883/omxplayer.txt)

**Comment by jehutting** [comment]
The `ERROR: COMXPlayer::interrupt_cb - Timed out` is given after 10 seconds of no stream data input. This time-out time can  be changed with the option `--timeout n` with `n` in seconds. There is no magic number to discard the time-out function.

**Comment by johannesjansson** [comment]
Thank you for the answer!

I tried with adding `--timeout 0` when starting the stream, but omxplayer still stops after a while after the stream has been paused (now after approx 20 s).

New log:
[omxplayer.txt](https://github.com/popcornmix/omxplayer/files/1083953/omxplayer.txt)

**Comment by jehutting** [comment]
Unfortunately, there are still unsolved issues with streaming, and it looks like you are running into one of them (see issue 361). The suspicion is that ffmpeg detects (incorrect) an End-Of-File (EOF) upon which OMXPlayer just stops (see logging SubmitEOS / IsEOS).
Could you try to run without the `--live` option? Just curious if that gives a different behaviour.

**Comment by johannesjansson** [comment]
Running omxplayer without `--live` causes the same behaviour unfortunately...

The command I used now in it's entirety was
`omxplayer -r rtsp://169.254.218.72:8858/LIVE0.sdp --win 1100,0,1356,144 --timeout 0 -g`

Log:
[omxplayer.txt](https://github.com/popcornmix/omxplayer/files/1087817/omxplayer.txt)

**Comment by jehutting** [comment]
Thanks for the try.

Lets try to direct FFmpeg through [the rtsp options](http://ffmpeg.org/ffmpeg-protocols.html#rtsp) using omxplayer option `--avdict`. Can you add 
```
--avdict rtsp_transport:tcp,stimeout:60000000
```
stimeout in microseconds, and seems to work only on a TCP socket.
Also try to use the rtsp option `timeout` instead of or together with the `stimeout`.

**Comment by johannesjansson** [comment]
Trying to connect to the stream with:
`omxplayer -r rtsp://[...] --win[...] --avdict rtsp_transport:tcp,stimeout:60000000 -g`
only makes omxplayer return `have a nice day ;)`

In [the log](https://github.com/popcornmix/omxplayer/files/1091254/omxplayer.txt) the following error line is found:
`ERROR: COMXPlayer::OpenFile - avformat_open_input rtsp://192.168.205.77:8858/LIVE1.sdp`

The result is the same if also `--timeout 0` is included:
`omxplayer -r rtsp://[...] --win[...] --timeout 0 --avdict rtsp_transport:tcp,stimeout:60000000 -g`

Or did you mean that I should do it in a different way?

**Comment by jehutting** [comment]
No you did it right. I was just suggesting one of the belows
```
--avdict rtsp_transport:tcp,stimeout:60000000
--avdict rtsp_transport:tcp,timeout:-1
--avdict rtsp_transport:tcp,stimeout:60000000,timeout:-1
```
with the rest of your options.

Strange that it doesn't work. Are these options not valid for your stream?
Try
```
omxplayer --avdict stimeout:60000000 "rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/_definst_/mp4:bigbuckbunnyiphone_400.mp4"
```
At least it plays at my RPI.

What do you get with ` ls -l /usr/lib/omxplayer/`?
```
Something like this?
$ ls -l /usr/lib/omxplayer/
total 12332
lrwxrwxrwx 1 root root       23 sep 23  2016 libavcodec.so -> libavcodec.so.57.48.101
lrwxrwxrwx 1 root root       23 sep 23  2016 libavcodec.so.57 -> libavcodec.so.57.48.101
-rwxr-xr-x 1 root root 10206404 sep 23  2016 libavcodec.so.57.48.101
lrwxrwxrwx 1 root root       23 sep 23  2016 libavdevice.so -> libavdevice.so.57.0.101
lrwxrwxrwx 1 root root       23 sep 23  2016 libavdevice.so.57 -> libavdevice.so.57.0.101
-rwxr-xr-x 1 root root    14648 sep 23  2016 libavdevice.so.57.0.101
lrwxrwxrwx 1 root root       23 sep 23  2016 libavfilter.so -> libavfilter.so.6.47.100
lrwxrwxrwx 1 root root       23 sep 23  2016 libavfilter.so.6 -> libavfilter.so.6.47.100
-rwxr-xr-x 1 root root   103708 sep 23  2016 libavfilter.so.6.47.100
lrwxrwxrwx 1 root root       24 sep 23  2016 libavformat.so -> libavformat.so.57.41.100
lrwxrwxrwx 1 root root       24 sep 23  2016 libavformat.so.57 -> libavformat.so.57.41.100
-rwxr-xr-x 1 root root  1364620 sep 23  2016 libavformat.so.57.41.100
lrwxrwxrwx 1 root root       22 sep 23  2016 libavutil.so -> libavutil.so.55.28.100
lrwxrwxrwx 1 root root       22 sep 23  2016 libavutil.so.55 -> libavutil.so.55.28.100
-rwxr-xr-x 1 root root   448044 sep 23  2016 libavutil.so.55.28.100
lrwxrwxrwx 1 root root       24 sep 23  2016 libswresample.so -> libswresample.so.2.1.100
lrwxrwxrwx 1 root root       24 sep 23  2016 libswresample.so.2 -> libswresample.so.2.1.100
-rwxr-xr-x 1 root root    78284 sep 23  2016 libswresample.so.2.1.100
lrwxrwxrwx 1 root root       21 sep 23  2016 libswscale.so -> libswscale.so.4.1.100
lrwxrwxrwx 1 root root       21 sep 23  2016 libswscale.so.4 -> libswscale.so.4.1.100
-rwxr-xr-x 1 root root   393680 sep 23  2016 libswscale.so.4.1.100
```
I assume you got the latest and greatest omxplayer version.

Thanks for just trying all these things out. I am just looking if there could be anything else than just blaming FFmpeg given an invalid/incorrect EOF. As I already said, there is no workaround/fix for that issue.

**Comment by johannesjansson** [comment]
I was able to play the stream when removing using `rtsp_transport:tcp` so I guess that has something to with that I need to do some enabling of tcp when setting up the stream in vlc as well? Unfortunately the issue when pausing occurred when trying all of the options below together with or without `--timeout 0`.
```
--avdict stimeout:60000000
--avdict timeout:-1
--avdict stimeout:60000000,timeout:-1
```

`ls -l /usr/bin/omxplayer/` returns
```
total 12344
lrwxrwxrwx 1 root root       23 Jan 30 02:55 libavcodec.so -> libavcodec.so.57.48.101
lrwxrwxrwx 1 root root       23 Jan 30 02:55 libavcodec.so.57 -> libavcodec.so.57.48.101
-rwxr-xr-x 1 root root 10211428 Jan 30 02:55 libavcodec.so.57.48.101
lrwxrwxrwx 1 root root       23 Jan 30 02:55 libavdevice.so -> libavdevice.so.57.0.101
lrwxrwxrwx 1 root root       23 Jan 30 02:55 libavdevice.so.57 -> libavdevice.so.57.0.101
-rwxr-xr-x 1 root root    14648 Jan 30 02:55 libavdevice.so.57.0.101
lrwxrwxrwx 1 root root       23 Jan 30 02:55 libavfilter.so -> libavfilter.so.6.47.100
lrwxrwxrwx 1 root root       23 Jan 30 02:55 libavfilter.so.6 -> libavfilter.so.6.47.100
-rwxr-xr-x 1 root root   103708 Jan 30 02:55 libavfilter.so.6.47.100
lrwxrwxrwx 1 root root       24 Jan 30 02:55 libavformat.so -> libavformat.so.57.41.100
lrwxrwxrwx 1 root root       24 Jan 30 02:55 libavformat.so.57 -> libavformat.so.57.41.100
-rwxr-xr-x 1 root root  1364724 Jan 30 02:55 libavformat.so.57.41.100
lrwxrwxrwx 1 root root       22 Jan 30 02:55 libavutil.so -> libavutil.so.55.28.100
lrwxrwxrwx 1 root root       22 Jan 30 02:55 libavutil.so.55 -> libavutil.so.55.28.100
-rwxr-xr-x 1 root root   451988 Jan 30 02:55 libavutil.so.55.28.100
lrwxrwxrwx 1 root root       24 Jan 30 02:55 libswresample.so -> libswresample.so.2.1.100
lrwxrwxrwx 1 root root       24 Jan 30 02:55 libswresample.so.2 -> libswresample.so.2.1.100
-rwxr-xr-x 1 root root    78284 Jan 30 02:55 libswresample.so.2.1.100
lrwxrwxrwx 1 root root       21 Jan 30 02:55 libswscale.so -> libswscale.so.4.1.100
lrwxrwxrwx 1 root root       21 Jan 30 02:55 libswscale.so.4 -> libswscale.so.4.1.100
-rwxr-xr-x 1 root root   393680 Jan 30 02:55 libswscale.so.4.1.100
```
which seems to be the same output as for you.

**Comment by jehutting** [comment]
_Apparently_ a stream server needs to support tcp... 

So now the question is: why don't these `avdict` options stimeout/timeout work on your (own) stream? Are these options only meant for the TCP protocol?

**Comment by johannesjansson** [comment]
Hi, should I close this issue? From what I can see the issue seems to lie within ffmpeg or my rtsp server right?

**Comment by jehutting** [comment]
Hi @johannesjansson,
Yesterday, I looked into the FFmpeg code. I can't figure out if these `stimeout` or `timeout` parameters work only for tcp. Can't find a good public 24-hours live rtsp stream either to test the parameters. So, yes close it if you can't test it with your stream.
