### ISSUE TITLE
mp4 fadein and fadeout flickering on the white spaces

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#553]
Hi, today I discovered that the fadein and fade out effects are flickering with evidence on the white spaces, here you can find a demo video:
nothing change if I use 25 or 30 fbps or if I use 0.7 or 12 mbps.
The videos are generated with ffmpeg, using the h264 codec.
It didn't help to use -y, -z, -r .
Using the command line -r, the slides are more clean, but then the clickering during the fades are more spike, like this demo:
all the flickerings are not horizontal or vertical , but all in diagonal, and always the smae direction.
I suppose now that the problem is caused from the codec.
I know that omxplayer is suppoting these file types: mp4,avi,mkv,mp3,mov,mpg,flv,m4v
but I don't know which codecs are supported with omxplayer, I hope that you can help me in it.

this is the original file
http://185.24.234.250/ffmpeg-test/vertical-close-to-real.mp4
and this is how I see it on my raspberry pi 3 model b with gpu:128mb
https://www.baramadori.tk/1.3gpp

I am using  this version of omxplayer:
```
Build date: Fri, 23 Sep 2016 00:56:49 +0000
        Version   : dfea8c9 [master]
        Repository: https://github.com/popcornmix/omxplayer.git
```
On raspbian jessie with desktop
```
Release date:2017-07-05
Kernel version:4.9
```
data about the mp4 file:
`Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 40.1 MiB
Duration                                 : 48 s 0 ms
Overall bit rate                         : 7 016 kb/s
Writing application                      : Lavf57.56.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 48 s 0 ms
Bit rate                                 : 7 013 kb/s
Nominal bit rate                         : 10 000 kb/s
Width                                    : 1 080 pixels
Height                                   : 1 920 pixels
Display aspect ratio                     : 0.563
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.135
Stream size                              : 40.1 MiB (100%)
Writing library                          : x264 core 148 r2643 5c65704
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=3 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=10000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
`
` Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.56.100
  Duration: 00:00:48.00, start: 0.000000, bitrate: 7015 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], 7013 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler`

**Comment by matteoraggi** [comment]
here the flickering is huge with raspberry pi 3 model b and omxplayer last stable version:
https://www.baramadori.tk/VID_20170707_102129.3gp
how I can patch it? Other videos looks so good..

**Comment by popcornmix** [comment]
Can you provide a sample of the video with the issue?
> http://185.24.234.250/ffmpeg-test/vertical-close-to-real.mp4

is not accessible.

**Comment by matteoraggi** [comment]
thansk for the quick answer, here is a similar demo:
http://185.24.234.250/ffmpeg-test/vertical-fade-out-1-sec.mp4

**Comment by popcornmix** [comment]
Video is playing fine here. I notice video is rotated in the camera recording - was that a different video or are you rotating video from command line?
Please list any non-standard command line options you are using.

**Comment by matteoraggi** [comment]
here:  /boot/config.txt
I added these lines to show the vertical video in fullscreen:
```
#VERTICAL - PORTRAIT
framebuffer_width=1080
framebuffer_height=1920
display_rotate=1 
gpu_mem=128
```
I cleaned space on raspberry with thsi command:
```
sudo apt-get remove --purge libreoffice* dillo penguinspuzzle minecraft-pi wolfram-engine sonic-pi scratch && sudo apt-get clean && sudo apt-get autoremove
#downloaded package files (.deb files) are kept in  /var/cache/apt/archives. You can remove these in order to free up space with:
sudo apt-get clean
```
nothing else, for the rest it is rapsbian using htpdate to sync the time.. no more.

**Comment by popcornmix** [comment]
display_rotate will cause the issue.
See: https://github.com/raspberrypi/firmware/issues/837

Try removing display_rotate and playing the video with
``omxplayer --orientation 90 dell/codecs/vertical-fade-out-1-sec.mp4``

**Comment by matteoraggi** [comment]
thanks, now it works well!
