### ISSUE TITLE
Peak/Beat detector via DBUS

### ISSUE THREAD

**Issue by Mark-81** [popcornmix/omxplayer#558]
Hi! Do you think it's possible to fork the code to add a beat (or peak) detector on the audio layer using DBUS?
In my application I want to receive a message every time a beat (or peak) is detected in other to sync other tasks. 

My idea is to process the audio samples just before send them to the output device. 
Any help to find the right function where I should put my code?

**Comment by popcornmix** [comment]
This is far outside of the scope of omxplayer.
Feel free to fork the repo and add support, but it is not something I will be adding.

If you want to do this, then at this point:
https://github.com/popcornmix/omxplayer/blob/master/OMXPlayerAudio.cpp#L256

you have decoded audio in ``decoded``buffer with size ``decoded_size``.
You can process that buffer how you want.
These audio samples won't be played immediately, but get queued up after being sent to GPU.
You should have a couple of seconds of audio queued after the queue has filled up (you can adjust amount of data queued with command line flags), so you can send a message that arrives before audio is heard.

**Comment by Mark-81** [comment]
Thanks for the answer! I would have imagined that it's far beyond the scope of omxplayer. Anyway your hint is more than enough!
