### ISSUE TITLE
(DBUS) What is the difference between Stop and Quit?

### ISSUE THREAD

**Issue by anselanza** [popcornmix/omxplayer#564]
I am maintaining a library which uses a modified version of the example `dbuscontrol.sh` (https://github.com/popcornmix/omxplayer/blob/master/dbuscontrol.sh).

The documentation seems to suggest that there is a **difference** between sending a *Stop* command and sending a *Quit* command. Specifically, the documentation says for the Play command:

> Play the video. If the video is playing, it has no effect, if it is paused it will play from current position and if it is stopped it will play from the beginning.

However, sending a "Play" command has no effect whatsoever after "Stop", since it appears that the omxplayer instance always *quits* on a Stop command. `ps aux | grep omxplayer` confirms this.

Is there something I'm missing? Or is the documentation just misleading (i.e. Stop and Quit actually do the same thing, and Play will only "resume" a video that is paused). Is there really a "stopped" state for omxplayer at all?

For reference, here are the commands I'm sending:
```
dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer_layer0 /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop >/dev/null

dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer_layer0 /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Quit

dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer_layer0 /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play >/dev/null
```

**Comment by jehutting** [comment]
Stop and Quit perform the same action ```KeyConfig::ACTION_EXIT``` (see OMXControl.cpp), an exit (/termination) of OMXPlayer.

There is no state Stopped (PlaybackStatus only responds with "Paused" or "Playing").

The Play documentation regarding _if it is stopped it will play from the beginning_ is incorrect.

**Comment by anselanza** [comment]
I have submitted a pull request to resolve this in the docs.
