### ISSUE TITLE
version jessie and stretch

### ISSUE THREAD

**Issue by bhong2002** [popcornmix/omxplayer#575]
hi,, 

1) is there any version that can compile for jessie(2017-07-05) version?   

2) i have a "stretch version dated "09-07-2017" and tried to compile the "e9b33e5 [master] build" and there is a message :

make: omxplayer.bin: Command not found
Makefile:55: recipe for target 'omxplayer.bin' failed
make: *** [omxplayer.bin] Error 127

is there any solution for this?

thanks :)

**Comment by popcornmix** [comment]
I've just checked out a clean tree of omxplayer and ran:
```
./prepare-native-raspbian.sh
make ffmpeg
make -j$(nproc)
```
(as described in README)
All seems to be fine. What commands are you entering?

**Comment by jehutting** [comment]
The $(STRIP) on line 56 of the Makefile is undefined.
Replacing it by just 'strip' will probably fix your issue.

$(SDKSTAGE) is also not defined, but that one can be simply removed.

Notice that @yy502 has added in pull-request 574 an install and uninstall target (which are not pulled-in yet) in case you want to make your compiled version the one-and-only.

**Comment by bhong2002** [comment]
Done! :) thanks @jehutting ....

**Comment by popcornmix** [comment]
SDKSTAGE is fine undefined.
@bhong2002 does adding ``STRIP ?= strip`` near top of ``Makefile`` (and leaving the ``$(STRIP)`` in place also work ok?

**Comment by bhong2002** [comment]
yes sir @jehutting . .  replacing $(STRIP) to strip works .. i didn't edit the SDKSTAGE...

but in command "sudo make install".. the response is:
>make: *** No rule to make target 'install'.  Stop.

so i copied the needed files manualy to /usr folder..
any way...  it works :)

thanks again :)

**Comment by yy502** [comment]
@bhong2002 the `make install` issue is addressed in PR#574

**Comment by jehutting** [comment]
@bhong2002 Good to see that it works... but...

popcornmix wants you to put `STRIP ?= strip` near top of `Makefile`

e.g
```
INCLUDES+=-I./ -Ilinux -Iffmpeg_compiled/usr/local/include/ -I /usr/include/dbus-1.0 -I /usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/freetype2 -isystem$(SDKSTAGE)/opt/vc/include -isystem$(SDKSTAGE)/opt/vc/include/interface/vcos/pthreads

STRIP ?= strip

DIST ?= omxplayer-dist
```

and leave Makefile line 56 to
```
	$(STRIP) omxplayer.bin
```
And don't touch the SDKSTAGE parts :-)

Does it still works for you?

The missing install/uninstall targets looks like
```
install:
	cp -r \$(DIST)/* /

uninstall:
	rm -rf /usr/bin/omxplayer
	rm -rf /usr/bin/omxplayer.bin
	rm -rf /usr/lib/omxplayer
	rm -rf /usr/share/doc/omxplayer
	rm -rf /usr/share/man/man1/omxplayer.1
```
As I said already, needs to be pulled in from @yy502 in pull-request 574 .

Thanks to you too!!!

**Comment by bhong2002** [comment]
sir @jehutting ...  got the new file "Makefile" without editing... 
it works perfect.. :)

thanks :)

**Comment by popcornmix** [comment]
I've pushed a patch that should reinstate the ``make install`` target.
Is all okay now without manual patches?

**Comment by bhong2002** [comment]
I've tested latest "Makefile" ... and it is okay for my "Raspbian stretch(9)" OS ...

thanks :)

**Comment by popcornmix** [comment]
Ok to close the issue now?

**Comment by bhong2002** [comment]
ok sir @popcornmix... thanks a lot :)
