### ISSUE TITLE
Cannot run two instances of omxplayer with -o alsa

### ISSUE THREAD

**Issue by KenT2** [popcornmix/omxplayer#579]
Run one instance from a terminal window. While it is playing try to 
run a second instance of omxplayer from another terminal window with different --win parameters. This second instance will not play.

Thought this was another incarnation of #317 but its not related to pause.

**Comment by jehutting** [comment]
Do you already use the ALSA dmixer configuration?

Otherwise try it with mine `.asoundrc` ALSA configuration file (placed in my home directory):
```
pcm.!default {
type plug
slave.pcm "dmixer"
}

pcm.dsp0 {
type plug
slave.pcm "dmixer"
}

pcm.dmixer {
type dmix
ipc_key 1024 # the key must be unique
ipc_key_add_uid 0
ipc_perm 0666# permissions - octal notation
slave {
pcm "hw:1,0"               # <<<<--- see cat /proc/asound/cards
period_time 0
period_size 1024
buffer_size 8192
rate 48000 #or 44100
}
}

ctl.dmixer {
type hw
card 1                      # <<<<--- see cat /proc/asound/cards
}
```
_I can't remember where I got it from :-)_

At my Stretch Raspbian **and using ssh'ed terminals** it works fine.

**Comment by KenT2** [comment]
I was just using Raspbian out of the box.
Your .asoundrc works fine. Jozef has come up trumps yet again as us British say.

If anyone uses this with the Pixel desktop be aware that right clicking on the loudspeaker icon on the task bar and selecting a sound device will overwrite this file with something generated by Raspbian.
