### ISSUE TITLE
voice stretching when playback speed changes

### ISSUE THREAD

**Issue by yy502** [popcornmix/omxplayer#581]
It is possible to add voice stretching (to maintain the pitch) when playing faster or slower than normal speed?

And, can we have more playback speed options? e.g. x0.5 to x2.0 with 1/8 or 1/10 step size

**Comment by popcornmix** [comment]
No, these aren't features supported by the gpu based videoplayer.
These features are supported by more advanced software like kodi.

**Comment by yy502** [comment]
ok, thanks for the explanation.
