### ISSUE TITLE
Rest API or Java JNI wrapper

### ISSUE THREAD

**Issue by jbescos** [popcornmix/omxplayer#607]
Hello,

The app is very good, but I miss some way to be able to control it from Java.

Could you consider to make a Java wrapper (like in the next link for VLC), please?:
https://github.com/caprica/vlcj

Providing a rest API would be awesome too.

Many thanks,
Jorge

**Comment by tmontes** [comment]
@jbescos,

You should be able to use a Java based DBus client to control OMXPlayer. For simple DBus based player control, refer to:
* https://github.com/popcornmix/omxplayer/#dbus-control
* https://github.com/popcornmix/omxplayer/blob/master/dbuscontrol.sh

I imagine there will be more than one DBus client implementation in Java.
