### ISSUE TITLE
Urgent: Please help with USB sound

### ISSUE THREAD

**Issue by yanone** [popcornmix/omxplayer#609]
Hi there,

I need to set up a Raspberry Pi with a seamless video loop using an external USB sound card for audio quality.

The video plays fine without sound output options, and audio plays fine over HDMI, so decoding issues can be ruled out.

Running `omxplayer -o alsa:hw:1,0 aac.mov` will not play back the video and print the following output:
```
Video codec omx-h264 width 1920 height 1080 profile 100 fps 25.000000
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1920x1080@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
```
and that's it.

I'm guessing my sound card is `1,0` from the output of `aplay -l`, which returns 
```
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: AG06AG03 [AG06/AG03], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
The last device is my target sound card.

And the same happens when I set the sound card in the system, then just play `omxplayer -o alsa aac.mov`

Also, the sound card plays audio when used from VLC or the browser, for instance, so this one also generally works.

What am I doing wrong?
I used both the preinstalled version of `omxplayer`, as well as just compiled my own from your sources.

Your help is greatly appreciated.
Thank you

**Comment by yanone** [comment]
Okay, found it.
It was related to ALSA settings.
I'm closing this. Sorry for the inconvenience.

**Comment by tanabarbier** [comment]
Hi !
I have exactly that same problem, I am trying to loop a video with 4 channels audio (mp4), I tried with Mplayer but when looping it looses audio on repeats, so I try with omxplayer and I can't make it use more than 2 channels. What did you do to the also settings ?
