### ISSUE TITLE
I can select PGS subtitles, but I can't view them

### ISSUE THREAD

**Issue by afontenot** [popcornmix/omxplayer#616]
I have a number of files with embedded PGS subtitles (i.e. images instead of utf-8 tracks). I can toggle on subtitles, and select all the different tracks (I see the popup saying something like "sub track 1 selected"). But none of them ever show up. I can confirm that the subtitles on all these files work in VLC.

So far as I can tell this is likely a bug - I can't find any indication that PGS subtitles aren't supported. I have a pretty standard up-to-date Raspbian install on a Pi 3B, so this shouldn't be hard to replicate. I'm happy to provide any additional information as needed.

**Comment by popcornmix** [comment]
omxplayer is a basic player. It has no support for graphical subtitles.
If you need this feature then kodi would be recommended which does support them.

**Comment by afontenot** [comment]
I can't use Kodi (at least not easily) because the Pi is fully headless, controlled only over ssh. Maybe there's a way to do it with another terminal-based player?

Also, it would be good to have a note about this limitation (and perhaps others?) placed somewhere prominent. I have spent many hours trying to debug this non-issue before reporting it here.

**Comment by popcornmix** [comment]
You can certainly launch playback of files in kodi over ssh (https://kodi.wiki/view/JSON-RPC_API/v8)
Check [texturecache.py play](https://github.com/MilhouseVH/texturecache.py) for an example.
There can also control kodi remotely through a browser or phone app.

**Comment by afontenot** [comment]
Thanks for this. Last time I tried to use Kodi was right around the end of the time it was still called XBMC. At the time it's performance and abilities left a lot to be desired and left me with a bad taste, but I'm happy to say after trying it out recently it has very much improved. I'd still hope for a standalone mmal player, but Kodi will do for now. I'll close this issue.

**Comment by killerkalamari** [comment]
I have a question on this issue. I haven't looked extensively, but from what I can tell, the code is taking the srt and rendering to a bitmap. Assuming I added code that could decode PGS subtitles to a bitmap, is there any reason I couldn't get omxplayer to display that in the same way as the rendered srt bitmaps, or are there extra complications that I'm not considering? If I can pull it off, would it be a welcome addition to omxplayer?

**Comment by popcornmix** [comment]
What you suggest is possible. If you can get PGS subtitles rendered to a bitmap is should be possible to display them.

The current subtitle code actually uses OpenVG for display, but that interface is deprecated as it isn't supported with the arm-side VC4 GL driver which we will eventually move to.

Using dispmanx is probably the easiest way of overlaying bitmaps on the video (see /opt/vc/src/hello_pi/hello_dispmanx). I did start converting the OpenVG Freetype rendering to use a bitmap on a dispmanx layer but haven't had time to complete that.

I'm not planning to support PGS (or other bitmap subtitle formats) myself, but would be happy to accept a pull request that offers that support.
