### ISSUE TITLE
Split second playback stall on rewind

### ISSUE THREAD

**Issue by tmontes** [popcornmix/omxplayer#618]
### Context

Hello and thanks for omxplayer.

I've been working on an interactive video playing project (https://github.com/nununo/pyCandle2017) that spawns several omxplayer processes, controlling their playback/paused states and video cross-fades via DBus. This has been very successful so far.

The videos themselves are variations of a burning candle video which are played-back depending on external inputs, so as to present an interactive experience where, for example, blowing into the "screen" plays back the corresponding video with the burning candle video flickering appropriately.

I've recently faced a scenario where a given playing video should be simply rewound to continue playing from the start with no cross-fades or any other visual transitions.

### Observed behaviour

The implementation calls `SetPosition` with `0`, via DBus, to rewind the omxplayer.

On rewind, the video playback seems to stall for a split second before going back to the start, leading to an unnatural video experience.

### Desired behaviour

Rewinding a playing video should keep playing at the same frame rate, with no visible stalls.

### Diagnostics

Faced with this, I decided to dig further:
* Playing from the command line with a simple `omxplayer <file>` and hitting `i` for *previous chapter* (or `left arrow` for *seek -30 seconds*) shows the same behaviour: the playback stalls for a split second.
* I then tried re-encoding the video file with combinations of:
  * 100% I-Frames.
  * Higher framerate, from the original 25 up to 60.
  * Calling `omxplayer` with `--fps 60`.
  * Lower bitrate, from the original ~5Mbps down to ~1Mbps.
  * Still getting the split second playback stall in all combinations of these cases.

One clue I found:
* Playing from the command line with `omxplayer <file>` with the original 25fps file.
* Speeding playback to 4x by hitting `.` twice.
* Rewinding with `i` then seems to play with no noticeable stall (or maybe it now stalls for 1/4th the time which is no longer noticeable).

### Request

With this information I believe there must be something I've been missing all along: if when playing at 4x the speed rewinding is "fast enough", why shouldn't it be when playing at 1x?

Thanks in advance for any pointers anyone may share.

### Techical details

Raspbian:
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

omxplayer:
```
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Wed, 05 Jul 2017 16:40:39 +0100
        Version   : 5a25a57 [debian]
        Repository: git@github.com:XECDesign/omxplayer.git
```

video files:
* H.264 encoded.
* 1280x720.
* 25fps.
* ~5Mbps bitrate.

**Comment by popcornmix** [comment]
I'm not sure what you want is possible from omxplayer. When seeking any video/audio buffers are discarded and need to be refilled sufficiently (by reading the file) before playback can resume again.

The option that could help is
```
--threshold   n         Amount of buffered data required to finish buffering [s]
```
The default is 0.2s. Try setting to a small value (e.g. 0.01) but you may find playback is unable to start smoothly if this is too small.

If you are just playing video with no audio, something simplet like hello_video may be a better option.
https://www.raspberrypi.org/forums/viewtopic.php?t=8042

**Comment by tmontes** [comment]
Update:
* We've addressed this limitation with a different approach in our project.
* Closing this issue since it is no longer "critical" for us.
* Also not to create unnecessary "open issue" load here.

Thanks again. :)
