### ISSUE TITLE
Chapter seeking on .mov stops working after first "next chapter"

### ISSUE THREAD

**Issue by johnpurlia** [popcornmix/omxplayer#623]
I'm encountering a problem with omxplayer (version 68961b3) seeking to the next chapter using the 'o' keyboard command. After my video has launched, the first keypress to advance to the next chapter works perfectly. All subsequent keypresses either go to chapter 0, or are ignored. Additionally, commands to advance the playhead 30 seconds following that first successful "next chapter" are ignored or result in odd behavior (video freezing or audio out of sync).

The video is a 32 minute .mov with two chapters and omxplayer is launched to loop.

Here's the info about the file from omxplayer:

pi@raspberrypi:~ $ omxplayer -i /home/pi/Videos/chapters.mov
Chapter : 	0 	Chapter 1 	    0.00
Chapter : 	1 	Chapter 2 	 1801.00
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/pi/Videos/tt.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2018-03-22T05:33:39.000000Z
    com.apple.quicktime.player.movie.audio.gain: 1.000000
    com.apple.quicktime.player.movie.audio.treble: 0.000000
    com.apple.quicktime.player.movie.audio.bass: 0.000000
    com.apple.quicktime.player.movie.audio.balance: 0.000000
    com.apple.quicktime.player.movie.audio.pitchshift: 0.000000
    com.apple.quicktime.player.movie.audio.mute: 
    com.apple.quicktime.player.movie.visual.brightness: 0.000000
    com.apple.quicktime.player.movie.visual.color: 1.000000
    com.apple.quicktime.player.movie.visual.tint: 0.000000
    com.apple.quicktime.player.movie.visual.contrast: 1.000000
    com.apple.quicktime.player.version: 7.6.6 (7.6.6)
    com.apple.quicktime.version: 7.7.3 (3014) 0x7738000 (Mac OS X, 10.13.3, 17D102)
  Duration: 00:39:32.20, start: 0.000000, bitrate: 13715 kb/s
    Chapter #0:0: start 0.000000, end 1801.950000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 1801.950000, end 2372.200000
    Metadata:
      title           : Chapter 2
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 105 kb/s (default)
    Metadata:
      creation_time   : 2018-03-22T05:33:39.000000Z
      handler_name    : Apple Alias Data Handler
    Stream #0:1: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 13603 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 60k tbc (default)
    Metadata:
      creation_time   : 2018-03-22T05:33:39.000000Z
      handler_name    : Apple Alias Data Handler
    Stream #0:2(eng): Data: bin_data (text / 0x74786574)
    Metadata:
      creation_time   : 2018-03-22T05:33:39.000000Z
      handler_name    : Apple Alias Data Handler
have a nice day ;)

**Comment by johnpurlia** [comment]
Providing a little more information...

It would appear that the problem occurs because m_iCurrentPts, gets set to an outrageously large value, which causes GetChapter to always return 0. This super big value is set in UpdateCurrentPTS when walking through the available streams and setting m_iCurrentPts to the cur_dts of Stream #2, which is a text stream present (but disabled) in the .mov file. That text track was used to create the file's chapter markers, but does not appear during playback.

**Comment by jehutting** [comment]
Same issue as #464 ?

**Comment by johnpurlia** [comment]
Yep, it appears to be the same problem. The stream with the out of bounds cur_dts is of type AVMEDIA_TYPE_DATA. The values for the audio and video streams are fine, but I've yet to determine when and how the value for this stream is being set.
