### ISSUE TITLE
OMXPlayer becomes unresponsive when activating GPIO

### ISSUE THREAD

**Issue by madmodder123** [popcornmix/omxplayer#627]
So I have OMXPlayer play a video splash screen when I boot up my Raspberry Pi (Using RetroPie).
I also have a PC speaker connected via GPIO that beeps during the boot process.
One of these: https://images-na.ssl-images-amazon.com/images/I/31dXtOoEJnL._SX355_.jpg

As soon as the speaker beeps the audio from the video just stops, the video continues, but when the the video reaches the end OMXPlayer just stays on the last frame of the video and never exits.
If I use "sudo killall omxplayer.bin" I am able to kill OMXPlayer and continue using my Pi without issue.

The code I am using (which starts with rc.local):
```
# variable for tone
note=76

# play tone function
tone () {
  local note="$1"
  if test "$note" -eq 0; then
    gpio -g mode 18 in
  else
    local period="$(perl -e"printf'%.0f',600000/440/2**(( $note-69)/12 )")"
    gpio -g mode 18 pwm # this seems to be the line that causes the issue
    gpio pwmr "$(( period ))"
    gpio -g pwm 18 "$(( period/2 ))"
    gpio pwm-ms
  fi
}

tone $note
sleep 0.1
tone 0
```

I can get this issue to reproduce 100% of the time, If I add a sleep to the beginning of the code I can have it happen at anytime during the video.
A tried moving the script to the top of the rc.local file so it runs first, but this issue still occurs (with a roughly 75% reproduction rate, even after adding a sleep command to the video splash screen).

I also tried running OMXPlayer and the script after the Pi has fully booted and the issue still repros.

Here is the command I am using btw:
`omxplayer --aspect-mode fill -o both -b --layer 10000 /home/pi/RetroPie/splashscreens/intro_video.mp4`

Any ideas why OMXPlayer doesn't like GPIO?

**Comment by jehutting** [comment]
See [Troubles with PWM and Audio](https://www.raspberrypi.org/forums/viewtopic.php?t=70308#p509985): the local (/jack plug) output makes already use of the pwm interface, and therefore it can't be used for your gpio tone. 

Follow the advise in the answer to use a software pwm library.

**Comment by Ruffio** [comment]
So this issue can be closed as it has been resolved, right?

**Comment by madmodder123** [comment]
@Ruffio Yes, it is unrelated to OMXPlayer
