### ISSUE TITLE
Non-latin characters display as question marks with white boxes (v0.3.7 23/09/2016)

### ISSUE THREAD

**Issue by rixwoodling** [popcornmix/omxplayer#640]
Subtitles in a foreign language such as Chinese, display as white boxes with question marks inside. I am certain the .srt files are encoded into utf-8: text/plain; charset=utf-8

Is this a font issue?

These are some of my specs if it helps any:
/boot/config.txt : gpu_mem=128
/boot/config.txt : hdmi_drive=2
uname -a : Linux 4.1.18+ #846 Thu Feb 25 14:11:56 GMT 2016 armv6l GNU/Linux
video file: .mp4 x264, aac, .srt utf-8 (chinese)

**Comment by torarin** [comment]
Probably a font issue yes, all subtitles are interpreted as utf-8. Can you try setting another font with the --font and --italic-font options?

**Comment by rixwoodling** [comment]
I tried a few fonts, especially various Chinese fonts, that i needed. It looked like i needed to install a specific fonts package:

sudo apt-get install fonts-arphic-ukai

after that, now i could use the --font command and point to the font file.
omxplayer -o hdmi --font /usr/share/fonts/truetype/arphic/ukai.ttc --align center --font-size 75 --no-ghost-box --subtitles *.srt *.mp4

All is good. Case closed!
