### ISSUE TITLE
audio broken in low-gap playback mode

### ISSUE THREAD

**Issue by clarkewd** [popcornmix/omxplayer#646]
After speaking with @subogero about https://github.com/subogero/omxd/issues/82 he advised that there is a bug with audio in low-gap playback mode when output is set to `hdmi`

It appears this bug now also affects output via the jack when the setting is `-olocal`

I've also had some issues with volume being too low and noise. All of these issues seem to go away if I'm not using low-gap mode.

In spite of this, `omxplayer` is still awesome, so thank you.

**Comment by popcornmix** [comment]
Does adding ``audio_pwm_mode=0`` to config.txt have any effect?

**Comment by clarkewd** [comment]
Seems to help with the volume and noise issues but not with the audio. As mentioned  at https://github.com/subogero/omxd/issues/82 the audio starts to "work" if I pause and then unpause after changing tracks or appending to the playlist.

But the low-gap playback mode with two `omxplayer` processes does not really work correctly even with `audio_pwm_mode=0`

Still have no audio unless I do some workaround like pause/unpause or kill one of the processes.
