### ISSUE TITLE
Unable to compile: dbus/dbus.h missing

### ISSUE THREAD

**Issue by dmcelectrico** [popcornmix/omxplayer#65]
Hello there,

Compiling on the pi (old raspbian installation but up to date). 

Just cloned the repository, executed prepare-native-raspbian.sh, make ffmpeg, make, and this compiling error pops:

OMXControl.cpp:7:23: fatal error: dbus/dbus.h: No such file or directory
compilation terminated.

I had no problems compiling it three months ago by those steps (still wrote on the readme).

I suppose I'm missing something. Thank you for your help.

**Comment by Ruffio** [comment]
@dmcelectrico is this still an issue?

**Comment by dmcelectrico** [comment]
@Ruffio Just checked on a fresh Raspbian installation that everything compiled OK following the instructions. The issue is gone  : )
