### ISSUE TITLE
ToOMXTime

### ISSUE THREAD

**Issue by TomMettam** [popcornmix/omxplayer#662]
It seems that the pts value passed into this function is completely overwritten and ignored, is this intentional?

```
static inline OMX_TICKS ToOMXTime(int64_t pts)
{
    OMX_TICKS ticks;
    int64_t pts = ticks.nLowPart | ((uint64_t)(ticks.nHighPart) << 32);
    return pts;
}
```

**Comment by jehutting** [comment]
Yes that seems to be a little bit wrong :-)

Luckily omxplayer uses (from ```OMXClock.h```)
```
static inline OMX_TICKS ToOMXTime(int64_t pts)
{
  OMX_TICKS ticks;
  ticks.nLowPart = pts;
  ticks.nHighPart = pts >> 32;
  return ticks;
}
```
Where did you got that code from?

**Comment by TomMettam** [comment]
Aha, you know what, I did a search for ToOMXTime and got this:

https://gyazo.com/1d4b8ab9f518fd973c6746c2614c6f93

My bad.. I didn't notice the line break..
