### ISSUE TITLE
build issues with OMX_DISPLAY_ALPHA_FLAGS_DISCARD_LOWER_LAYERS

### ISSUE THREAD

**Issue by tlemmons** [popcornmix/omxplayer#664]
I am trying to build the latest and I get an issue that error: ‘OMX_DISPLAY_ALPHA_FLAGS_DISCARD_LOWER_LAYERS’ was not declared in this scope.  I have traced it back to the structure OMX_CONFIG_DISPLAYREGIONTYPE which I cannot find in my code set either.  Have I missed a dependency or can anyone point me to how to fix the issue.

Thanks in advance!

**Comment by popcornmix** [comment]
You need the latest firmware for this update.
Either use the headers from userland repo, or make sure firmware headers are latest (rpi-update definitely is new enough - apt version may or may not be).

**Comment by tlemmons** [comment]
Thanks.  I will try an update.

**Comment by tlemmons** [comment]
Great,  that fixed it.  Now I have to deal with other issues that an update causes me, but I knew I had to eventually.  I really appreciate the fast response!

**Comment by poisonousgoat** [comment]
Saw the same issue, did
```bassh
sudo apt-get update
sudo apt-get dist-upgrade
```
and nothing but a reboot to make it work like every other elite raspberry pi out there with an omxplayer
