### ISSUE TITLE
Monitoring player latency

### ISSUE THREAD

**Issue by damarre89** [popcornmix/omxplayer#667]
Hi all,

First of all thanks for this fork of omxplayer, its performance is great! 

I am writing some code to compare live streams from RTP. I have modified some of the source code to get the stream's pts and dts (in ffmpeg/libavcodec/h264_parser.c seems to be the streams's values of PTS and DTS). After running the code in two RPi and printing these values (both with the same RTP source in a wired lan), they are common and appear simultaneously, but the displayed frame is not the same (even with a difference of >1s). So I assume I print those PTS values at the reception of the stream and the internal latency of each player is the cause which makes that difference in the displayed content. To monitor and quantify this delay, I have checked and calculated some latency-related variables: 
1- monitoring the video buffer level (in seconds) from the '-s' input option
2- substracting the runtime value from the '-s' input option minus the pkt->pts value from OMXPlayerVideo
3- substracting the runtime value from m_av_clock->OMXMediaTime() minus the pkt->pts value from OMXPlayerVideo

These three different calculations have very similar values but are not exactly the same (they vary tens of milliseconds, which is not relevant for my purpose). Either way, those calculations seem not to be accurate enough, as the calculated asynchrony value between the two RPi does not reflect the perceived frame differences between players (the latter is significantly higher). I am sure I am missing some variables but I am unable to find them. Where or how should I monitor the latency value correctly?

Many thanks in advance

**Comment by popcornmix** [comment]
There may be a few seconds of video frames buffered in decoder.
The difference between pts value read from demuxer and OMXMediaTime() should be the latency.

Try enabling live mode (--live) and looking at https://github.com/popcornmix/omxplayer/blob/master/omxplayer.cpp#L1731

**Comment by popcornmix** [comment]
While paused OMXMediaTime will stop progressing.
If there is room in the gpu fifos more data will be read from file and queued up in these fifos. It depends on the bitrate of the file how much the latency will increase by. For a low bitrate file it may increase by more than two seconds during a 2 second pause.
If the "file" is actually a live stream, then you generally can't read faster than real time, so increasing latency by about 2 seconds is likely (but it may be a little more or less depending exactly on how much data is currently queued up in network stack).

**Comment by damarre89** [comment]
Ok, thank you very much for the information!

BR
