### ISSUE TITLE
the output of `omxplayer -i xxx.mp4` could not be grep ?

### ISSUE THREAD

**Issue by msongz** [popcornmix/omxplayer#689]
i want to write a  script to get the info of the video resolution, but find the -i could not be grep

**Comment by popcornmix** [comment]
This is really a bash question rather than an omxplayer question.
Output goes to stderr, so normal `|` won't work.  Try:
```omxplayer -i sample.mkv |& grep Stream```

**Comment by msongz** [comment]
sorry for ask a bash question 😫
