### ISSUE TITLE
Bad keybinding when opening from python/pygame 

### ISSUE THREAD

**Issue by rtomasa** [popcornmix/omxplayer#691]
I found out that when you run omxplayer from within a python+pygame program, the key mapping is completely messed up. i.e:
```javascript
os.system('omxplayer -b "' + videofile + '"')
```
Only a few keys are working with wrong mappings. i.e.: d > play/pause, + > quit

I'm on raspbian stretch.

**Comment by jehutting** [comment]
Tried

```
import os

videofile = xxx
os.system('omxplayer -b "' + videofile + '"')
```
which gave me the correct action on the keybindings (space gave pause, arrow left gave forward movement, - gave volume down, + gave volume up).

Add -g (for logging) to your command and have a look at oxmplayer.log for lines as
```
xxxx DEBUG: Keyboard: character q (0x71)
```

If possible post (or PM) your code.

**Comment by rtomasa** [comment]
Posting the original code is almost impossible due to the complexity of the same but the main idea is the following:

```
# -*- coding: utf-8 -*-
import pygame, os
from pygame.locals import *

def main():
    # Initialise screen
    pygame.init()
    pygame.mouse.set_visible(0)
    pygame.key.set_repeat()
    screen = pygame.display.set_mode((320, 240))
    pygame.display.set_caption('Test Program')
    fpsClock = pygame.time.Clock()

    ''' Fill background '''
    background = pygame.Surface(screen.get_size())
    background = background.convert()
    background.fill((0, 0, 128))

    ''' Event loop '''
    while True:
        for event in pygame.event.get():
            pressed = pygame.key.get_pressed()

            if event.type == QUIT:
                return
            
            if pressed[pygame.K_v]:
                # Video
                videofile = xxx
                os.system('omxplayer -b "' + videofile + '"')

        ''' Blit everything to the screen '''
        screen.blit(background, (0, 0))
        pygame.display.update()
        fpsClock.tick(30)

if __name__ == '__main__': main()
```

Also very important to note that I'm on raspbian (raspberry hardware).

I was able to get the log file and create a custom working mapping, but keys from the log file were crazy and the only choice was to use HEX codes from there. Maybe when running from pygame there is something wrong when executing inside the main event loop and the pygame key events.

**Comment by jehutting** [comment]
Thanks. Your example is good enough to play with.

I don't understand what you mean by

>  ...and create a custom working mapping, but keys from the log file were crazy and the only choice was to use HEX codes from there.

When I am ssh'ed to my RPi, and run your script, a key 'v' starts playing the video.When I press a key  OMXPlayer doesn't get the key; so when pressing the space bar OMXPlayer doesn't pause. I don't see any logging of keys either. Only when I select the console (window), a key pressed goes to OMXPlayer, so pausing on the space key.

So _what I make out of my setup_, ```os.system()``` gets the stdin stream from the (by the os.sytem() started) shell stdin, which is the console stdin; this stdin is the same for pygame key input. 

Maybe you can describe your (hardware/system) setup. E,g, how do you start the script, from boot, or from (main rpi) console or ssh-console, keyboard connected? Is your (actual) call to ```os.system()``` from within a thread? 

Perhaps python's ```subprocess``` gives a better solution (pygame keys sending to the stdin of the  OMXPlayer process), or use ```python-omxplayer-wrapper```.

Although it is an interesting thing to know, I don't think it is an issue of OMXPlayer. You may be better off on the RPI forum. Anyway, describe your setup in more details.

**Comment by rtomasa** [comment]
Closing this old post. BTW I finally ended up developing an integration using OMXPlayer DBUS service.
