### ISSUE TITLE
DBUS error: Service Unknown

### ISSUE THREAD

**Issue by piggeywig2000** [popcornmix/omxplayer#695]
Before I start, I just want to say that I am very new to Linux, so I apologize if I'm asking something that's trivial.

I am using omxplayer that was preinstalled on raspbian on my raspberry pi. I would like to use DBUS to interact with omxplayer without the CLI.

If I run the dbuscontrol.sh script using
`./dbuscontrol.sh openuri "music.mp3"`
I get the error
`Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files`

I get the same error if I run the command directly
`dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri string:"music.mp3" >/dev/null`

However, if I run omxplayer normally with the CLI using
`omxplayer -o local music.mp3`
it works as expected

I have no idea how .service files work. Again, I apologize if this should be obvious.
Thanks,
piggeywig2000

**Comment by piggeywig2000** [comment]
So I've just found out that if I run the script while omxplayer is running in another window, it works just fine. 

So I guess my question now is: Can I make omxplayer open a file using DBUS without it already running, or is this just not possible? I ask this because I would like to be able to interact with omxplayer using C#

**Comment by jehutting** [comment]
No, it isn't possible to start OMXPlayer by running one of its D-Bus commands. Only when there is a running OMXPlayer, you have the org.mpris.MediaPlayer2.omxplayer service. No OMXPlayer, no service.

You can have a C# program to start a OMXPlayer _Process_ with in its _StartInfo.Arguments_ the name of the movie you want to play. Once the movie is playing you can go with the D-Bus commands to control OMXPlayer.

**Comment by piggeywig2000** [comment]
Cool, I'll do that then. Thanks
