### ISSUE TITLE
Put OMXPlayer below another application (fluxbox)

### ISSUE THREAD

**Issue by samouds** [popcornmix/omxplayer#701]
Hello,

I'm running an application with fluxbox, but when I want to play a video with OMXPlayer it stays above fluxbox. (I'm trying to add an overlay to video playback)

Is there a way to put OMXplayer below fluxbox ?

**Comment by popcornmix** [comment]
```
--layer n               Set video render layer number (higher numbers are on top)
```

Try ``--layer -128``

**Comment by samouds** [comment]
Thanks but when I try to add --layer -128 I can't see the video but just fluxbox.

**Comment by popcornmix** [comment]
Can you try adding to config.txt:
framebuffer_ignore_alpha=0
