### ISSUE TITLE
Incorrect aspect ratio for movies using official 7" LCD screen

### ISSUE THREAD

**Issue by edrozenberg** [popcornmix/omxplayer#706]
Slackware Linux 14.2+ (-current) ARM (hardfp)
omxplayer built from source (2019-01-02 f06235c)

I've read all the previous issues and various postings regarding aspect ratio with omxplayer. None of the suggestions (various combinations of `-r`, `--win`, `--aspect-mode`) work to properly display various movies in their native aspect ratio.

For ex. I have 2 movies:
- Movie 1.mp4 (1280 x 688)
- Movie 2.mp4 (960 x 720)

Without any parameters, `omxplayer` makes both movies too wide. Movie 1 is squished too much vertically (gets big black bars at top and bottom). Movie 2 is stretched sideways to fill the width, and everything looks too wide.

Details:

```
$ tvservice -s
state 0x400000 [LCD], 800x480 @ 60.00Hz, progressive
```

Output playing each movie (movie resolution is correctly detected):

**Movie 1**
```
Video codec omx-h264 width 1280 height 688 profile 100 fps 24.000000
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1280x688@24.00 interlace:0 deinterlace:0 anaglyph:0 par:1.25 display:0 layer:0 alpha:255 aspectMode:0
```

**Movie 2**
```
Video codec omx-h264 width 960 height 720 profile 100 fps 23.976025
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 960x720@23.98 interlace:0 deinterlace:0 anaglyph:0 par:1.25 display:0 layer:0 alpha:255 aspectMode:0
```

The only ugly workaround would be to write a script to:
1. Get movie resolution for the movie user wants to play (`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 mymovie.mp4`)
2. Do math in order to determine the correct coordinates to pass to omxplayer via `--win` such that the movie is correctly sized to fit into the 800x480 LCD resolution

Note that there is no one-size-fits-all value for `--win` - it would need to be set for each movie, based on that movie's WxH. This is because not all movies use the same W/H ratio. Some are 16:9, some 4:3, etc.

**Comment by zmiller90** [comment]
I'm having the same issue, would love a workaround so that pi video looper plays file in correct resolution.... my 720 x720 is being squished and adjusting omxplayer files for strict resolutions isnt working

**Comment by edrozenberg** [comment]
@zmiller90 The omxplayer project is dead - hasn't been updated since last year. Believe the recommendation is to use VLC for ARM now, but I haven't wanted to spend a few days figuring out how to build it properly on my Slackware ARM systems. If you find a ready to use vlc arm package for your OS that's probably the way to go.

**Comment by zmiller90** [comment]
to be honest im pretty new to the pi scene and am trying to accomplish an autoboot/autoplay video looper, but when put on loop VLC has a massive stutter/delay between looping my individual video file (mp4). Any breadcrumbs as to how i might research a workaround to autoboot vlc on powerup to play a file loaded onto my onboard sd in a smoother manner?

**Comment by edrozenberg** [comment]
I wouldn't know where to start sorry, other than VLC forums if there are any. I'm no big fan on VLC actually, use IINA on Mac only, and not doing anything much with Pi's these days. Was fun to tool around with ARM boards but they don't do anything useful or fast enough me. If it's a real need you might consider other small PC's like an Intel NUC running x86 64 Linux.
