### ISSUE TITLE
screesnshot of omxplayer while playing

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#710]
Hi, I tryed to do a screenshot of omxplayer while playing with scrot but it answer that It answer:

> giblib error: Can't open X display. It *is* running, yeah?
and I tryed with raspi2png but it show the desktop and not omxplayr while playing.
I tryed to use this parameter: --display,`-D - Raspberry Pi display number (default 0)` from 0 to 1 and 2 and 3 ... but nothing changed..
Any suggestions?

**Comment by popcornmix** [comment]
I believe raspi2png should do what you want. Are you using the version from here?
https://github.com/AndrewFromMelbourne/raspi2png

**Comment by matteoraggi** [comment]
I am using version 0.8 installed by default on raspbian stretch, and launcching from termianl used from anydesk.

**Comment by popcornmix** [comment]
@AndrewFromMelbourne - this should work shouldn't it?

**Comment by matteoraggi** [comment]
It just show the desktop instead of omxplayer that is playing, a friwend have the solution, I will tell you it into th weekend :-)

**Comment by matteoraggi** [comment]
fro mdataplicity and crontaks it works, from anydesk not instead..

**Comment by matteoraggi** [comment]
anydesk is using a virtual X11 so, that is probably why it cannot take screenshots of anything other than the desktop by default.

**Comment by matteoraggi** [comment]
also anydesk never show omxplayer playing too on the screen too.

**Comment by matteoraggi** [comment]
Ok, all right! I was just launching the scrrenshot on the wrong monitor, raspi2png works perfectly with anydesk to make a screenshot of omxplayer while playing, thanks for the patience :-)
