### ISSUE TITLE
Pi 4 and sync'd video

### ISSUE THREAD

**Issue by exidyboy** [popcornmix/omxplayer#715]
Will it be possible to play a single 8K video spanned across both 4K outputs on the new Raspberry Pi 4?

Will it be possible to sync two separate, but equal length, 4K videos in omxplayer with each video playing on separate micro HDMI outputs?

**Comment by popcornmix** [comment]
omxplayer only supports gpu codecs (like h.264).
It doesn't support the arm side HEVC codec.

So no, not with omxplayer. It may be possible through other software
but it's not something that has been tested.
