### ISSUE TITLE
Pi 4 will not play .mkv video

### ISSUE THREAD

**Issue by KenT2** [popcornmix/omxplayer#733]
Running a .mkv file on a Pi4 with the latest Buster gives this error:

`pi@SD4:~/pp_home/media $ omxplayer suits-short.mkv
Video codec omx-h264 width 1276 height 720 profile 100 fps 23.976025
* failed to add service - already in use?
Audio codec ac3 channels 6 samplerate 48000 bitspersample 16
/usr/bin/omxplayer: line 67:   924 Aborted                 LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
`
Using the same SD card on a Pi3B the video plays OK.

.mp4 files play OK

GPUMEM is 400MB

Config.txt has 

`[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
start_x=1
gpu_mem=400`

File is here if you need it:

[https://github.com/KenT2/pipresents-beep-examples/blob/master/pp_home/media/suits-short.mkv](url)

**Comment by jdonald** [comment]
Well that's exactly how it behaved prior to Buster if you tried running omxplayer with fkms in its default mode. It uses OpenVG for subtitles which required the legacy Broadcom driver.

Try running with `--no-osd` ?

**Comment by KenT2** [comment]
I tried that with no success. I have 20th June omxplayer which is in the latest Raspbian. There has been a bug fix in this area since but I do not know where to get the .deb

**Comment by jdonald** [comment]
Interesting. I was able to reproduce the same issue with your Suits episode mkv after doing `sudo apt install --reinstall omxplayer`, but if I use the one built from source it works fine.

Looks like this was fixed in #728 just a few days ago.

Also, apparently users no longer need to specify `--no-osd` manually. That's handled by fkms auto-detection now.

**Comment by KenT2** [comment]
Fixed by sudo apt-get upgrade to install 01 August version of omxplayer
