### ISSUE TITLE
Play mp4 with custom aspect ratio

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#734]
Is it possible with omxplayer play videos with custom aspect ratio if not goign over the total number of pixel of 1920x1080= 2073600 ? 
If yes then I can also play every video aspect ratio, also 2720x680, right?

**Comment by popcornmix** [comment]
No the hardware decoder has a limit on the width of the image of 1920.

**Comment by matteoraggi** [comment]
Aha, and what about raspberry pi4, it has the same limit with h264 too?

**Comment by popcornmix** [comment]
The h264 hardware hasn't changed for pi4.
