### ISSUE TITLE
omxplayer stops reading STDIN from a FIFO

### ISSUE THREAD

**Issue by prusa3duser** [popcornmix/omxplayer#737]
Version information for this issue is at bottom...

I am trying to control omxplayer playback on raspberry pi remotely, by having its STDIN be a FIFO rather than keyboard.  So, although I am able to get omxplayer playing the media file, the player stops responding to any further keystrokes sent via the FIFO.

Here's what I am doing:
- create fifo in terminal 1: mkfifo /tmp/omxfifo
- start omxplayer in terminal 2:   omxplayer file.mp3 < /tmp/omxfifo
- in terminal 1, execute:   printf ' ' >> /tmp/omxfifo && sleep 0.5 && printf ' ' >> /tmp/omxfifo
- Playback starts.  I wait a few seconds and, on terminal 1, I execute:  printf 'q' >> /tmp/omxfifo
- The 'q', which means QUIT to omxplayer, does not do anything... In fact, I can send any other keyboard commands this way and they have no effect on omxplayer.
- There are no related logs that I can see in any file at /var/log

Note, that I am doing exactly the same process as above with mplayer and it works just fine.

I am not married to using a FIFO to remotely control omxplayer so if there's another way to achieve remote control of omxplayer please by all means point me in that direction.  BTW, I have also tried substituting omxplayer above with omxplayer.bin and I have the same issues.

VERSION INFORMATION
pi@raspberrypi:/var/log $ omxplayer -v
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Thu, 20 Jun 2019 14:19:17 +0000
        Version   : f06235c [master]
        Repository: https://github.com/popcornmix/omxplayer.git

Tried on RASPBERRY PI 2 b+, 3 B+ & pi 4  running Raspbian BUSTER
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux

**Comment by KenT2** [comment]
I found FIFO's difficult when I used them some years ago.
python-pexpect is better, DBUS is best
Examples of these in my repositories

**Comment by prusa3duser** [comment]
Thanks, I found the "dbuscontrol.sh" script which provides a user friendly way of sending DBUS commands to a running instance of omxplayer.  I had no idea omxplayer supported DBUS.
 I am now using that script successfully, at least to start/stop, pause and resume.  The seek function is not seeking forward or backward, but it does interrupt the playback momentarily.

**Comment by twinstef** [comment]
I try to use RaspberryCast ( see https://github.com/vincelwt/RaspberryCast) on a Raspberry Pi3 A+ under Raspbian BUSTER 
It's a chromecast like that uses python and omxplayer.

I had issue to control playback so i check the code and see that it uses the same method to pilot omxplayer:
  - create fifo  /tmp/cmd
  - launch omxplayer with this fifo input
  - close omxplayer with commands like : echo -n q > /tmp/cmd

Same issue: omxplayer launch the video but do not respond to further inputs in fifo.

Of course i can modify the python code but i imagine that a lot of applications use this way to pilot omxplayer and should not work from now on buster.
