### ISSUE TITLE
RPi 3B w/ Arch Linux Arm: omxplayer plays audio, but no video 

### ISSUE THREAD

**Issue by andrewboring** [popcornmix/omxplayer#739]
Raspberry Pi 3b with Arch Linux Arm with VC4.
Wayland+Weston with DRM backend. 

HDMI connected to Sunfounder 10" IPS LCD Display.
Changed to a Toshiba 720p TV after reading [this thread](https://github.com/popcornmix/omxplayer/issues/509).

I can play the same video without issue using both mpv and gstreamer, so I'm thinking it's a configuration issue specific to omxplayer's workings. 

```
$ omxplayer big_buck_bunny_720p_1mb.mp4 
Video codec omx-h264 width 1280 height 720 profile 77 fps 25.000000
Audio codec aac channels 6 samplerate 48000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1280x720@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
```

But no video. I can hear the audio through HDMI by default, but no video is displayed.

I've tried every `--display` option from [this thread](https://github.com/popcornmix/omxplayer/issues/738), but with the same result: audio plays, but no video.

I'm using Wayland/Weston and omxplayer from Arch, but also tried compiling omxplayer directly. Same result for both on the original 10" LCD display.

After switching back to an Arch-packaged omxplayer and the Toshiba display, I tried a few `--display` with 0, 1, 2, and 7 and the screen will turn full-screen-black briefly, then flip back to the Weston desktop with no visible video playing (while playing audio).

- omxplayer -g big_buck_bunny_720p_1mb.mp4: https://pastebin.com/gd891g1G
- strace omxplayer big_buck_bunny_720p_1mb.mp4: https://pastebin.com/FCpgip7w
- /boot/config.txt: https://pastebin.com/4AWzTpeA
- ~/.config/weston.ini: https://pastebin.com/mwkVqFPa

What am I missing?

**Comment by jehutting** [comment]
Afaik omxplayer doesn't work with /boot/config.txt line 
` ` ` dtoverlay=vc4-kms-v3d` ` `

**Comment by popcornmix** [comment]
> Afaik omxplayer doesn't work with /boot/config.txt line

correct

**Comment by andrewboring** [comment]
Ah. Well, that certainly was it.
Commented out the dtoverlay, reboot, and then switched to fbdev-backend for weston. Everything plays fine now. Thanks for that.

I hadn't encountered anything in my searches that indicated omxplayer was incompatible with the vc4 driver.  What's the reason omxplayer doesn't work with vc4-kms-v3d?

**Comment by popcornmix** [comment]
kms means the arm controls display. That means gpu cannot drive display.
omxplayer is a gpu side video player

**Comment by andrewboring** [comment]
Got it. Thanks for the clarification.
