### ISSUE TITLE
How to control multiple Omxplayer instances with dbuscontrol.sh

### ISSUE THREAD

**Issue by ashishbindal93** [popcornmix/omxplayer#742]
Hi

I am running multiple omxplayer player instances on raspberry pi over HDMI.
Please help me by providing code that can control multiple instances.

My script to start omxplayer instances..

```
screen -dmS camera1 sh -c 'while true; do omxplayer -- --layer 1 --live --win 4,4,454,342 http://192.168.1.201:8081; done; exec bash'
screen -dmS camera2 sh -c 'while true; do omxplayer --layer 1 --live --win 458,4,908,342 http://192.168.1.202:8081; done; exec bash'
screen -dmS camera3 sh -c 'while true; do omxplayer --layer 1 --live --win 912,4,1362,342 http://192.168.1.203:8081; done; exec bash'
#screen -dmS camera4 sh -c 'while true; do omxplayer --layer 1 --live --win 4,346,454,684 http://192.168.1.204:8081; done; exec bash'
#screen -dmS camera5 sh -c 'while true; do omxplayer --layer 1 --live --win 458,346,908,684 http://192.168.1.205:8081; done; exec bash'
screen -dmS camera6 sh -c 'while true; do omxplayer --layer 1 --live --win 912,346,1362,684 http://192.168.1.206:8081; done; exec bash'

```

I want to resize the movies on remote button press( already implemented in other file ) through code without killing them( Reinitiate new ones ).

Example :

Press button 1 :- Make camera1 full screen
Press nutton 2 :- Make camera2 full screen

I have tried alot on my behalf with omxplayer/dbuscontrol.sh but could not succeed to make it work.

**Comment by thecalle** [comment]
You must define a custom DBUS Name for every streaming you open using the **--dbus_name** option.

Then you must customize the dbuscontrol.sh file because it refers to the single default DBUS name created by omxplayer by default.

**Comment by ashishbindal93** [comment]
What should I change in dbus file?
Can you guide me please?

**Comment by thecalle** [comment]
DBus is a bus processes use to comunicate each other. If you launch two or more OMX you need to set a different  dbus name for every process so you can control a specific process sending commands to the correct name.

Inviato da 📞 iPhone

**Comment by ashishbindal93** [comment]
@thecalle I got your point.
I have named the cameras with this option

--dbus_name=com.bindal.ashish.camera1
--dbus_name=com.bindal.ashish.camera2
--dbus_name=com.bindal.ashish.camera3
--dbus_name=com.bindal.ashish.camera4
--dbus_name=com.bindal.ashish.camera5
--dbus_name=com.bindal.ashish.camera6

Now what should be done in dbuscontrol.sh file?
Please give me code for dbuscontrol.sh

**Comment by jehutting** [comment]
Extend ```dbuscontrol.sh``` with a second argument which is the name of the player.

Add to ```dbuscontrol.sh```
```
destination=${2:-org.mpris.MediaPlayer2.omxplayer}
```

and use ```$destination``` instead of the (fixed) name ```org.mpris.MediaPlayer2.omxplayer``` as the value for the ```--dest``` argument of ```dbus-send```.

E.g. the modified pause command would be
```
pause)
	dbus-send --print-reply=literal --session --dest=$destination /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Action int32:16 >/dev/null
	;;
```

With the modified ```dbuscontrol.sh``` e.g. to pause camera1 the call would be:
```
dbuscontrol.sh pause com.bindal.ashish.camera1
```


[dbuscontrol.sh.zip](https://github.com/popcornmix/omxplayer/files/3774951/dbuscontrol.sh.zip)

**Comment by ashishbindal93** [comment]
Thanks. This works very well.
