### ISSUE TITLE
video stop to play after 7 minutes on raspbian buster

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#743]
Hi, I have some raspbian buster with omxoplayer playing 247 perfectly, but one device has somethign different and it stop to play the video (the video should play in loop) after about 7 minutes and it crash with a strange screen:
here the 66mb video .mp4 h264 25fps (duration 6minutes and 14 seconds): 
https://wetransfer.com/downloads/d1e14da101f9ecefd964b2c7322aa52f20191003113802/be8d009ed66103cd739272ddb0e585a520191003113802/117cef

and here the crash screen (not moving):
https://wetransfer.com/downloads/18ef6d0f329e1f66bf7a9c10277d890820191003114039/604d46cf73b7c84b26cbaf41539e9bd520191003114039/592c53

**Comment by popcornmix** [comment]
Are you saying most Pi's play that video okay, but one Pi fails to play it?
Or are you saying most video files play forever, but that one video file fails?

**Comment by matteoraggi** [comment]
1) yes, one pi fails to play the video, but it is aso a different video, this one that I linked up on my first post here. 
2) yes, all videos are in -loop but this one fail , I don't know if it is able to start the second loop.. I am far from this device into few days maybe I can go in front of the monitor to check better what is happening.

**Comment by matteoraggi** [comment]
I see lines saying under voltage detected (0x000050000000)
maybe is that the issue? maybe should I change the power supplier?

**Comment by matteoraggi** [comment]
false alarm! the video was broken from ffmpeg that was receiveing one frame in the wrong size :-) so omxplayer is wtill working perfectly to be, thanks for patience!
