### ISSUE TITLE
Omxplayer flickering on 2 monitor if no internet connetcion?

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#748]
When playing omxplayer on double monitor with raspberry pi 4 2gbram, sometimes I was watching a flickering of the 2 monitor without be able to understand why. After many thinkings then from today it looks that I am able to recreate the issue:  
https://wetransfer.com/downloads/ad07850dd4a95362e10917848e97ad2a20191015103902/1b4765ab6adca475166b79a7c2cca3cb20191015103902/aa6947
I just run this command:
nohup sudo /usr/bin/omxplayer --display 2 --layer 1 --orientation 0 --loop --no-osd /home/pi/Videos/vdo_1.mp4 &

nohup sudo /usr/bin/omxplayer --display 7 --layer 1 --orientation 0 --loop --no-osd /home/pi/Videos/vdo_2.mp4 &

**Comment by popcornmix** [comment]
It looks like you are running more than two copies of omxplayer when this flickers.
How are you launching omxplayer?
Can you run ``ps aux |grep omx`` (e.g. from ssh) when the monitors are flickering.

**Comment by matteoraggi** [comment]
`ps  aux   |   grep    /usr/bin/omxplayer
root     24148  0.0  0.1   9952  3196 pts/0    S    15:14   0:00 sudo /usr/bin/omxplayer --display 2 --layer 1 --orientation 0 --loop --no-osd /home/pi/Videos/vdo_1.mp4
root     24153  0.0  0.1   7676  2632 pts/0    S    15:14   0:00 /bin/bash /usr/bin/omxplayer --display 2 --layer 1 --orientation 0 --loop --no-osd /home/pi/Videos/vdo_1.mp4
root     24164  1.7  2.0 195424 38756 pts/0    SLl  15:14   0:03 /usr/bin/omxplayer.bin --display 2 --layer 1 --orientation 0 --loop --no-osd /home/pi/Videos/vdo_1.mp4
root     24165  0.0  0.1   9952  3176 pts/0    S    15:14   0:00 sudo /usr/bin/omxplayer --display 7 --layer 1 --orientation 0 --loop --no-osd /home/pi/Videos/vdo_2.mp4
root     24170  0.0  0.1   7676  2608 pts/0    S    15:14   0:00 /bin/bash /usr/bin/omxplayer --display 7 --layer 1 --orientation 0 --loop --no-osd /home/pi/Videos/vdo_2.mp4
root     24181  1.7  2.0 194860 38964 pts/0    SLl  15:14   0:03 /usr/bin/omxplayer.bin --display 7 --layer 1 --orientation 0 --loop --no-osd /home/pi/Videos/vdo_2.mp4
pi       24935  0.0  0.0   7348   560 pts/0    S+   15:17   0:00 grep --color=auto /usr/bin/omxplayer`

**Comment by matteoraggi** [comment]
If I just launch the loop while the device is offline it plays wel, if instead I launch it while the router is searching for the internet signal , os the lan is active but without internet, then omxplayer is flickering.
So maybe some internet calls are going to be stuck and they are disturbing omxplayer?

**Comment by matteoraggi** [comment]
yes at my second test it worked (it stillshow the flickering), waiting around 30 seconds to switch on the router after rpi4..

**Comment by matteoraggi** [comment]
Yes you are right are mutiple omxplayer instances contemporarily and it is a bug of my script and I go to patch it, thanks.
