### ISSUE TITLE
Very loud audio by default

### ISSUE THREAD

**Issue by mariomadproductions** [popcornmix/omxplayer#751]
Maybe this isn't something that can be solved, as for others the audio might be very quiet by default, and you can change the volume at startup (i'm using it from the command line). But maybe this is a valid issue? This is on raspbian on rpi3b. omxplayer version: 20190723+gitf543a0d-1.

**Comment by popcornmix** [comment]
Duplicate of https://github.com/popcornmix/omxplayer/issues/750

**Comment by mariomadproductions** [comment]
Oops, didn't notice I made that.
