### ISSUE TITLE
Pixel format 4:2:2 not working

### ISSUE THREAD

**Issue by cityadpro** [popcornmix/omxplayer#753]
Hello all,

I've been doing some tests with different video files and I've found that all video files I've been trying to play that use the 4:2:2 pixel format do not play in omxplayer. If I convert these files to 4:2:0 pixel format then they are playing correctly.
I've been googling around for such problem and I've not been able to find anything related to it.

Does anybody know whether these files (with 4:2:2 pixel format) should be working?

I'm using latest Raspbian Buster with a RPi 4B (I've also tried with a RPi 3B and the problem is also there).

Here are some sample files to test:

[4:2:0 working file](https://drive.google.com/open?id=1_ySjDwB4pEEvvyStKw1ZrlNHb13j-Ju8)
[4:2:2 NOT working file](https://drive.google.com/open?id=1aekRrcb3_qyUAGBeazCXE5sArPBA_58D)

**Comment by popcornmix** [comment]
4:2:2 video is not supported by the hardware decoder on videocore (and on almost no hardware decoders).

These videos will only work with software decode which omxplayer doesn't support.
Software decode probably won't be fast enough to play these.

**Comment by cityadpro** [comment]
Hello, thank you very much for your fast answer, I wasn't aware of this restriction.

Is there any other restriction or all the rest of h264 encoded video will play correctly with omxplayer?

Thank you!

**Comment by popcornmix** [comment]
H.264 hardware is specced to High profile Level 4.1 H.264 (BluRay).

**Comment by cityadpro** [comment]
Thank you!
