### ISSUE TITLE
v4l2 request API

### ISSUE THREAD

**Issue by wasalm** [popcornmix/omxplayer#760]
_Sorry for posting this question in the wrong repository, but I don't know where else to post them._

I see that people are implementing the v4l2 request api in ffmpeg in the https://github.com/popcornmix/FFmpeg/tree/kodi_v4l2_1 branch.
I like to experiment with these new feature, but somehow I am not able to enable to compile them on Raspbian.
I see that configure checks if linux/videodev2.h contains the constant V4L2_PIX_FMT_HEVC_SLICE, which Raspbian doesn't have.

I was wondering which drivers or OS I need to install in order to compile ffmpeg with the new request api.

Thanks for the help.

**Comment by popcornmix** [comment]
This is very experimental and probably won't be stable for a few months.
You'll need this kernel https://github.com/popcornmix/linux/tree/v4l2_3 to have v4l2 support
and you'll need to install headers from this tree to build kodi under raspbian.

The trees are just being shared to allow discussion of how the V4L2 support is being added (v4l2 request api is still not merged in kernel or ffmpeg).

If you want something that "just works" then it's best to wait.

**Comment by wasalm** [comment]
Thanks, im going to look into that.
