### ISSUE TITLE
Supported Media Type？

### ISSUE THREAD

**Issue by AnterCreeper** [popcornmix/omxplayer#763]

**Comment by popcornmix** [comment]
omxplayer only supports gpu codecs.
That is H264 and MJPEG on Pi0-4.
Pi0-3 can also do MPEG4.
Pi0-3 can also do VC1/MPEG2 when the appropriate codec licence is bought.

VLC is a recommended alternative and will support all codecs (software decode when hardware decode is not available), including HEVC.

**Comment by AnterCreeper** [comment]
Pretty thanks.
Hope that it could be added to the usage.
