### ISSUE TITLE
.srt Subtitle styling ignored

### ISSUE THREAD

**Issue by udayreddykaipa** [popcornmix/omxplayer#774]
when tried applying color and bold styles to subtitles text they are ignored and displayed as plain text.
> italic style is working,

`single subtitle in<i>italic</i><font color="FF0000">in Red</font><b>Bold</b>`

**Comment by popcornmix** [comment]
Subtitle support in omxplayer is basic.
For more advanced options you should consider kodi or vlc.

**Comment by udayreddykaipa** [comment]
Thanks for quick reply and advice.
Thank you.
