### ISSUE TITLE
Changing keybindings

### ISSUE THREAD

**Issue by darklord111** [popcornmix/omxplayer#781]
`omxplayer -k`
Shows as an example "up arrow : seek +600 seconds", etc.
I was wondering, is it possible to change the values of keybindings, like instead of 600 seconds, make it 10 seconds?
If so, how would I go about doing that? Will I need to edit something in the source code, or is there a simple .config file I can edit.
Thanks!

**Comment by popcornmix** [comment]
Change the `m_incr = 600.0`/`m_incr = -600.0` here
https://github.com/popcornmix/omxplayer/blob/f543a0d0e707ab56415f17b0ca6d397394ee8b63/omxplayer.cpp#L1303-L1330

**Comment by darklord111** [comment]
Ok thanks!
