### ISSUE TITLE
Second Screen getting incorrect PAR

### ISSUE THREAD

**Issue by danielwells** [popcornmix/omxplayer#784]
I see that omplayer is getting deprecated in favor of VLC.  But it has been working great for our project (and plays our streams more consistently and accurately than VLC, which seems to struggle with our HLS streams).  I am hoping it can already do what I need but I am struggling to find the proper way to do it. 

I am using and RPi 4 with a touchscreen on the DSI connection and playing fullscreen video on the 1st HDMI output.  The touchscreen is 800x480 and the tv it is connected to is 1080p.  When I play a video in this hw config, omx reports the 'par' as 1.25 and the video is vertically squashed.  I can't seem to find a way to force omx to use a different par.  The aspect mode set to 'stretch' works fine when the source content is 16:9.  But if we are streaming other aspects ratios we have the opposite issues (video is stretched too tall).  

Here is the command we are using

omxplayer --display 2 --adev hdmi VIDEO_FILE

Any help would be appreciated.

**Comment by popcornmix** [comment]
You could try using --win to force aspect ratio

**Comment by danielwells** [comment]
That works.  I'll need to run some calculations for some of the streams 😄 

But for most of them them they will just be --win 0,0,1920,1080

Thanks.
