### ISSUE TITLE
Orientation does not apply to subtitles

### ISSUE THREAD

**Issue by rtomasa** [popcornmix/omxplayer#791]
Hi, I'm using the `orientation` video rotation parameter and I've noticed that the subtitles remain in the original position so that if I rotate a video to display the same in a vertical monitor, the subtitles are displayed vertically.

Is there any other option to handle this behaviour?

BR

**Comment by popcornmix** [comment]
omxplayer has been deprecated in favour of vlc.
Can you try this with vlc?

**Comment by rtomasa** [comment]
Oohh then I think that I’m in a dead end since I’m on Raspbian Lite (no X), so VLC is not an option here.

Thanks for your quick response, at least now I know that I need to search for another different solution.

________________________________
De: popcornmix <notifications@github.com>
Enviado: Tuesday, November 17, 2020 2:54:42 PM
Para: popcornmix/omxplayer <omxplayer@noreply.github.com>
Cc: Rubén Tomás <ruben.tomas@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [popcornmix/omxplayer] Orientation does not apply to subtitles (#791)


omxplayer has been deprecated in favour of vlc.
Can you try this with vlc?

**Comment by popcornmix** [comment]
VLC runs outside of X (in a fullscreen mode).

**Comment by rtomasa** [comment]
Really 😮? I had no idea about that. I always thought that it required to be run on top of X.

Many thanks for the clarification on that. I’ll close this issue now.

________________________________
De: popcornmix <notifications@github.com>
Enviado: Tuesday, November 17, 2020 3:22:43 PM
Para: popcornmix/omxplayer <omxplayer@noreply.github.com>
Cc: Rubén Tomás <ruben.tomas@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [popcornmix/omxplayer] Orientation does not apply to subtitles (#791)


VLC runs outside of X (in a fullscreen mode).
