### ISSUE TITLE
display elapsed/total time during pause ceased working recently

### ISSUE THREAD

**Issue by captain** [popcornmix/omxplayer#797]
Until circa 2020 November omxplayer would display elapsed | total time during pause.  This is an invaluable feature!  I don't know what happened, but it seems to be gone from every omxplayer on every machine now, so I'm guessing some code changed.  I grepped all the source code for show_time but came up empty.  I noticed show_time_offset used in a different fork of the code, but I've always just run the official distributed binaries, so I don't know what to do.

**Comment by popcornmix** [comment]
omxplayer is deprecated and there have been no changes for many months.
Note: OSD does not work with fkms driver. Have you enabled that in config.txt?

**Comment by captain** [comment]
That appears to have been the problem.  THANK YOU popcornmix!
