### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by obadz** [popcornmix/omxplayer#8]
Sorry didn't find an E-mail address so figured I would try reaching out through an Issue.

I'd like to do some work on omxplayer but I have to do say I don't know where to begin in terms of compiling it.

1)  Is it possible to compile it on amd64/i386 for usage amd64/i386 (not cross compiling) for testing? Is it expected to work correctly on these platforms? How to compile this way?

2) For cross compiling, it seems that the makefile is pretty much setup for this. Should the cross compiler be installed following this guide? http://airwiki.ws.dei.polimi.it/index.php/Cross-compiling_for_the_RaspberryPi

Thanks for the guidance,
David-

**Comment by Ruffio** [comment]
@popcornmix I believe this can be closed
