### ISSUE TITLE
IPTV live stream stop playing

### ISSUE THREAD

**Issue by spherewallpapers** [popcornmix/omxplayer#814]
Hi, I'm using omxplayer to play live stream channels. I just realized that in most cases depending on the streaming server, the live stream video switches live video sources on the same URL when showing commercials. In that case, the video freezes, but the connection is still active, now if I reconnect and let's say there is no commercial the live video works fine. I have tried --loop, -b, -r but nothing works.
Here is an example to replicate the issue.

`omxplayer -r --display 4 -o hdmi "http://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/5ba3fb9c4b078e0f37ad34e8/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=1YNY&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&profileLimit=&profileFloor=&embedPartner=samsung-tvplus"`

**Comment by popcornmix** [comment]
See: https://github.com/popcornmix/omxplayer#readme and consider switching to VLC.
