### ISSUE TITLE
Playing audio to individual HDMI

### ISSUE THREAD

**Issue by spherewallpapers** [popcornmix/omxplayer#815]
Hi, I'm currently playing two videos instance on two TV via HDMI 1 and HDMI 2 and I was wondering how can I send audio from video 2 playing on HDMI 2? All I can get is audio on HDMI 1.

**Comment by popcornmix** [comment]
It may be possible using `--adev alsa:<device>` with device using the hdmi2 alsa device.
But read https://github.com/popcornmix/omxplayer#readme and consider switching to vlc.

**Comment by spherewallpapers** [comment]
Thanks for the answer this fixed my problem.
`DISPLAY=:0 omxplayer --adev alsa:hw:1,0 --dbus_name org.mpris.MediaPlayer2.omxplayer1  --display=7 video.mp4`
And about switching to VLC, NEVER! I can do stuff with Omxplayer  that I will not be able to do with others players and I already tried most video players. Too bad developing this any furder ended.
