### ISSUE TITLE
Volume control while playing 

### ISSUE THREAD

**Issue by rijotech** [popcornmix/omxplayer#816]
I'm trying to control the volume while playing a video using `xdotool key minus` and `xdotool key plus` but it doesn't seem to work and I'm wondering if this is possible via command line?

**Comment by popcornmix** [comment]
omxplayer isn't an X app, so I wouldn't expect that to work.
Perhaps the DBUS control section of readme would be helpful.

**Comment by rijotech** [comment]
I can't still figure out the DBUS control but I found a possible solution here to control the volume via stdin. the only problem is I'm getting a permission denied after executing `sudo echo -n "-" > /proc/$(pidof omxplayer.bin)/fd/0` `-bash: /proc/$(pidof omxplayer.bin)/fd/0: Permission denied`
I got this info from [this site  ](https://newbedev.com/adjust-audio-volume-level-with-cli-omxplayer-raspberry-pi)

**Comment by popcornmix** [comment]
`sudo echo -n "-" > [file` is almost certainly not what you want.
That runs echo as root but pipes the output as a normal user.

Try `echo -n "-" | sudo tee [file]` which will actually pipe the output as root.
