### ISSUE TITLE
DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by rijotech** [popcornmix/omxplayer#820]
I'm facing problems with DBus. 
I have the latest Omxplayer installed 
```
 omxplayer --version
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Thu, 01 Aug 2019 12:50:43 +0000
        Version   : f543a0d [master]
```
and running custom instances of it, now when I run the command via terminal. 
`sudo -u pi DISPLAY=:0.0  ./dbuscontrol.sh pause`
All I'm getting is 
`Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer3.omxplayer2 was not provided by any .service files`
But when I check htop the instance is running.
What am I doing wrong?
![image](https://user-images.githubusercontent.com/17016357/181122079-b432cd66-6b25-462b-9f35-06ccca8306d2.png)

**Comment by popcornmix** [comment]
You should read the README at https://github.com/popcornmix/omxplayer
omxplayer will not be getting any updates.
VLC is the recommended alternative if there are features missing from the existing version of omxplayer.
