### ISSUE TITLE
Will omxplayer stop working eventually?

### ISSUE THREAD

**Issue by rijotech** [popcornmix/omxplayer#825]
This is not an issues but a question, will omxplayer stop working in the near future? Since it depend on OpenMAX API?

**Comment by popcornmix** [comment]
It depends if you are happy running it on an older version of an OS.
It currently is easy to install and use on buster. 
It currently isn't directly supported on (32-bit) bullseye, but can be made to work by switching to the fkms driver and installing the openmax libs.
It's hard to say if it will work on the next OS (bookworm). Probably in a similar manner to bullseye it can be made to work.

But there is no reason why a working omxplayer will stop working on a older version of OS.
But obviously you will miss out on new applications or features that require a newer OS.

**Comment by rijotech** [comment]
Great thanks and Oh yes I'm SUPER HAPPY, I'm developing a Digital Signage and is coming out really nice!.
