### ISSUE TITLE
Compiling on Raspberry Pi 5 running Debian 12 32bits?

### ISSUE THREAD

**Issue by rijotech** [popcornmix/omxplayer#836]
There is any workaround to get omxplayer to run on Raspberry Pi 5 Debian 12 32bits?
I'm currently trying some stuff around but no luck.

**Comment by rijotech** [comment]
It's sad to see this player go! Because of this player, I was able to develop a nice [signage player](https://www.youtube.com/watch?v=uaI_q3HcpVI), It's too bad I cannot port this to pi5.

**Comment by popcornmix** [comment]
See [this post](https://forums.raspberrypi.com/viewtopic.php?p=2240895#p2240895).
What you are hoping for is impossible.

The Pi5 is perfectly capable of digital signage if you switch to standard linux API (v4l2/drm).
