### ISSUE TITLE
omxplayer freezes temporarily playing mp4 streams

### ISSUE THREAD

**Issue by schumra** [popcornmix/omxplayer#90]
I've got a recurring problem when trying to use omxplayer on Raspberry Pi. And this happens with the majority of mp4 video streams I've tried, but not all. When I start omxplayer I get about 1 second of AV. Then it freezes. I can see the network is still reading data which I confirmed through other OS utilities, like netstat, etc. But the picture is frozen, and no sound. Then about 15 minutes later, it starts playing and the picture/sound is crystal clear with no issues. I am at the latest Rasberrian, omxplayer, and Raspberry firmware. 

I can't find any difference in the mp4 streams, as far as I know they were all ripped/encoded the same way.

Any recommendations would be appreciated! Please let me know if I can provide additional information. 

Thank you.

Randall

**Comment by Ruffio** [comment]
@schumra is this still an issue?

**Comment by schumra** [comment]
I figured it out.

The media stream had a bunch of junk (some kind of data, but not obvious
media data) in it. And that caused resource saturation on the Raspberry Pi
player, and the hangs. If I strip out the junk everything is fine.

Randall

On Tue, Jun 23, 2015 at 5:06 PM, Rasmus Christiansen <
notifications@github.com> wrote:

> @schumra <https://github.com/schumra> is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/popcornmix/omxplayer/issues/90#issuecomment-114641910>
> .
>



-- 
Randall Schumm, EMCPA, SCSE, VTSP
C: (407) 733-3369
E: randall.schumm@gmail.com

**Comment by Ruffio** [comment]
@popcornmix this can be closed.
