### ISSUE TITLE
Prebuilt Binary via apt-get

### ISSUE THREAD

**Issue by pukster** [popcornmix/omxplayer#92]
Is there any chance of easily downloading this with apt-get? I only ask because I am looking at the instructions for installing it, and one needs gcc-4.7, which I don't have on my raspi, and can't download. I suppose I could cross compile it, but I never managed to get the last two cross compilers to, well, compile. 

At the very least clear up the ambiguity in the README file, I can't tell if gcc-4.7 is required for both the cross compilation and the 'native' compilation on the raspi, or just for the cross compilation. If it's the former then I assume I have to install gcc-4.7 from source.

**Comment by Ruffio** [comment]
@popcornmix this can be closed
