### ISSUE TITLE
Image viewer : OMXImage ??

### ISSUE THREAD

**Issue by fcarlier** [popcornmix/omxplayer#94]
Hi,

It's possible to reintegrated OMXImage from xbmc ?
omxplayer could be so image viewer ;)

https://github.com/xbmc/xbmc/blob/master/xbmc/cores/omxplayer/OMXImage.cpp
I think xbmc/omxplayer only supports jpeg format, but it is a good start. 

Otherwise i have tested fbida in my repository. it's cool with different format support (ffmpeg ;)

A+

**Comment by Ruffio** [comment]
@popcornmix of this is not going to be implemented, this feature request should be closed.
